const recommendedChineseSeries = [
  {
    id: 1,
    title: "The Untamed",
    platform: "Tencent / Netflix",
    genre: "Xianxia / Fantasy / Bromance",
    year: 2019,
    popularity: 95,
    seasons: 1,
    episodes: 50,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 2,
    title: "Love Between Fairy and Devil",
    platform: "iQIYI / Netflix",
    genre: "Xianxia / Fantasy / Romance",
    year: 2022,
    popularity: 92,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 3,
    title: "Hidden Love",
    platform: "Youku / Netflix",
    genre: "Romance / Youth / Slice of Life",
    year: 2023,
    popularity: 94,
    seasons: 1,
    episodes: 25,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 4,
    title: "Love O2O",
    platform: "Tencent / Netflix",
    genre: "Romance / Gaming / Campus",
    year: 2016,
    popularity: 91,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 5,
    title: "The Long Ballad",
    platform: "Tencent / Viki",
    genre: "Historical / War / Romance",
    year: 2021,
    popularity: 90,
    seasons: 1,
    episodes: 49,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 6,
    title: "Put Your Head on My Shoulder",
    platform: "Tencent / Netflix",
    genre: "Romance / Youth / Comedy",
    year: 2019,
    popularity: 89,
    seasons: 1,
    episodes: 24,
    runtime: "40 min",
    language: "Hindi Dubbed"
  },
  {
    id: 7,
    title: "Who Rules the World",
    platform: "Tencent / Netflix",
    genre: "Wuxia / Romance / Action",
    year: 2022,
    popularity: 88,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 8,
    title: "My Journey to You",
    platform: "iQIYI / Netflix",
    genre: "Historical / Spy / Romance",
    year: 2023,
    popularity: 86,
    seasons: 1,
    episodes: 24,
    runtime: "50 min",
    language: "Hindi Dubbed"
  },
  {
    id: 9,
    title: "Go Ahead",
    platform: "Netflix",
    genre: "Family / Slice of Life / Youth",
    year: 2020,
    popularity: 91,
    seasons: 1,
    episodes: 46,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 10,
    title: "The First Frost",
    platform: "Youku / Netflix",
    genre: "Romance / Youth / Slice of Life",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 11,
    title: "Love Like the Galaxy",
    platform: "Tencent / Viki",
    genre: "Historical / Romance / Political",
    year: 2022,
    popularity: 90,
    seasons: 2,
    episodes: 56,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 12,
    title: "Till the End of the Moon",
    platform: "Youku / Netflix",
    genre: "Xianxia / Fantasy / Romance",
    year: 2023,
    popularity: 93,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 13,
    title: "Love Me, Love My Voice",
    platform: "iQIYI",
    genre: "Romance / Healing / Modern",
    year: 2023,
    popularity: 84,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 14,
    title: "A Familiar Stranger",
    platform: "Youku",
    genre: "Historical / Identity Swap / Romance",
    year: 2022,
    popularity: 83,
    seasons: 1,
    episodes: 18,
    runtime: "25 min",
    language: "Hindi Dubbed"
  },
  {
    id: 15,
    title: "Lost You Forever",
    platform: "Tencent",
    genre: "Xianxia / Romance / Fantasy",
    year: 2023,
    popularity: 91,
    seasons: 1,
    episodes: 39,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 16,
    title: "Meet Yourself",
    platform: "Hunan TV / Youku",
    genre: "Slice of Life / Healing / Rural",
    year: 2023,
    popularity: 89,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 17,
    title: "The Romance of Tiger and Rose",
    platform: "Tencent / MX Player",
    genre: "Historical / Comedy / Romance",
    year: 2020,
    popularity: 87,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 18,
    title: "Miss the Dragon",
    platform: "Tencent / Viki",
    genre: "Fantasy / Romance / Mythical",
    year: 2021,
    popularity: 85,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 19,
    title: "Rattan",
    platform: "Youku / Viki",
    genre: "Fantasy / Sci-Fi / Mystery",
    year: 2021,
    popularity: 84,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 20,
    title: "A Love So Beautiful",
    platform: "Tencent / Netflix",
    genre: "Youth / Romance / School",
    year: 2017,
    popularity: 90,
    seasons: 1,
    episodes: 23,
    runtime: "24 min",
    language: "Hindi Dubbed"
  },
  {
    id: 21,
    title: "The Blood of Youth",
    platform: "Youku",
    genre: "Wuxia / Fantasy / Adventure",
    year: 2022,
    popularity: 88,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 22,
    title: "You Are My Glory",
    platform: "Tencent / Viki",
    genre: "Modern / Romance / Gaming",
    year: 2021,
    popularity: 91,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 23,
    title: "The Legends",
    platform: "iQIYI / MX Player",
    genre: "Xianxia / Fantasy / Romance",
    year: 2019,
    popularity: 88,
    seasons: 1,
    episodes: 56,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 24,
    title: "Sweet Teeth",
    platform: "iQIYI / MX Player",
    genre: "Romance / Dentist / Modern",
    year: 2021,
    popularity: 87,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 25,
    title: "Forever and Ever",
    platform: "iQIYI / Netflix",
    genre: "Modern / Romance / Marriage",
    year: 2021,
    popularity: 86,
    seasons: 1,
    episodes: 30,
    runtime: "40 min",
    language: "Hindi Dubbed"
  },
  {
    id: 26,
    title: "Light Chaser Rescue",
    platform: "Tencent / iQIYI",
    genre: "Rescue / Romance / Action",
    year: 2022,
    popularity: 84,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 27,
    title: "Reset",
    platform: "Tencent / Netflix",
    genre: "Sci-Fi / Thriller / Time Loop",
    year: 2022,
    popularity: 90,
    seasons: 1,
    episodes: 15,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 28,
    title: "Under the Power",
    platform: "iQIYI / MX Player",
    genre: "Historical / Detective / Romance",
    year: 2019,
    popularity: 89,
    seasons: 1,
    episodes: 55,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 29,
    title: "Love is Sweet",
    platform: "iQIYI / MX Player",
    genre: "Modern / Office / Romance",
    year: 2020,
    popularity: 88,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 30,
    title: "The Legend of Zang Hai",
    platform: "Tencent",
    genre: "Historical / Epic / Military",
    year: 2025,
    popularity: 91,
    seasons: 1,
    episodes: 42,
    runtime: "45 min",
    language: "English Dubbed"
  },
{
    id: 31,
    title: "Love in Pavilion",
    platform: "Youku / Netflix",
    genre: "Historical / Romance / Palace",
    year: 2025,
    popularity: 88,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 32,
    title: "Legend of the Female General",
    platform: "Tencent",
    genre: "Historical / Military / Romance",
    year: 2025,
    popularity: 90,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 33,
    title: "The Immortal Ascension",
    platform: "iQIYI",
    genre: "Xianxia / Cultivation / Fantasy",
    year: 2025,
    popularity: 87,
    seasons: 1,
    episodes: 34,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 34,
    title: "Fox Spirit Matchmaker: Sword and Beloved",
    platform: "Tencent",
    genre: "Fantasy / Romance / Mythical",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 35,
    title: "The Prisoner of Beauty",
    platform: "Youku",
    genre: "Historical / Romance / Drama",
    year: 2025,
    popularity: 91,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 36,
    title: "Love of the Divine Tree",
    platform: "iQIYI",
    genre: "Fantasy / Romance / Mythical",
    year: 2025,
    popularity: 88,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 37,
    title: "A Dream Within a Dream",
    platform: "Tencent",
    genre: "Mystery / Romance / Psychological",
    year: 2025,
    popularity: 86,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 38,
    title: "Ski into Love",
    platform: "Youku",
    genre: "Sports / Romance / Youth",
    year: 2025,
    popularity: 85,
    seasons: 1,
    episodes: 23,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 39,
    title: "The Best Thing",
    platform: "iQIYI",
    genre: "Romance / Family / Drama",
    year: 2025,
    popularity: 90,
    seasons: 1,
    episodes: 28,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 40,
    title: "The Legend of Shen Li",
    platform: "Youku / Netflix",
    genre: "Xianxia / Romance / Action",
    year: 2024,
    popularity: 92,
    seasons: 1,
    episodes: 39,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 41,
    title: "Love Never Fails",
    platform: "iQIYI",
    genre: "Fantasy / Romance / Mythical",
    year: 2025,
    popularity: 87,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 42,
    title: "Youthful Glory",
    platform: "Tencent",
    genre: "Youth / Romance / School",
    year: 2025,
    popularity: 84,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 43,
    title: "A Love Never Lost",
    platform: "Youku",
    genre: "Historical / War / Romance",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 44,
    title: "Love for You",
    platform: "Tencent",
    genre: "Modern / Romance / Drama",
    year: 2025,
    popularity: 85,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 45,
    title: "Eternal Brotherhood",
    platform: "iQIYI",
    genre: "Wuxia / Brotherhood / Action",
    year: 2024,
    popularity: 88,
    seasons: 2,
    episodes: 48,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 46,
    title: "The Rise of Ning",
    platform: "Youku",
    genre: "Historical / Political / Drama",
    year: 2024,
    popularity: 86,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 47,
    title: "Reborn",
    platform: "Tencent",
    genre: "Crime / Thriller / Mystery",
    year: 2025,
    popularity: 87,
    seasons: 1,
    episodes: 23,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 48,
    title: "Amidst a Snowstorm of Love",
    platform: "Youku / Netflix",
    genre: "Romance / Sports / Healing",
    year: 2024,
    popularity: 90,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 49,
    title: "My Girlfriend is an Alien",
    platform: "Tencent / MX Player",
    genre: "Fantasy / Romance / Comedy",
    year: 2019,
    popularity: 89,
    seasons: 2,
    episodes: 52,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 50,
    title: "Sweet Sweet",
    platform: "Youku / MX Player",
    genre: "Romance / Comedy / Healing",
    year: 2021,
    popularity: 88,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
{
    id: 51,
    title: "Love Scenery",
    platform: "Tencent / MX Player",
    genre: "Romance / Music / College",
    year: 2021,
    popularity: 86,
    seasons: 1,
    episodes: 31,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 52,
    title: "Please Feel at Ease Mr. Ling",
    platform: "Tencent / MX Player",
    genre: "Romance / Comedy / Modern",
    year: 2021,
    popularity: 88,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 53,
    title: "The Flame’s Daughter",
    platform: "Youku / Netflix",
    genre: "Wuxia / Romance / Action",
    year: 2018,
    popularity: 84,
    seasons: 1,
    episodes: 52,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 54,
    title: "When We Were Young",
    platform: "iQIYI",
    genre: "Youth / School / Retro",
    year: 2018,
    popularity: 85,
    seasons: 1,
    episodes: 24,
    runtime: "40 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 55,
    title: "The Double",
    platform: "Youku",
    genre: "Historical / Revenge / Romance",
    year: 2024,
    popularity: 87,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 56,
    title: "Love and Destiny",
    platform: "iQIYI / MX Player",
    genre: "Xianxia / Fantasy / Romance",
    year: 2019,
    popularity: 89,
    seasons: 1,
    episodes: 60,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 57,
    title: "The Blue Whisper",
    platform: "Youku",
    genre: "Fantasy / Romance / Adventure",
    year: 2022,
    popularity: 86,
    seasons: 2,
    episodes: 42,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 58,
    title: "My Amazing Boyfriend",
    platform: "Tencent",
    genre: "Fantasy / Supernatural / Romance",
    year: 2016,
    popularity: 83,
    seasons: 2,
    episodes: 48,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 59,
    title: "Sword Snow Stride",
    platform: "Tencent",
    genre: "Wuxia / Political / Action",
    year: 2021,
    popularity: 88,
    seasons: 1,
    episodes: 38,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 60,
    title: "Reset in July",
    platform: "Youku",
    genre: "Romance / Youth / Slice of Life",
    year: 2024,
    popularity: 85,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 61,
    title: "Find Yourself",
    platform: "Netflix",
    genre: "Modern / Romance / Drama",
    year: 2020,
    popularity: 87,
    seasons: 1,
    episodes: 41,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 62,
    title: "Falling Into Your Smile",
    platform: "Tencent / MX Player",
    genre: "Esports / Romance / Comedy",
    year: 2021,
    popularity: 92,
    seasons: 1,
    episodes: 31,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 63,
    title: "The Imperial Coroner",
    platform: "Youku",
    genre: "Historical / Crime / Detective",
    year: 2021,
    popularity: 84,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 64,
    title: "My Little Happiness",
    platform: "Tencent / MX Player",
    genre: "Romance / Comedy / Medical",
    year: 2021,
    popularity: 89,
    seasons: 1,
    episodes: 28,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 65,
    title: "First Romance",
    platform: "iQIYI / YouTube",
    genre: "Youth / College / Romance",
    year: 2020,
    popularity: 86,
    seasons: 1,
    episodes: 24,
    runtime: "35 min",
    language: "English Dubbed"
  },
];