const recommendedChineseSeries = [
  {
    id: 1,
    title: "Eternal Love",
    platform: "Tencent",
    genre: "Romance, Fantasy",
    year: 2017,
    popularity: 97,
    language: "Mandarin",
    seasons: 1,
    episodes: 58,
    runtime: "45min"
  },
  {
    id: 2,
    title: "The Untamed",
    platform: "Tencent",
    genre: "Fantasy, Historical",
    year: 2019,
    popularity: 95,
    language: "Mandarin",
    seasons: 1,
    episodes: 50,
    runtime: "45min"
  },
  {
    id: 3,
    title: "Put Your Head on My Shoulder",
    platform: "Tencent",
    genre: "Romance, Modern",
    year: 2019,
    popularity: 90,
    language: "Mandarin",
    seasons: 1,
    episodes: 24,
    runtime: "45min"
  },
  {
    id: 4,
    title: "Love O2O",
    platform: "Youku",
    genre: "Romance, Modern",
    year: 2016,
    popularity: 89,
    language: "Mandarin",
    seasons: 1,
    episodes: 30,
    runtime: "45min"
  },
  {
    id: 5,
    title: "Nirvana in Fire",
    platform: "Dragon TV",
    genre: "Historical, Drama",
    year: 2015,
    popularity: 94,
    language: "Mandarin",
    seasons: 1,
    episodes: 54,
    runtime: "45min"
  },
  {
    id: 6,
    title: "Go Ahead",
    platform: "Hunan TV",
    genre: "Drama, Modern",
    year: 2020,
    popularity: 92,
    language: "Mandarin",
    seasons: 1,
    episodes: 46,
    runtime: "45min"
  },
  {
    id: 7,
    title: "Skate Into Love",
    platform: "Youku",
    genre: "Romance, Modern",
    year: 2020,
    popularity: 88,
    language: "Mandarin",
    seasons: 1,
    episodes: 40,
    runtime: "45min"
  },
  {
    id: 8,
    title: "Word of Honor",
    platform: "Youku",
    genre: "Fantasy, Historical",
    year: 2021,
    popularity: 93,
    language: "Mandarin",
    seasons: 1,
    episodes: 36,
    runtime: "45min"
  },
  {
    id: 9,
    title: "Ashes of Love",
    platform: "Jiangsu TV",
    genre: "Fantasy, Romance",
    year: 2018,
    popularity: 96,
    language: "Mandarin",
    seasons: 1,
    episodes: 63,
    runtime: "45min"
  },
  {
    id: 10,
    title: "Meteor Garden",
    platform: "Hunan TV",
    genre: "Romance, Modern",
    year: 2018,
    popularity: 91,
    language: "Mandarin",
    seasons: 1,
    episodes: 50,
    runtime: "45min"
  }
];