window.chineseWatchlist= [
  {
    id: 1,
    title: "The Untamed",
    platform: "Tencent Video / Netflix",
    genre: "Wuxia / BL",
    year: 2019,
    seasons: 1,
    episodes: 50,
    runtime: "48h",
    popularity: 98,
    imdbRating: 9.0,
    hindiDubbed: true,
    description: "Two soulmates uncover a dark secret from the past, forging a bond that defies all odds."
  },
  {
    id: 2,
    title: "Love O2O",
    platform: "Youku / Netflix",
    genre: "Romantic Comedy / Gaming",
    year: 2016,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 95,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Two college students fall in love in a virtual world and find their romance spilling into real life."
  },
  {
    id: 3,
    title: "Eternal Love",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Epic",
    year: 2017,
    seasons: 1,
    episodes: 58,
    runtime: "56h",
    popularity: 94,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A goddess and a celestial prince transcend three lifetimes of love, war, and sacrifice."
  },
  {
    id: 4,
    title: "Go Ahead",
    platform: "Hunan TV / Netflix",
    genre: "Family Drama / Slice of Life",
    year: 2020,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 92,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "Three unrelated teenagers form an unconventional family, navigating life's challenges with unconditional love."
  },
  {
    id: 5,
    title: "Falling Into Your Smile",
    platform: "Youku / Netflix",
    genre: "Romantic Comedy / E-sports",
    year: 2021,
    seasons: 1,
    episodes: 31,
    runtime: "28h",
    popularity: 93,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A female gamer joins a male-dominated e-sports team, fighting stereotypes and falling for her captain."
  },
  {
    id: 6,
    title: "Put Your Head on My Shoulder",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Campus",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 91,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A physics major and an accounting student become accidental roommates and find love in their daily lives."
  },
  {
    id: 7,
    title: "A Love So Beautiful",
    platform: "Tencent Video / Netflix",
    genre: "Youth Romance / Coming-of-Age",
    year: 2017,
    seasons: 1,
    episodes: 23,
    runtime: "21h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A bubbly high school girl's long-term crush on her cold neighbor blossoms into a heartwarming love story."
  },
  {
    id: 8,
    title: "My Little Happiness",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Workplace",
    year: 2021,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A lawyer and a surgeon who were childhood friends reunite as professional rivals and fall in love."
  },
  {
    id: 9,
    title: "You Are My Glory",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Gaming",
    year: 2021,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 97,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A top actress reconnects with her high school crush, a rocket scientist, in an online game."
  },
  {
    id: 10,
    title: "The Long Ballad",
    platform: "Tencent Video / Viki",
    genre: "Historical Romance / Revenge",
    year: 2021,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 96,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A princess survives a royal massacre and seeks revenge, forging an unlikely alliance with her enemy."
  },
  {
    id: 11,
    title: "Meteor Garden",
    platform: "Hunan TV / Netflix",
    genre: "Romantic Comedy / School",
    year: 2018,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A poor student enrolls in a prestigious school and clashes with the popular F4 boys, especially their leader."
  },
  {
    id: 12,
    title: "Find Yourself",
    platform: "Hunan TV / Netflix",
    genre: "Romantic Comedy / Office",
    year: 2020,
    seasons: 1,
    episodes: 41,
    runtime: "39h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A successful career woman in her 30s falls for a younger intern, challenging societal expectations."
  },
  {
    id: 13,
    title: "The Bad Kids",
    platform: "iQIYI / Netflix",
    genre: "Crime Thriller / Suspense",
    year: 2020,
    seasons: 1,
    episodes: 12,
    runtime: "10h",
    popularity: 95,
    imdbRating: 9.1,
    hindiDubbed: true,
    description: "Three children accidentally film a murder, plunging them into a dangerous game of cat and mouse."
  },
  {
    id: 14,
    title: "Nirvana in Fire",
    platform: "iQIYI / Netflix",
    genre: "Historical Drama / Political",
    year: 2015,
    seasons: 1,
    episodes: 54,
    runtime: "52h",
    popularity: 98,
    imdbRating: 9.3,
    hindiDubbed: true,
    description: "A brilliant strategist with a hidden past returns to the capital to seek justice for a past conspiracy."
  },
  {
    id: 15,
    title: "Joy of Life",
    platform: "Tencent Video / Viki",
    genre: "Historical Comedy / Time Travel",
    year: 2019,
    seasons: 1,
    episodes: 46,
    runtime: "44h",
    popularity: 96,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A modern man reincarnated into ancient times uses his 21st-century knowledge to survive court politics."
  },
  {
    id: 16,
    title: "The Longest Promise",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Cultivation",
    year: 2023,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 94,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A princess and a general are bound by a tragic past, but their destinies intertwine again in a world of magic."
  },
  {
    id: 17,
    title: "The Starry Love",
    platform: "Youku / Viki",
    genre: "Fantasy Romance / Mythical",
    year: 2023,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 91,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Two goddesses with different destinies accidentally swap identities, leading to a magical romance and epic adventure."
  },
  {
    id: 18,
    title: "Till the End of the Moon",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Reincarnation",
    year: 2023,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 97,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "A mortal woman must go back in time to stop a demon god from rising, but she falls for him instead."
  },
  {
    id: 19,
    title: "Who Rules the World",
    platform: "Tencent Video / Netflix",
    genre: "Wuxia / Political Romance",
    year: 2022,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 93,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Two rival martial arts masters are secretly crown princes, and their paths cross in a quest to save the world."
  },
  {
    id: 20,
    title: "Sword and Brocade",
    platform: "Tencent Video / Viki",
    genre: "Historical Romance / Politics",
    year: 2021,
    seasons: 1,
    episodes: 45,
    runtime: "42h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A concubine's son and a noblewoman enter a strategic marriage, but their hearts fall in love for real."
  },
  {
    id: 21,
    title: "The Legend of Haolan",
    platform: "iQIYI / Netflix",
    genre: "Historical Drama / Court Intrigue",
    year: 2019,
    seasons: 1,
    episodes: 62,
    runtime: "60h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A woman rises from a humble background to become an influential queen during the Qin Dynasty."
  },
  {
    id: 22,
    title: "Word of Honor",
    platform: "Youku / Netflix",
    genre: "Wuxia / BL",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 96,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "Two retired assassins find a new purpose in life when they get entangled in a conspiracy to take over the martial arts world."
  },
  {
    id: 23,
    title: "The Legend of the White Snake",
    platform: "iQIYI / Viki",
    genre: "Fantasy Romance / Mythology",
    year: 2019,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A snake spirit and a mortal man fall in love, but their relationship is forbidden by the gods."
  },
  {
    id: 24,
    title: "Love Scenery",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Gaming",
    year: 2021,
    seasons: 1,
    episodes: 31,
    runtime: "28h",
    popularity: 91,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A popular singer and a gaming student fall for each other through an online game, unaware of each other's true identities."
  },
  {
    id: 25,
    title: "The King's Avatar",
    platform: "Tencent Video / Netflix",
    genre: "E-sports / Action",
    year: 2019,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 95,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "A professional gamer, forced to retire, makes a comeback with a new team to reclaim his title."
  },
  {
    id: 26,
    title: "My Sunshine",
    platform: "Youku / Viki",
    genre: "Romantic Drama / Reunion",
    year: 2015,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A photographer and a lawyer reconnect after seven years apart, rekindling a love that never faded."
  },
  {
    id: 27,
    title: "The Rise of Phoenixes",
    platform: "Hunan TV / Netflix",
    genre: "Historical Drama / Political",
    year: 2018,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 92,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A princess disguises herself as a man to become a respected scholar, but her true identity is threatened by a crown prince."
  },
  {
    id: 28,
    title: "Love and Redemption",
    platform: "Youku / Viki",
    genre: "Fantasy Romance / Cultivation",
    year: 2020,
    seasons: 1,
    episodes: 59,
    runtime: "60h",
    popularity: 95,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "A warrior with a dark past and a girl with no senses must save the world, falling in love despite their tragic fate."
  },
  {
    id: 29,
    title: "Goodbye My Princess",
    platform: "Youku / Netflix",
    genre: "Historical Romance / Tragedy",
    year: 2019,
    seasons: 1,
    episodes: 52,
    runtime: "50h",
    popularity: 93,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A western princess is forced into a political marriage with a ruthless crown prince, but their shared past haunts them."
  },
  {
    id: 30,
    title: "Ashes of Love",
    platform: "Jiangsu TV / Netflix",
    genre: "Fantasy Romance / Epic",
    year: 2018,
    seasons: 1,
    episodes: 63,
    runtime: "60h",
    popularity: 97,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A flower fairy and a fire deity fall in love, but their tragic past and a powerful curse threaten to keep them apart."
  },
  {
    id: 31,
    title: "Boss and Me",
    platform: "Sohu TV / Viki",
    genre: "Romantic Comedy / CEO Romance",
    year: 2014,
    seasons: 1,
    episodes: 33,
    runtime: "30h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A naïve girl gets involved with a wealthy CEO — heartwarming gestures and corporate chaos turn into love."
  },
  {
    id: 32,
    title: "My Amazing Boyfriend",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Superhuman Drama",
    year: 2016,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A mutant with supernatural powers wakes from a 100-year sleep — and finds an unlikely romance with a modern actress."
  },
  {
    id: 33,
    title: "Begin Again",
    platform: "Youku / Viki",
    genre: "Romantic Comedy / CEO Marriage",
    year: 2020,
    seasons: 1,
    episodes: 35,
    runtime: "33h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A domineering CEO enters a contract marriage with a sweet doctor — and discovers love’s unpredictability."
  },
  {
    id: 34,
    title: "A River Runs Through It",
    platform: "Youku / MX Player",
    genre: "Youth / School Romance",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "After a transfer student joins a close-knit class, friendship and romance ripple through homework, heartbreak, and coming of age."
  },
  {
    id: 35,
    title: "Well-Intended Love",
    platform: "Sohu TV / Netflix",
    genre: "Romantic Comedy / Contract Marriage",
    year: 2019,
    seasons: 2,
    episodes: 32,
    runtime: "30h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "An actress with leukemia marries a CEO for a medical match — but love takes over the plan."
  },
  {
    id: 36,
    title: "Love Me If You Dare",
    platform: "Sohu TV / Viki",
    genre: "Crime Thriller / Psychological Romance",
    year: 2015,
    seasons: 1,
    episodes: 24,
    runtime: "24h",
    popularity: 85,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A criminal profiler and his assistant unravel twisted cases — while their bond dives into danger and trust."
  },
  {
    id: 37,
    title: "The Brightest Star in the Sky",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Drama / Music Industry",
    year: 2019,
    seasons: 1,
    episodes: 44,
    runtime: "42h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "An aspiring singer and a cold top idol fall into discord — but music slowly brings them in tune."
  },
  {
    id: 38,
    title: "You Are My Hero",
    platform: "Youku / MX Player",
    genre: "Romantic Action / Medical + Police Drama",
    year: 2021,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A kind doctor falls for a brave special ops officer — their love grows through trauma, rescue missions, and duty."
  },
  {
    id: 39,
    title: "Please Feel at Ease Mr. Ling",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Workplace Drama",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A quirky accident lands a mysterious CEO in a girl’s life — and their coexistence spins into playful romance."
  },
  {
    id: 40,
    title: "Forever and Ever",
    platform: "iQIYI / Viki",
    genre: "Romantic Drama / Soulmate Story",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A gentle voice actress meets her destined partner — together they revive love across lifetimes and gentle moments."
  },
  {
    id: 41,
    title: "The Day of Becoming You",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Body-Swap Fantasy",
    year: 2021,
    seasons: 1,
    episodes: 26,
    runtime: "24h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A celebrity and a reporter wake up swapped — chaos, career disasters, and unexpected affection bloom hilariously."
  },
  {
    id: 42,
    title: "Love Under the Full Moon",
    platform: "Youku / Viki",
    genre: "Fantasy Romance / Time Slip",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A girl loses her memory under a supermoon — and meets a tech genius who may be the key to her past and future."
  },
  {
    id: 43,
    title: "Le Coup de Foudre",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Reunion Drama",
    year: 2019,
    seasons: 1,
    episodes: 35,
    runtime: "32h",
    popularity: 86,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "High school deskmates part ways, then reunite years later — but life, careers, and lost moments haunt their love story."
  },
  {
    id: 44,
    title: "Unforgettable Love",
    platform: "Mango TV / Viki",
    genre: "Romantic Comedy / CEO + Kid",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A CEO hires a doctor to care for his adopted son — but fatherhood and feelings grow in unexpected ways."
  },
  {
    id: 45,
    title: "The Imperial Coroner",
    platform: "Tencent Video / Viki",
    genre: "Historical Mystery / Forensic Romance",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 83,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A female coroner solves crimes for the royal court — partnering with a prince in love and logic."
  },
  {
    id: 46,
    title: "The Love Equations",
    platform: "Tencent Video / Viki",
    genre: "Youth Romance / Campus Drama",
    year: 2020,
    seasons: 1,
    episodes: 27,
    runtime: "25h",
    popularity: 81,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A bubbly girl falls for a mysterious forensic student — romance rises through chemistry, heartbreak, and college curiosity."
  },
  {
    id: 47,
    title: "Lucky’s First Love",
    platform: "iQIYI / Netflix",
    genre: "Romantic Comedy / Office + Startup",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A designer joins a startup and clashes with the arrogant founder — their arguments turn into spark-filled attraction."
  },
  {
    id: 48,
    title: "Professional Single",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Art School Life",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A sculptor who plans to stay single meets a bold girl determined to win his heart — awkward charm leads the way."
  },
  {
    id: 49,
    title: "Go Princess Go",
    platform: "LeTV / MX Player",
    genre: "Fantasy Comedy / Time Travel + Gender Swap",
    year: 2015,
    seasons: 1,
    episodes: 35,
    runtime: "30h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A modern man wakes up in the body of a crown princess — political chaos and gender confusion ignite hilarious romance."
  },
  {
    id: 50,
    title: "Mysterious Love",
    platform: "Youku / Viki",
    genre: "Romantic Suspense / Undercover Drama",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "15h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A bodyguard and a theater actress fall for each other — secrets, shadows, and danger follow their fragile love."
  },
  {
    id: 51,
    title: "Love Designer",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Drama / Fashion Industry",
    year: 2020,
    seasons: 1,
    episodes: 45,
    runtime: "43h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A stubborn designer and a perfectionist CEO clash over a business deal — sparks and stitching turn into passion."
  },
  {
    id: 52,
    title: "Love is Sweet",
    platform: "iQIYI / Viki",
    genre: "Romantic Comedy / Workplace + Childhood Crush",
    year: 2020,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A financial analyst reunites with her childhood friend — now her harsh boss — and their cold war turns sweet."
  },
  {
    id: 53,
    title: "My Dear Guardian",
    platform: "Youku / MX Player",
    genre: "Romantic Action / Military + Hospital",
    year: 2021,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 86,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A special ops soldier and a brave doctor navigate danger, healing, and a slow-burn love under fire."
  },
  {
    id: 54,
    title: "The Wolf",
    platform: "Tencent Video / MX Player",
    genre: "Historical Fantasy / Royal Romance",
    year: 2020,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Raised by wolves, a boy becomes a powerful general — but love and betrayal threaten his ties to the crown."
  },
  {
    id: 55,
    title: "Love and Redemption",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Cultivation Saga",
    year: 2020,
    seasons: 1,
    episodes: 59,
    runtime: "60h",
    popularity: 91,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A blind girl and a warrior with a dark past must save the six realms — but their love defies prophecy."
  },
  {
    id: 56,
    title: "Dr. Cutie",
    platform: "Youku / Viki",
    genre: "Historical Romantic Comedy / Medical Mystery",
    year: 2020,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A cross-dressed girl becomes a royal doctor to investigate her family’s murder — but her general boss falls for her."
  },
  {
    id: 57,
    title: "Ten Miles of Peach Blossoms",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Deity Melodrama",
    year: 2017,
    seasons: 1,
    episodes: 58,
    runtime: "56h",
    popularity: 94,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A celestial princess and a crown prince live through lifetimes of heartbreak — only to find each other again."
  },
  {
    id: 58,
    title: "The Sword and the Brocade",
    platform: "Tencent Video / Viki",
    genre: "Historical Romance / Noble Marriage",
    year: 2021,
    seasons: 1,
    episodes: 45,
    runtime: "42h",
    popularity: 85,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A general marries a noblewoman for duty — but her wit, strength, and kindness change his world."
  },
  {
    id: 59,
    title: "The Blue Whisper",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Spirit Master Saga",
    year: 2022,
    seasons: 2,
    episodes: 42,
    runtime: "40h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A spirit master tasked with taming a merman slowly falls for her captive — and defies dark orders from above."
  },
  {
    id: 60,
    title: "Ancient Love Poetry",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Deity Tragedy",
    year: 2021,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 88,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Two ancient gods endure lifetimes of love, betrayal, and sacrifice — poetry and fate intertwine their hearts."
  },
  {
    id: 61,
    title: "Untouchable Lovers",
    platform: "Hunan TV / Netflix",
    genre: "Historical Romance / Double Identity",
    year: 2018,
    seasons: 1,
    episodes: 52,
    runtime: "50h",
    popularity: 81,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A rebellious woman takes her twin sister’s place in the palace — and falls in love with her enemy prince."
  },
  {
    id: 62,
    title: "I Hear You",
    platform: "Youku / Viki",
    genre: "Romantic Comedy / Audio Drama Twist",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 83,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "An aspiring voice actress joins a reality show — and finds herself paired with a violinist whose feelings grow louder each day."
  },
  {
    id: 63,
    title: "The Legend of Shen Li",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Deity Exile",
    year: 2024,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 90,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A battle goddess escapes heaven and meets a cursed mortal — their love risks divine rebellion."
  },
  {
    id: 64,
    title: "Miss the Dragon",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Dragon Prince Myth",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 85,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A kind maid saves a dragon — now he chases her through lifetimes to repay love with devotion."
  },
  {
    id: 65,
    title: "First Romance",
    platform: "Youku / MX Player",
    genre: "Youth Romance / College Reconnect",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 81,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A shy freshman reunites with her high school crush at university — rediscovering love and awkward memories."
  },
  {
    id: 66,
    title: "Trial Marriage",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / CEO Marriage Contract",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A genius CEO offers marriage for business — but falling in love wasn’t part of the plan."
  },
  {
    id: 67,
    title: "My Girl",
    platform: "Youku / MX Player",
    genre: "Romantic Drama / Trauma + Makeup Artist",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 78,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A scarred makeup artist hides her past — until she meets a man who helps her heal through love."
  },
  {
    id: 68,
    title: "The Love You Give Me",
    platform: "Youku / Viki",
    genre: "Romantic Drama / Reunion + Parenthood",
    year: 2023,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Years after heartbreak, a woman reunites with her ex — now a father, both seeking closure and connection."
  },
  {
    id: 69,
    title: "Butterflied Lover",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Butterfly Reincarnation",
    year: 2022,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 80,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A butterfly spirit reincarnates into a girl — love blossoms between realms as fate flutters near."
  },
  {
    id: 70,
    title: "Accidentally in Love",
    platform: "Sohu TV / Netflix",
    genre: "Romantic Comedy / Secret Identity",
    year: 2018,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 87,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A runaway heiress hides her identity to attend college — only to fall for a celebrity in disguise."
  },
  {
    id: 71,
    title: "The Romance of Hua Rong",
    platform: "iQIYI / MX Player",
    genre: "Romantic Comedy / Pirate + Noble",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A feisty noblewoman gets kidnapped by a pirate — but love sails in faster than escape."
  },
  {
    id: 72,
    title: "Cute Programmer",
    platform: "Youku / Viki",
    genre: "Romantic Comedy / Tech Drama",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A girl disguises herself as a boy to work with her coding crush — awkward debug love follows."
  },
  {
    id: 73,
    title: "Flavour It's Yours",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Wine + Taste Sensory",
    year: 2019,
    seasons: 1,
    episodes: 25,
    runtime: "23h",
    popularity: 78,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "A wine critic loses his taste and meets a girl with super senses — love brews across palates."
  },
  {
    id: 74,
    title: "The Oath of Love",
    platform: "Tencent Video / Viki",
    genre: "Romantic Drama / Medical + Music",
    year: 2022,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 85,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A rising cellist and a steady doctor meet during crisis — healing begins where love plays softly."
  },
  {
    id: 75,
    title: "Intense Love",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Celebrity + Doctor",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 82,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A superstar actress and a cold-hearted surgeon try to avoid an arranged match — but fate writes a rom-com script."
  },
  {
    id: 76,
    title: "Hello Mr. Gu",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Contract Marriage",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 81,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "An arrogant tech tycoon marries a soft-spoken girl to fulfill a family deal — but love hijacks the plan."
  },
  {
    id: 77,
    title: "Why Women Love",
    platform: "Youku / MX Player",
    genre: "Romantic Drama / Workplace + Reverse Age Gap",
    year: 2022,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A confident manager meets a younger intern — maturity and mischief collide in their stormy romance."
  },
  {
    id: 78,
    title: "My Lethal Man",
    platform: "iQIYI / Viki",
    genre: "Suspense Romance / Identity Swap",
    year: 2023,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A woman takes her dead twin’s identity — and gets entangled with a deadly yet seductive protector."
  },
  {
    id: 79,
    title: "Put Your Head on My Shoulder 2",
    platform: "Tencent Video / Viki",
    genre: "Romantic Sequel / College Couple",
    year: 2022,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "Si Tu Mo and Gu Weiyi return — now balancing adult life and a deeper love that’s no longer shy."
  },
  {
    id: 80,
    title: "Nothing But Thirty",
    platform: "Dragon TV / Netflix",
    genre: "Slice of Life / Female Friendship",
    year: 2020,
    seasons: 1,
    episodes: 43,
    runtime: "41h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Three women face marriage, work, and self-worth in their 30s — honest, empowering, and emotionally resonant."
  },
  {
    id: 81,
    title: "Dear Missy",
    platform: "Tencent Video / MX Player",
    genre: "Drama / Female Rivalry + Friendship",
    year: 2020,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 80,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Two best friends reunite after betrayal — now successful women navigating work, wounds, and buried bonds."
  },
  {
    id: 82,
    title: "Reset",
    platform: "Tencent Video / Viki",
    genre: "Thriller / Time Loop Mystery",
    year: 2022,
    seasons: 1,
    episodes: 15,
    runtime: "14h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A girl keeps dying in a bus explosion — trapped in a time loop, she must solve the case to escape."
  },
  {
    id: 83,
    title: "Psychologist",
    platform: "Youku / MX Player",
    genre: "Drama / Healing + Mental Health",
    year: 2021,
    seasons: 1,
    episodes: 40,
    runtime: "39h",
    popularity: 82,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A therapist helps clients find peace while struggling with her own scars — gentle, sensitive, and poignant."
  },
  {
    id: 84,
    title: "Glory of Special Forces",
    platform: "iQIYI / Netflix",
    genre: "Military Drama / Action + Growth",
    year: 2022,
    seasons: 1,
    episodes: 45,
    runtime: "43h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A rebellious soldier joins China’s elite unit — discovering brotherhood, discipline, and true strength."
  },
  {
    id: 85,
    title: "Draw the Line",
    platform: "Hunan TV / Viki",
    genre: "Legal Drama / Ethics vs Power",
    year: 2022,
    seasons: 1,
    episodes: 40,
    runtime: "39h",
    popularity: 80,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Three generations of judges face justice in a corrupt world — personal trials echo through the courtroom."
  },
  {
    id: 86,
    title: "Being a Hero",
    platform: "Youku / Netflix",
    genre: "Crime Thriller / Police + Drug War",
    year: 2022,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Two childhood friends turned cops chase a drug lord — loyalty, grief, and justice collide at every turn."
  },
  {
    id: 87,
    title: "My Supernatural Power Boyfriend",
    platform: "Tencent Video / MX Player",
    genre: "Fantasy Romance / Psychic Twist",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 81,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A telekinetic man and an unlucky girl become roommates — romance and chaos fly through walls and hearts."
  },
  {
    id: 88,
    title: "Love Like the Galaxy",
    platform: "Tencent Video / Netflix",
    genre: "Historical Romance / Family Drama",
    year: 2022,
    seasons: 2,
    episodes: 56,
    runtime: "55h",
    popularity: 93,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "A misunderstood girl finds love with a sharp general — their bond shakes empires and heals wounds."
  },
  {
    id: 89,
    title: "The Rebel Princess",
    platform: "iQIYI / Viki",
    genre: "Historical Romance / Empire Power Play",
    year: 2021,
    seasons: 1,
    episodes: 68,
    runtime: "66h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A noblewoman marries a warrior to survive political storms — their love rises alongside war and ambition."
  },
  {
    id: 90,
    title: "Joy of Life",
    platform: "Tencent Video / Netflix",
    genre: "Historical Comedy Thriller / Rebirth",
    year: 2019,
    seasons: 1,
    episodes: 46,
    runtime: "44h",
    popularity: 92,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A modern man reborn in ancient times uncovers conspiracies — witty, brilliant, and dangerously charming."
  },
  {
    id: 91,
    title: "Under the Skin",
    platform: "Youku / Viki",
    genre: "Crime Mystery / Art + Detective Drama",
    year: 2022,
    seasons: 1,
    episodes: 20,
    runtime: "18h",
    popularity: 85,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A portrait artist aids in solving police cases — each canvas holds secrets, pain, and justice."
  },
  {
    id: 92,
    title: "A Familiar Stranger",
    platform: "Youku / Netflix",
    genre: "Historical Romance / Body Swap Mystery",
    year: 2022,
    seasons: 1,
    episodes: 18,
    runtime: "16h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A noblewoman and a courtesan swap bodies — deception and desire twist their lives in unpredictable ways."
  },
  {
    id: 93,
    title: "Till the End of the World",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Disaster / Survival Drama",
    year: 2018,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 82,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Two strangers get trapped in Antarctica after a crash — frozen hearts thaw with survival and silent love."
  },
  {
    id: 94,
    title: "Fearless Whispers",
    platform: "iQIYI / Viki",
    genre: "Spy Thriller / Historical Drama",
    year: 2020,
    seasons: 1,
    episodes: 51,
    runtime: "50h",
    popularity: 87,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A rookie cop joins counterintelligence — betrayal, patriotism, and hidden truths trace every step."
  },
  {
    id: 95,
    title: "Song of the Moon",
    platform: "iQIYI / MX Player",
    genre: "Fantasy Romance / Deity Quest",
    year: 2022,
    seasons: 1,
    episodes: 34,
    runtime: "32h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A girl sells her destiny for riches — and meets an immortal fated to restore her soul and rewrite her fate."
  },
  {
    id: 96,
    title: "The Legend of White Snake",
    platform: "iQIYI / Netflix",
    genre: "Fantasy Romance / Folklore Reimagined",
    year: 2019,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 88,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A snake spirit falls for a scholar — love rises as divine rules and human prejudice strike back."
  },
  {
    id: 97,
    title: "Goodbye My Princess",
    platform: "iQIYI / Netflix",
    genre: "Historical Romance / Tragedy + Memory Loss",
    year: 2019,
    seasons: 1,
    episodes: 52,
    runtime: "50h",
    popularity: 91,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A cursed love story between a Western princess and an ambitious crown prince — betrayal and amnesia rewrite fate."
  },
  {
    id: 98,
    title: "Lost You Forever",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Deity Mythology + Politics",
    year: 2023,
    seasons: 1,
    episodes: 39,
    runtime: "38h",
    popularity: 92,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A forgotten princess wanders the realms — meeting three men tied to love, revenge, and fate in a divine power struggle."
  },
  {
    id: 99,
    title: "Legend of Awakening",
    platform: "iQIYI / MX Player",
    genre: "Fantasy Action / Martial Arts + Growth",
    year: 2020,
    seasons: 1,
    episodes: 48,
    runtime: "46h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A boy awakens mysterious powers and joins a sect of fighters — uncovering ancient secrets and his true identity."
  },
  {
    id: 100,
    title: "She and Her Perfect Husband",
    platform: "Youku / Netflix",
    genre: "Modern Romance / Legal Career + Contract Marriage",
    year: 2022,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 87,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A fierce lawyer enters a fake marriage to boost her career — but her cold 'husband' isn’t immune to love’s heat."
  },
  {
    id: 101,
    title: "The Rise of Phoenixes",
    platform: "Tencent Video / Netflix",
    genre: "Historical Drama / Revenge & Romance",
    year: 2018,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 89,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Amid palace intrigue and betrayal, a forgotten prince and a cunning scholar rise as phoenixes of war and love."
  },
  {
    id: 102,
    title: "Eternal Love of Dream",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Reincarnation",
    year: 2020,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 90,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A fate-bound deity and a mortal designer traverse dreams and lifetimes to rekindle an immortal romance."
  },
  {
    id: 103,
    title: "The King's Avatar",
    platform: "Tencent Video / Netflix",
    genre: "E-Sports Drama / Friendship & Ambition",
    year: 2019,
    seasons: 1,
    episodes: 12,
    runtime: "10h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A top esports champion returns to pro gaming with a new team — for glory, redemption, and real friendship."
  },
  {
    id: 104,
    title: "Novoland: The Castle in the Sky",
    platform: "Youku / Viki",
    genre: "Fantasy Epic / Adventure",
    year: 2016,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "In a land of dragons and sky castles, a young lord and a rebel girl unite to protect their world from darkness."
  },
  {
    id: 105,
    title: "Novoland: Eagle Flag",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy / Political Alliance",
    year: 2019,
    seasons: 1,
    episodes: 58,
    runtime: "56h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Three nations collide as a general rises from ashes — forging alliances, battling betrayal, and shaping destiny."
  },
  {
    id: 106,
    title: "Royal Nirvana",
    platform: "Tencent Video / Netflix",
    genre: "Historical / Palace Politics",
    year: 2018,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 83,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A crown prince returns from exile to reclaim the throne — navigating power struggles, loyalty, and forbidden love."
  },
  {
    id: 107,
    title: "Legend of Yunxi",
    platform: "Tencent Video / Viki",
    genre: "Historical Romance / Medical Drama",
    year: 2018,
    seasons: 1,
    episodes: 50,
    runtime: "48h",
    popularity: 82,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A herbalist healer and a cold prince cross paths — their bond blooms through medicine, loyalty, and royal intrigue."
  },
  {
    id: 108,
    title: "Our Glamorous Time",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Drama / Fashion Industry",
    year: 2018,
    seasons: 1,
    episodes: 48,
    runtime: "46h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A struggling designer meets a top executive — together they navigate runway chaos, brand wars, and unexpected love."
  },
  {
    id: 109,
    title: "Winter Begonia",
    platform: "iQIYI / Viki",
    genre: "Historical Drama / Peking Opera",
    year: 2020,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 85,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "In 1930s Shanghai, a Peking opera master and a merchant’s daughter find art, passion, and rivalry beneath the stage lights."
  },
  {
    id: 110,
    title: "My Huckleberry Friends",
    platform: "Tencent Video / Netflix",
    genre: "Youth Romance / Coming-of-Age",
    year: 2017,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "Best friends in high school navigate heartbreak, dreams, and the bittersweet taste of growing up together."
  },
  {
    id: 111,
    title: "With You",
    platform: "Tencent Video / Netflix",
    genre: "Youth / School Drama",
    year: 2016,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 86,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Four classmates form an unlikely bond — exploring friendship, rivalry, and the joy of teenage discovery."
  },
  {
    id: 112,
    title: "Medical Examiner Dr Qin",
    platform: "Hunan TV / Netflix",
    genre: "Crime / Forensic Thriller",
    year: 2016,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 85,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A brilliant forensic pathologist solves baffling cases with medical genius — uncovering truths and dark secrets."
  },
  {
    id: 113,
    title: "Dance of the Phoenix",
    platform: "iQIYI / Netflix",
    genre: "Fantasy / Reincarnation",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A star dancer is betrayed by a prince — reincarnated a century later, she reclaims vengeance and hidden love."
  },
  {
    id: 114,
    title: "Back to 1989",
    platform: "Youku / Netflix",
    genre: "Romance / Time Travel",
    year: 2019,
    seasons: 1,
    episodes: 45,
    runtime: "42h",
    popularity: 83,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A modern couple travels back to their teenage selves — reliving love’s first joys and painful lessons."
  },
  {
    id: 115,
    title: "The Golden Hairpin",
    platform: "iQIYI / Netflix",
    genre: "Mystery / Historical",
    year: 2020,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A female detective and her scholar friend unravel palace conspiracies — solving murders one clue at a time."
  },
  {
    id: 116,
    title: "Tribes and Empires: Storm of Prophecy",
    platform: "iQIYI / Netflix",
    genre: "Fantasy Epic / Political Struggle",
    year: 2017,
    seasons: 1,
    episodes: 56,
    runtime: "53h",
    popularity: 87,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Three princes fight for destiny in a realm of prophecy — love, betrayal, and power clash under storm-filled skies."
  },
  {
    id: 117,
    title: "The Story of Ming Lan",
    platform: "iQIYI / Viki",
    genre: "Historical Drama / Family Epic",
    year: 2018,
    seasons: 1,
    episodes: 73,
    runtime: "70h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A resilient young woman navigates familial politics and romantic intrigue in Song dynasty China."
  },
  {
    id: 118,
    title: "Dream of Red Mansions",
    platform: "Tencent Video / Netflix",
    genre: "Historical / Literary Adaptation",
    year: 2010,
    seasons: 1,
    episodes: 50,
    runtime: "48h",
    popularity: 82,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "An epic adaptation of one of China’s four great novels — love, tragedy, and destiny unfold in grand style."
  },
  {
    id: 119,
    title: "The Legend of Hao Lan",
    platform: "Tencent Video / Viki",
    genre: "Historical / Power Play",
    year: 2019,
    seasons: 1,
    episodes: 62,
    runtime: "60h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A low-born woman uses intelligence and grace to become a powerful queen in the Qin dynasty."
  },
  {
    id: 120,
    title: "Legend of Fei",
    platform: "Tencent Video / Netflix",
    genre: "Wuxia / Female Warrior Saga",
    year: 2020,
    seasons: 1,
    episodes: 51,
    runtime: "48h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A free-spirited martial artist and a cautious nobleman journey across the martial world, forging destiny."
  },
  {
    id: 121,
    title: "My Heroic Husband",
    platform: "WeTV / Viki",
    genre: "Historical Comedy / Transmigration",
    year: 2021,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 87,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A modern banker transmigrates into ancient times as a new husband, using business savvy to outsmart rivals."
  },
  {
    id: 122,
    title: "Sword Snow Stride",
    platform: "Youku / MX Player",
    genre: "Xianxia / Fantasy Epic",
    year: 2019,
    seasons: 1,
    episodes: 54,
    runtime: "52h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A former god traverses realms to uncover his past, battling demons and forging alliances."
  },
  {
    id: 123,
    title: "Painting Heart Expert",
    platform: "iQIYI / Viki",
    genre: "Fantasy Comedy / Art + Medicine",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A talented painter and an awkward doctor swap roles to heal hearts and solve mysteries through art."
  },
  {
    id: 124,
    title: "Wu Xin: The Monster Killer",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Mystery / Supernatural Thriller",
    year: 2015,
    seasons: 1,
    episodes: 25,
    runtime: "23h",
    popularity: 88,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A cursed detective battles evil spirits across dynasties, unraveling the secrets of immortality."
  },
  {
    id: 125,
    title: "Dear Translator",
    platform: "Youku / Netflix",
    genre: "Romantic Drama / Workplace",
    year: 2016,
    seasons: 1,
    episodes: 31,
    runtime: "28h",
    popularity: 81,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A talented translator and a hotel heir navigate cultural clashes and unexpected romance in Shanghai."
  },
  {
    id: 126,
    title: "The Legend of the Nine-Tailed Fox",
    platform: "iQIYI / Netflix",
    genre: "Fantasy Romance / Mythology",
    year: 2022,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A fox spirit falls for a mortal scholar, defying heavenly laws in a world of magic and mortal peril."
  },
  {
    id: 127,
    title: "The Legends",
    platform: "iQIYI / Viki",
    genre: "Fantasy Action / Twin Sisters",
    year: 2019,
    seasons: 1,
    episodes: 48,
    runtime: "45h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Twin sisters hunt down supernatural conspiracies, uncovering family secrets and bonding through adversity."
  },
  {
    id: 128,
    title: "Novoland: Arsenal Military Academy",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy / Political Alliance",
    year: 2020,
    seasons: 1,
    episodes: 50,
    runtime: "48h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Young cadets train at a military academy, forging friendships, rivalries, and uncovering ancient prophecies."
  },
  {
    id: 129,
    title: "My Unicorn Girl",
    platform: "iQIYI / MX Player",
    genre: "Romantic Comedy / Mythical",
    year: 2018,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A mythical creature transforms into a girl to pursue love and learn the depth of human emotion."
  },
  {
    id: 130,
    title: "Tientsin Mystic",
    platform: "Tencent Video / Netflix",
    genre: "Crime Mystery / Fantasy",
    year: 2017,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A detective and his friends uncover supernatural crimes in 1920s Tianjin, where nothing is as it seems."
  },
  {
    id: 131,
    title: "One and Only",
    platform: "Tencent Video / Viki",
    genre: "Historical Wuxia Romance",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 85,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A renowned martial artist and a gifted apothecary fight corruption and forge an unbreakable bond."
  },
  {
    id: 132,
    title: "The Legend of Xiao Chuo",
    platform: "Tencent Video / Netflix",
    genre: "Historical / Royal Saga",
    year: 2019,
    seasons: 1,
    episodes: 54,
    runtime: "52h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Ambitious Empress Xiao Chuo navigates court intrigue, love, and power in Liao dynasty China."
  },
  {
    id: 133,
    title: "Swordsman",
    platform: "Tencent Video / Netflix",
    genre: "Wuxia / Martial Arts Epic",
    year: 2013,
    seasons: 1,
    episodes: 54,
    runtime: "52h",
    popularity: 84,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A young martial artist vows revenge and discovers friendship, honor, and destiny on his epic journey."
  },
  {
    id: 134,
    title: "The Promise of Chang’an",
    platform: "iQIYI / Viki",
    genre: "Historical Romance / Political Intrigue",
    year: 2020,
    seasons: 1,
    episodes: 56,
    runtime: "54h",
    popularity: 86,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A noblewoman is caught between love and duty — as she becomes the empress of a rival kingdom."
  },
  {
    id: 135,
    title: "Ashes of Love 2",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Celestial Saga",
    year: 2024,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 92,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A new generation of deities battles fate and forbidden desire — with echoes of an immortal legacy."
  },
  {
    id: 136,
    title: "The Sleepless Princess",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Sleep Disorder Drama",
    year: 2020,
    seasons: 1,
    episodes: 35,
    runtime: "33h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A princess who can’t sleep meets a general with battle scars — love blossoms between nightmares and moonlight."
  },
  {
    id: 137,
    title: "Legend of Anle",
    platform: "iQIYI / Netflix",
    genre: "Historical Romance / Kingdom Rebellion",
    year: 2023,
    seasons: 1,
    episodes: 39,
    runtime: "37h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A woman whose family was destroyed by betrayal returns in disguise — to reclaim justice and confront love."
  },
  {
    id: 138,
    title: "Love Between Blossoms",
    platform: "Youku / MX Player",
    genre: "Historical Romance / Hidden Identity",
    year: 2022,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 81,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A florist with secrets wins the favor of a nobleman — unraveling truths between petals and palace whispers."
  },
  {
    id: 139,
    title: "Mirror: Twin Cities",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Twin Kingdoms",
    year: 2022,
    seasons: 1,
    episodes: 43,
    runtime: "41h",
    popularity: 86,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Two realms clash beneath the sea — where memory, identity, and love ripple between twin souls."
  },
  {
    id: 140,
    title: "The Ingenious One",
    platform: "iQIYI / Viki",
    genre: "Mystery Thriller / Inventor Drama",
    year: 2023,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A wandering genius crafts devices to solve ancient crimes — and uncovers his own forgotten legacy."
  },
  {
    id: 141,
    title: "Brilliant Class 8",
    platform: "Youku / MX Player",
    genre: "Youth Drama / Teacher + Underdogs",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "An unconventional teacher transforms a rowdy class — healing hearts and awakening dreams."
  },
  {
    id: 142,
    title: "Fox Spirit Matchmaker",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Rebirth Love Match",
    year: 2023,
    seasons: 1,
    episodes: 38,
    runtime: "36h",
    popularity: 88,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "Fox spirits match reincarnated lovers across lifetimes — destiny and desire dance through reincarnation."
  },
  {
    id: 143,
    title: "Heroes",
    platform: "Youku / Viki",
    genre: "Wuxia / Martial Arts Brotherhood",
    year: 2022,
    seasons: 1,
    episodes: 38,
    runtime: "36h",
    popularity: 85,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Five wandering warriors form a bond to protect the realm — fighting injustice, betrayal, and fate."
  },
  {
    id: 144,
    title: "Daughter of the Emperor",
    platform: "iQIYI / Netflix",
    genre: "Historical Romance / Father-Daughter Saga",
    year: 2023,
    seasons: 1,
    episodes: 42,
    runtime: "40h",
    popularity: 83,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A fierce princess raised by the emperor must choose between her father’s rule and her own heart."
  },
  {
    id: 145,
    title: "Battle Through the Heavens",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Action / Cultivation Epic",
    year: 2018,
    seasons: 1,
    episodes: 45,
    runtime: "42h",
    popularity: 90,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A fallen prodigy embarks on a journey to rise again — mastering elements and earning redemption."
  },
  {
    id: 146,
    title: "The Imperial Age",
    platform: "Youku / Viki",
    genre: "Historical / Founding of the Ming Dynasty",
    year: 2020,
    seasons: 1,
    episodes: 60,
    runtime: "58h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "From rebellion to throne, a legendary emperor fights enemies and fate to establish the Ming dynasty."
  },
  {
    id: 147,
    title: "Love in Between",
    platform: "Youku / Netflix",
    genre: "Historical Romance / Hidden Past",
    year: 2020,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 83,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A mysterious swordsman and a noble lady cross paths — secrets unfold as love and truth collide."
  },
  {
    id: 148,
    title: "Serenade of Peaceful Joy",
    platform: "iQIYI / Viki",
    genre: "Palace Drama / Father-Daughter Bonds",
    year: 2020,
    seasons: 1,
    episodes: 69,
    runtime: "67h",
    popularity: 87,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A Song dynasty emperor struggles to balance power and love — with his daughter caught in the storm."
  },
  {
    id: 149,
    title: "Truth or Dare",
    platform: "Youku / MX Player",
    genre: "Historical Comedy / Marriage Swap",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "Two brides are swapped accidentally — and chaos turns into love as mistaken identity rewrites fate."
  },
  {
    id: 150,
    title: "The World of Fantasy",
    platform: "Tencent Video / Netflix",
    genre: "Xianxia / Cosmic Romance",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A lost boy discovers his destiny in a universe of gods and monsters — love and war stretch across realms."
  }
];

