const chineseWatchlist = [
  {
    id: 1,
    title: "Love Between Fairy and Devil",
    platform: "iQIYI / Netflix",
    genre: "Fantasy Romance / Immortal Curse",
    year: 2022,
    seasons: 1,
    episodes: 36,
    runtime: "32h",
    popularity: 92,
    imdbRating: 8.8,
    hindiDubbed: true,
    description: "A low-ranked fairy accidentally awakens the demon lord sealed in her body — and their fates twist across love, power, and redemption."
  },
  {
    id: 2,
    title: "Hidden Love",
    platform: "Youku / Netflix",
    genre: "Romantic Drama / Coming-of-Age",
    year: 2023,
    seasons: 1,
    episodes: 25,
    runtime: "20h",
    popularity: 89,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A shy teenager falls for her older brother’s friend — hiding her love through childhood, until fate makes it real."
  },
  {
    id: 3,
    title: "Who Rules the World",
    platform: "Tencent Video / Netflix",
    genre: "Historical Wuxia Romance",
    year: 2022,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 90,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "Two powerful martial artists from rival kingdoms clash, flirt, and fight their way through politics, war, and destiny."
  },
  {
    id: 4,
    title: "The Long Ballad",
    platform: "Tencent Video / Viki",
    genre: "Historical Epic / Revenge Drama",
    year: 2021,
    seasons: 1,
    episodes: 49,
    runtime: "45h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "After a coup kills her family, a Tang dynasty princess sets out to restore justice — and meets an unlikely ally from the enemy clan."
  },
  {
    id: 5,
    title: "Till the End of the Moon",
    platform: "Youku / Netflix",
    genre: "Xianxia Romance / Demon Reincarnation",
    year: 2023,
    seasons: 1,
    episodes: 40,
    runtime: "40h",
    popularity: 93,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A mortal girl is sent back in time to prevent a demon lord’s rise — but love threatens to rewrite destiny itself."
  },
  {
    id: 6,
    title: "You Are My Glory",
    platform: "Tencent Video / Viki",
    genre: "Romantic Slice of Life / Space & Gaming",
    year: 2021,
    seasons: 1,
    episodes: 32,
    runtime: "30h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A celebrity gamer reconnects with her high school crush — now a space engineer struggling with his own orbit."
  },
  {
    id: 7,
    title: "Put Your Head on My Shoulder",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Campus Life",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 87,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A cheerful business major and a genius physics student become unexpected roommates — and first love slowly sparks."
  },
  {
    id: 8,
    title: "Love O2O",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Gaming World",
    year: 2016,
    seasons: 1,
    episodes: 30,
    runtime: "30h",
    popularity: 91,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A top student and a game developer fall in love both online and offline — as their virtual marriage turns into reality."
  },
  {
    id: 9,
    title: "Ashes of Love",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Immortal War",
    year: 2018,
    seasons: 1,
    episodes: 63,
    runtime: "60h",
    popularity: 94,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A love-starved flower deity accidentally falls for the Fire God — but their passion sparks celestial war."
  },
  {
    id: 10,
    title: "The Romance of Tiger and Rose",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Writer isekai",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "20h",
    popularity: 86,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A screenwriter wakes up inside her own story — now living as a side character destined to die. Can she rewrite her ending?"
  },
  {
    id: 11,
    title: "Go Ahead",
    platform: "Hunan TV / Netflix",
    genre: "Healing Drama / Found Family",
    year: 2020,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 89,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "Three non-related siblings grow up under one roof — bonding through laughter, loss, and complicated adulthood."
  },
  {
    id: 12,
    title: "The Untamed",
    platform: "Tencent Video / Netflix / MX Player",
    genre: "Xianxia / Mystery / BL Vibes",
    year: 2019,
    seasons: 1,
    episodes: 50,
    runtime: "50h",
    popularity: 95,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "Two cultivators unravel conspiracies across clans — and forge an unforgettable bond through life, death, and sacrifice."
  },
  {
    id: 13,
    title: "Falling Into Your Smile",
    platform: "Youku / Netflix",
    genre: "Romantic Comedy / E-sports Drama",
    year: 2021,
    seasons: 1,
    episodes: 31,
    runtime: "30h",
    popularity: 90,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A girl enters the male-dominated world of pro gaming — and steals the team captain’s heart while smashing opponents."
  },
  {
    id: 14,
    title: "The Princess Weiyoung",
    platform: "Tencent Video / Viki",
    genre: "Historical Revenge Romance",
    year: 2016,
    seasons: 1,
    episodes: 54,
    runtime: "54h",
    popularity: 83,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "After her kingdom is destroyed, a princess assumes another identity — but her plan for revenge gets entangled in love and loyalty."
  },
  {
    id: 15,
    title: "A Love So Beautiful",
    platform: "Tencent Video / Netflix",
    genre: "Youth Romance / School Drama",
    year: 2017,
    seasons: 1,
    episodes: 24,
    runtime: "20h",
    popularity: 89,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A bubbly girl chases her cold classmate from high school to college — navigating friendship, awkwardness, and growing up."
  },
  {
    id: 16,
    title: "General and I",
    platform: "Hunan TV / Viki",
    genre: "Historical Romance / War Strategy",
    year: 2017,
    seasons: 1,
    episodes: 62,
    runtime: "65h",
    popularity: 82,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A brilliant strategist and a famous general from opposing kingdoms fall in love — while fighting on rival sides of a war."
  },
  {
    id: 17,
    title: "Eternal Love",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Immortal Love Story",
    year: 2017,
    seasons: 1,
    episodes: 58,
    runtime: "60h",
    popularity: 94,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Across three lives and countless memories, a fox goddess and a heavenly prince battle fate and heartbreak to find each other again."
  },
  {
    id: 18,
    title: "The King's Woman",
    platform: "Youku / MX Player",
    genre: "Historical Romance / Royal Politics",
    year: 2017,
    seasons: 1,
    episodes: 48,
    runtime: "45h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A fierce warrior woman becomes the queen of Qin — but her heart still belongs to another, as palace intrigue and betrayal unfold."
  },
  {
    id: 19,
    title: "Once Upon a Time",
    platform: "Netflix",
    genre: "Fantasy Romance / Immortal Film Adaptation",
    year: 2017,
    seasons: 1,
    episodes: 1,
    runtime: "1h 50m",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A cinematic retelling of Eternal Love — two deities fall in love across lifetimes, torn between memory and destiny."
  },
  {
    id: 20,
    title: "Princess Agents",
    platform: "Hunan TV / Viki",
    genre: "Historical Action / Spy Drama",
    year: 2017,
    seasons: 1,
    episodes: 58,
    runtime: "55h",
    popularity: 91,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A slave girl trained as a spy rises through deadly court politics — fighting for freedom and love in a kingdom without mercy."
  },
  {
    id: 21,
    title: "Meteor Garden",
    platform: "Netflix",
    genre: "Romantic Comedy / High School Drama",
    year: 2018,
    seasons: 1,
    episodes: 49,
    runtime: "45h",
    popularity: 90,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A brave girl enters a prestigious university and clashes with the notorious F4 boys — chaos, crushes, and rebellion follow."
  },
  {
    id: 22,
    title: "The Flame’s Daughter",
    platform: "Youku / MX Player",
    genre: "Fantasy Romance / Martial Arts Saga",
    year: 2018,
    seasons: 1,
    episodes: 52,
    runtime: "48h",
    popularity: 83,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Born with a fiery fate, a spirited martial artist must uncover her past, challenge destiny, and choose between love and loyalty."
  },
  {
    id: 23,
    title: "Legend of Fuyao",
    platform: "Tencent Video / Netflix",
    genre: "Historical Fantasy / Destiny Quest",
    year: 2018,
    seasons: 1,
    episodes: 66,
    runtime: "62h",
    popularity: 89,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A woman born from a divine lotus embarks on a journey across kingdoms — facing betrayal, ancient secrets, and divine love."
  },
  {
    id: 24,
    title: "My Little Happiness",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Legal Workplace",
    year: 2021,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A secretly returned law intern reunites with her childhood crush — now her flirty supervising doctor."
  },
  {
    id: 25,
    title: "Go Go Squid!",
    platform: "iQIYI / Netflix",
    genre: "Romantic Comedy / E-Sports + AI",
    year: 2019,
    seasons: 1,
    episodes: 41,
    runtime: "40h",
    popularity: 87,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "An adorable singer chases an aloof cybersecurity genius — and helps him rediscover love, team spirit, and ambition."
  },
  {
    id: 26,
    title: "My Sassy Princess",
    platform: "Youku / MX Player",
    genre: "Historical Romance / Gender Reversal",
    year: 2022,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 78,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A mischievous princess and a cold general trade roles in power — rewriting tradition with sass, strength, and heart."
  },
  {
    id: 27,
    title: "Sweet Dreams",
    platform: "Zhejiang TV / Viki",
    genre: "Fantasy Romance / Tech + Sleep Science",
    year: 2018,
    seasons: 1,
    episodes: 48,
    runtime: "45h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A shy girl enters a sleep experiment and finds herself inside her crush’s dreams — love blossoms inside dreamscapes."
  },
  {
    id: 28,
    title: "Perfect and Casual",
    platform: "Tencent Video / MX Player",
    genre: "Romantic Comedy / Contract Marriage",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A professor and a fashion girl get married for convenience — but their clashing personalities reveal unexpected chemistry."
  },
  {
    id: 29,
    title: "Skate Into Love",
    platform: "iQIYI / Netflix",
    genre: "Youth Romance / Sports + Ice Hockey",
    year: 2020,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 82,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A speed skater and a hockey player reignite old rivalry — and skate into romance through sweat, struggle, and winter sparks."
  },
  {
    id: 30,
    title: "Be With You",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Co-Workers to Lovers",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 81,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A confident architect and a shy editor end up working together — navigating awkwardness, teamwork, and blooming love."
  },
  {
    id: 31,
    title: "Boss and Me",
    platform: "Sohu TV / Viki",
    genre: "Romantic Comedy / CEO Romance",
    year: 2014,
    seasons: 1,
    episodes: 33,
    runtime: "30h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A naïve girl gets involved with a wealthy CEO — heartwarming gestures and corporate chaos turn into love."
  },
  {
    id: 32,
    title: "My Amazing Boyfriend",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Superhuman Drama",
    year: 2016,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A mutant with supernatural powers wakes from a 100-year sleep — and finds an unlikely romance with a modern actress."
  },
{
    id: 32,
    title: "My Amazing Boyfriend",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Superhuman Drama",
    year: 2016,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A mutant with supernatural powers wakes from a 100-year sleep — and finds an unlikely romance with a modern actress."
  },
  {
    id: 33,
    title: "Begin Again",
    platform: "Youku / Viki",
    genre: "Romantic Comedy / CEO Marriage",
    year: 2020,
    seasons: 1,
    episodes: 35,
    runtime: "33h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A domineering CEO enters a contract marriage with a sweet doctor — and discovers love’s unpredictability."
  },
  {
    id: 34,
    title: "A River Runs Through It",
    platform: "Youku / MX Player",
    genre: "Youth / School Romance",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "After a transfer student joins a close-knit class, friendship and romance ripple through homework, heartbreak, and coming of age."
  },
  {
    id: 35,
    title: "Well-Intended Love",
    platform: "Sohu TV / Netflix",
    genre: "Romantic Comedy / Contract Marriage",
    year: 2019,
    seasons: 2,
    episodes: 32,
    runtime: "30h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "An actress with leukemia marries a CEO for a medical match — but love takes over the plan."
  },
  {
    id: 36,
    title: "Love Me If You Dare",
    platform: "Sohu TV / Viki",
    genre: "Crime Thriller / Psychological Romance",
    year: 2015,
    seasons: 1,
    episodes: 24,
    runtime: "24h",
    popularity: 85,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A criminal profiler and his assistant unravel twisted cases — while their bond dives into danger and trust."
  },
  {
    id: 37,
    title: "The Brightest Star in the Sky",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Drama / Music Industry",
    year: 2019,
    seasons: 1,
    episodes: 44,
    runtime: "42h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "An aspiring singer and a cold top idol fall into discord — but music slowly brings them in tune."
  },
  {
    id: 38,
    title: "You Are My Hero",
    platform: "Youku / MX Player",
    genre: "Romantic Action / Medical + Police Drama",
    year: 2021,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A kind doctor falls for a brave special ops officer — their love grows through trauma, rescue missions, and duty."
  },
  {
    id: 39,
    title: "Please Feel at Ease Mr. Ling",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Workplace Drama",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A quirky accident lands a mysterious CEO in a girl’s life — and their coexistence spins into playful romance."
  },
  {
    id: 40,
    title: "Forever and Ever",
    platform: "iQIYI / Viki",
    genre: "Romantic Drama / Soulmate Story",
    year: 2021,
    seasons: 1,
    episodes: 30,
    runtime: "28h",
    popularity: 86,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A gentle voice actress meets her destined partner — together they revive love across lifetimes and gentle moments."
  },
  {
    id: 41,
    title: "The Day of Becoming You",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Comedy / Body-Swap Fantasy",
    year: 2021,
    seasons: 1,
    episodes: 26,
    runtime: "24h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A celebrity and a reporter wake up swapped — chaos, career disasters, and unexpected affection bloom hilariously."
  },
  {
    id: 42,
    title: "Love Under the Full Moon",
    platform: "Youku / Viki",
    genre: "Fantasy Romance / Time Slip",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A girl loses her memory under a supermoon — and meets a tech genius who may be the key to her past and future."
  },
  {
    id: 43,
    title: "Le Coup de Foudre",
    platform: "Tencent Video / Viki",
    genre: "Romantic Comedy / Reunion Drama",
    year: 2019,
    seasons: 1,
    episodes: 35,
    runtime: "32h",
    popularity: 86,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "High school deskmates part ways, then reunite years later — but life, careers, and lost moments haunt their love story."
  },
  {
    id: 44,
    title: "Unforgettable Love",
    platform: "Mango TV / Viki",
    genre: "Romantic Comedy / CEO + Kid",
    year: 2021,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A CEO hires a doctor to care for his adopted son — but fatherhood and feelings grow in unexpected ways."
  },
  {
    id: 45,
    title: "The Imperial Coroner",
    platform: "Tencent Video / Viki",
    genre: "Historical Mystery / Forensic Romance",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 83,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A female coroner solves crimes for the royal court — partnering with a prince in love and logic."
  },
  {
    id: 46,
    title: "The Love Equations",
    platform: "Tencent Video / Viki",
    genre: "Youth Romance / Campus Drama",
    year: 2020,
    seasons: 1,
    episodes: 27,
    runtime: "25h",
    popularity: 81,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A bubbly girl falls for a mysterious forensic student — romance rises through chemistry, heartbreak, and college curiosity."
  },
  {
    id: 47,
    title: "Lucky’s First Love",
    platform: "iQIYI / Netflix",
    genre: "Romantic Comedy / Office + Startup",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 80,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A designer joins a startup and clashes with the arrogant founder — their arguments turn into spark-filled attraction."
  },
  {
    id: 48,
    title: "Professional Single",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Art School Life",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A sculptor who plans to stay single meets a bold girl determined to win his heart — awkward charm leads the way."
  },
{
    id: 48,
    title: "Professional Single",
    platform: "Youku / MX Player",
    genre: "Romantic Comedy / Art School Life",
    year: 2020,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 79,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A sculptor who plans to stay single meets a bold girl determined to win his heart — awkward charm leads the way."
  },
  {
    id: 49,
    title: "Go Princess Go",
    platform: "LeTV / MX Player",
    genre: "Fantasy Comedy / Time Travel + Gender Swap",
    year: 2015,
    seasons: 1,
    episodes: 35,
    runtime: "30h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A modern man wakes up in the body of a crown princess — political chaos and gender confusion ignite hilarious romance."
  },
  {
    id: 50,
    title: "Mysterious Love",
    platform: "Youku / Viki",
    genre: "Romantic Suspense / Undercover Drama",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "15h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A bodyguard and a theater actress fall for each other — secrets, shadows, and danger follow their fragile love."
  },
  {
    id: 51,
    title: "Love Designer",
    platform: "Tencent Video / Netflix",
    genre: "Romantic Drama / Fashion Industry",
    year: 2020,
    seasons: 1,
    episodes: 45,
    runtime: "43h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A stubborn designer and a perfectionist CEO clash over a business deal — sparks and stitching turn into passion."
  },
  {
    id: 52,
    title: "Love is Sweet",
    platform: "iQIYI / Viki",
    genre: "Romantic Comedy / Workplace + Childhood Crush",
    year: 2020,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 88,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A financial analyst reunites with her childhood friend — now her harsh boss — and their cold war turns sweet."
  },
  {
    id: 53,
    title: "My Dear Guardian",
    platform: "Youku / MX Player",
    genre: "Romantic Action / Military + Hospital",
    year: 2021,
    seasons: 1,
    episodes: 40,
    runtime: "38h",
    popularity: 86,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A special ops soldier and a brave doctor navigate danger, healing, and a slow-burn love under fire."
  },
  {
    id: 54,
    title: "The Wolf",
    platform: "Tencent Video / MX Player",
    genre: "Historical Fantasy / Royal Romance",
    year: 2020,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Raised by wolves, a boy becomes a powerful general — but love and betrayal threaten his ties to the crown."
  },
  {
    id: 55,
    title: "Love and Redemption",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Cultivation Saga",
    year: 2020,
    seasons: 1,
    episodes: 59,
    runtime: "60h",
    popularity: 91,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A blind girl and a warrior with a dark past must save the six realms — but their love defies prophecy."
  },
  {
    id: 56,
    title: "Dr. Cutie",
    platform: "Youku / Viki",
    genre: "Historical Romantic Comedy / Medical Mystery",
    year: 2020,
    seasons: 1,
    episodes: 28,
    runtime: "26h",
    popularity: 80,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A cross-dressed girl becomes a royal doctor to investigate her family’s murder — but her general boss falls for her."
  },
  {
    id: 57,
    title: "Ten Miles of Peach Blossoms",
    platform: "Tencent Video / Netflix",
    genre: "Fantasy Romance / Deity Melodrama",
    year: 2017,
    seasons: 1,
    episodes: 58,
    runtime: "56h",
    popularity: 94,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A celestial princess and a crown prince live through lifetimes of heartbreak — only to find each other again."
  },
  {
    id: 58,
    title: "The Sword and the Brocade",
    platform: "Tencent Video / Viki",
    genre: "Historical Romance / Noble Marriage",
    year: 2021,
    seasons: 1,
    episodes: 45,
    runtime: "42h",
    popularity: 85,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A general marries a noblewoman for duty — but her wit, strength, and kindness change his world."
  },
  {
    id: 59,
    title: "The Blue Whisper",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Spirit Master Saga",
    year: 2022,
    seasons: 2,
    episodes: 42,
    runtime: "40h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A spirit master tasked with taming a merman slowly falls for her captive — and defies dark orders from above."
  },
  {
    id: 60,
    title: "Ancient Love Poetry",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Deity Tragedy",
    year: 2021,
    seasons: 1,
    episodes: 49,
    runtime: "48h",
    popularity: 88,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Two ancient gods endure lifetimes of love, betrayal, and sacrifice — poetry and fate intertwine their hearts."
  },
  {
    id: 61,
    title: "Untouchable Lovers",
    platform: "Hunan TV / Netflix",
    genre: "Historical Romance / Double Identity",
    year: 2018,
    seasons: 1,
    episodes: 52,
    runtime: "50h",
    popularity: 81,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A rebellious woman takes her twin sister’s place in the palace — and falls in love with her enemy prince."
  },
  {
    id: 62,
    title: "I Hear You",
    platform: "Youku / Viki",
    genre: "Romantic Comedy / Audio Drama Twist",
    year: 2019,
    seasons: 1,
    episodes: 24,
    runtime: "22h",
    popularity: 83,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "An aspiring voice actress joins a reality show — and finds herself paired with a violinist whose feelings grow louder each day."
  },
  {
    id: 63,
    title: "The Legend of Shen Li",
    platform: "Youku / Netflix",
    genre: "Fantasy Romance / Deity Exile",
    year: 2024,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 90,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A battle goddess escapes heaven and meets a cursed mortal — their love risks divine rebellion."
  },
  {
    id: 64,
    title: "Miss the Dragon",
    platform: "Tencent Video / Viki",
    genre: "Fantasy Romance / Dragon Prince Myth",
    year: 2021,
    seasons: 1,
    episodes: 36,
    runtime: "34h",
    popularity: 85,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A kind maid saves a dragon — now he chases her through lifetimes to repay love with devotion."
  },
