const recommendedChineseSeries = [
  {
    id: 1,
    title: "The Untamed",
    platform: "Tencent / Netflix",
    genre: "Xianxia / Fantasy / Bromance",
    year: 2019,
    popularity: 95,
    seasons: 1,
    episodes: 50,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 2,
    title: "Love Between Fairy and Devil",
    platform: "iQIYI / Netflix",
    genre: "Xianxia / Fantasy / Romance",
    year: 2022,
    popularity: 92,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 3,
    title: "Hidden Love",
    platform: "Youku / Netflix",
    genre: "Romance / Youth / Slice of Life",
    year: 2023,
    popularity: 94,
    seasons: 1,
    episodes: 25,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 4,
    title: "Love O2O",
    platform: "Tencent / Netflix",
    genre: "Romance / Gaming / Campus",
    year: 2016,
    popularity: 91,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 5,
    title: "The Long Ballad",
    platform: "Tencent / Viki",
    genre: "Historical / War / Romance",
    year: 2021,
    popularity: 90,
    seasons: 1,
    episodes: 49,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 6,
    title: "Put Your Head on My Shoulder",
    platform: "Tencent / Netflix",
    genre: "Romance / Youth / Comedy",
    year: 2019,
    popularity: 89,
    seasons: 1,
    episodes: 24,
    runtime: "40 min",
    language: "Hindi Dubbed"
  },
  {
    id: 7,
    title: "Who Rules the World",
    platform: "Tencent / Netflix",
    genre: "Wuxia / Romance / Action",
    year: 2022,
    popularity: 88,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 8,
    title: "My Journey to You",
    platform: "iQIYI / Netflix",
    genre: "Historical / Spy / Romance",
    year: 2023,
    popularity: 86,
    seasons: 1,
    episodes: 24,
    runtime: "50 min",
    language: "Hindi Dubbed"
  },
  {
    id: 9,
    title: "Go Ahead",
    platform: "Netflix",
    genre: "Family / Slice of Life / Youth",
    year: 2020,
    popularity: 91,
    seasons: 1,
    episodes: 46,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 10,
    title: "The First Frost",
    platform: "Youku / Netflix",
    genre: "Romance / Youth / Slice of Life",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 11,
    title: "Love Like the Galaxy",
    platform: "Tencent / Viki",
    genre: "Historical / Romance / Political",
    year: 2022,
    popularity: 90,
    seasons: 2,
    episodes: 56,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 12,
    title: "Till the End of the Moon",
    platform: "Youku / Netflix",
    genre: "Xianxia / Fantasy / Romance",
    year: 2023,
    popularity: 93,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 13,
    title: "Love Me, Love My Voice",
    platform: "iQIYI",
    genre: "Romance / Healing / Modern",
    year: 2023,
    popularity: 84,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 14,
    title: "A Familiar Stranger",
    platform: "Youku",
    genre: "Historical / Identity Swap / Romance",
    year: 2022,
    popularity: 83,
    seasons: 1,
    episodes: 18,
    runtime: "25 min",
    language: "Hindi Dubbed"
  },
  {
    id: 15,
    title: "Lost You Forever",
    platform: "Tencent",
    genre: "Xianxia / Romance / Fantasy",
    year: 2023,
    popularity: 91,
    seasons: 1,
    episodes: 39,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 16,
    title: "Meet Yourself",
    platform: "Hunan TV / Youku",
    genre: "Slice of Life / Healing / Rural",
    year: 2023,
    popularity: 89,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 17,
    title: "The Romance of Tiger and Rose",
    platform: "Tencent / MX Player",
    genre: "Historical / Comedy / Romance",
    year: 2020,
    popularity: 87,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 18,
    title: "Miss the Dragon",
    platform: "Tencent / Viki",
    genre: "Fantasy / Romance / Mythical",
    year: 2021,
    popularity: 85,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 19,
    title: "Rattan",
    platform: "Youku / Viki",
    genre: "Fantasy / Sci-Fi / Mystery",
    year: 2021,
    popularity: 84,
    seasons: 1,
    episodes: 30,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 20,
    title: "A Love So Beautiful",
    platform: "Tencent / Netflix",
    genre: "Youth / Romance / School",
    year: 2017,
    popularity: 90,
    seasons: 1,
    episodes: 23,
    runtime: "24 min",
    language: "Hindi Dubbed"
  },
  {
    id: 21,
    title: "The Blood of Youth",
    platform: "Youku",
    genre: "Wuxia / Fantasy / Adventure",
    year: 2022,
    popularity: 88,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 22,
    title: "You Are My Glory",
    platform: "Tencent / Viki",
    genre: "Modern / Romance / Gaming",
    year: 2021,
    popularity: 91,
    seasons: 1,
    episodes: 32,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 23,
    title: "The Legends",
    platform: "iQIYI / MX Player",
    genre: "Xianxia / Fantasy / Romance",
    year: 2019,
    popularity: 88,
    seasons: 1,
    episodes: 56,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 24,
    title: "Sweet Teeth",
    platform: "iQIYI / MX Player",
    genre: "Romance / Dentist / Modern",
    year: 2021,
    popularity: 87,
    seasons: 1,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 25,
    title: "Forever and Ever",
    platform: "iQIYI / Netflix",
    genre: "Modern / Romance / Marriage",
    year: 2021,
    popularity: 86,
    seasons: 1,
    episodes: 30,
    runtime: "40 min",
    language: "Hindi Dubbed"
  },
  {
    id: 26,
    title: "Light Chaser Rescue",
    platform: "Tencent / iQIYI",
    genre: "Rescue / Romance / Action",
    year: 2022,
    popularity: 84,
    seasons: 1,
    episodes: 40,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 27,
    title: "Reset",
    platform: "Tencent / Netflix",
    genre: "Sci-Fi / Thriller / Time Loop",
    year: 2022,
    popularity: 90,
    seasons: 1,
    episodes: 15,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 28,
    title: "Under the Power",
    platform: "iQIYI / MX Player",
    genre: "Historical / Detective / Romance",
    year: 2019,
    popularity: 89,
    seasons: 1,
    episodes: 55,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 29,
    title: "Love is Sweet",
    platform: "iQIYI / MX Player",
    genre: "Modern / Office / Romance",
    year: 2020,
    popularity: 88,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Hindi Dubbed"
  },
  {
    id: 30,
    title: "The Legend of Zang Hai",
    platform: "Tencent",
    genre: "Historical / Epic / Military",
    year: 2025,
    popularity: 91,
    seasons: 1,
    episodes: 42,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 31,
    title: "Love in Pavilion",
    platform: "Youku / Netflix",
    genre: "Historical / Romance / Palace",
    year: 2025,
    popularity: 88,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "English Dubbed"
  },
  {
    id: 32,
    title: "Legend of the Female General",
    platform: "Tencent",
    genre: "Historical / Military / Romance",
    year: 2025,
    popularity: 90,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 33,
    title: "The Immortal Ascension",
    platform: "iQIYI",
    genre: "Xianxia / Cultivation / Fantasy",
    year: 2025,
    popularity: 87,
    seasons: 1,
    episodes: 34,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 34,
    title: "Fox Spirit Matchmaker: Sword and Beloved",
    platform: "Tencent",
    genre: "Fantasy / Romance / Mythical",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 36,
    runtime: "45 min",
    language: "Mandarin (Subs)"
  },
  {
    id: 35,
    title: "The Prisoner of Beauty",
    platform: "Youku",
    genre: "Historical / Romance / Drama",
    year: 2025,
    popularity:90,
  },
  
];
console.log("🧧 Chinese recommendations loaded:", recommendedChineseSeries.length, "entries");