const myWatchlist = [
  {
    id: 1,
    title: "Farzi",
    platform: "Prime Video",
    genre: "Crime Thriller",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 89,
    hindiDubbed: true,
    description: "An artist drawn into the world of counterfeiting finds himself pitted against a ruthless gangster and a determined cop in this darkly stylish thriller."
  },
  {
    id: 2,
    title: "Wednesday",
    platform: "Netflix",
    genre: "Supernatural Mystery",
    year: 2022,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 92,
    hindiDubbed: true,
    description: "Wednesday Addams joins Nevermore Academy and uncovers a monstrous mystery involving her parents’ past, all while mastering her psychic powers."
  },
  {
    id: 3,
    title: "Stranger Things",
    platform: "Netflix",
    genre: "Sci-Fi Horror",
    year: 2016,
    seasons: 4,
    episodes: 34,
    runtime: "30h",
    popularity: 98,
    hindiDubbed: true,
    description: "When a young boy vanishes, a small town uncovers a secret government experiment and a strange girl with supernatural powers from an alternate dimension."
  },
  {
    id: 4,
    title: "Rudra: The Edge of Darkness",
    platform: "Disney+ Hotstar",
    genre: "Psychological Thriller",
    year: 2022,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 84,
    hindiDubbed: true,
    description: "A brooding cop with a haunted past dives deep into Mumbai’s most disturbing cases while confronting his own demons."
  },
  {
    id: 5,
    title: "Scam 1992: The Harshad Mehta Story",
    platform: "Sony LIV",
    genre: "Biographical Drama",
    year: 2020,
    seasons: 1,
    episodes: 10,
    runtime: "9h",
    popularity: 95,
    hindiDubbed: true,
    description: "The gripping rise and fall of Harshad Mehta, the stockbroker who shook India’s financial system with one of the biggest market scams."
  },
  {
    id: 6,
    title: "The Family Man",
    platform: "Prime Video",
    genre: "Spy Thriller",
    year: 2019,
    seasons: 2,
    episodes: 19,
    runtime: "15h",
    popularity: 94,
    hindiDubbed: true,
    description: "A middle-class man secretly working as an intelligence officer balances domestic life and national duty while combating terrorists and sleeper cells."
  },
  {
    id: 7,
    title: "The Boys",
    platform: "Prime Video",
    genre: "Superhero Satire",
    year: 2019,
    seasons: 3,
    episodes: 24,
    runtime: "22h",
    popularity: 94,
    hindiDubbed: true,
    description: "When heroes go corrupt, a scrappy team of vigilantes takes them down in this ultra-violent, irreverent twist on the superhero genre."
  },
  {
    id: 8,
    title: "All of Us Are Dead",
    platform: "Netflix",
    genre: "Zombie Thriller",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 88,
    hindiDubbed: true,
    description: "A high school becomes the epicenter of a zombie virus outbreak as trapped students fight to survive and escape."
  },
  {
    id: 9,
    title: "The Last of Us",
    platform: "HBO Max",
    genre: "Post-Apocalyptic Drama",
    year: 2023,
    seasons: 1,
    episodes: 9,
    runtime: "9h",
    popularity: 97,
    hindiDubbed: true,
    description: "A hardened smuggler escorts a girl immune to a deadly fungus across a ravaged America, forging a bond that changes everything."
  },
  {
    id: 10,
    title: "Lockwood & Co.",
    platform: "Netflix",
    genre: "Supernatural Mystery",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 82,
    hindiDubbed: true,
    description: "In a haunted London, teen ghost-hunters run an agency to battle spirits without adult supervision — or funding."
  },
  {
    id: 11,
    title: "Dahmer – Monster: The Jeffrey Dahmer Story",
    platform: "Netflix",
    genre: "Crime Biopic",
    year: 2022,
    seasons: 1,
    episodes: 10,
    runtime: "9h",
    popularity: 86,
    hindiDubbed: true,
    description: "A disturbing look into the mind of one of America’s most notorious serial killers, told from the perspectives of his victims."
  },
  {
    id: 12,
    title: "Ozark",
    platform: "Netflix",
    genre: "Crime Thriller",
    year: 2017,
    seasons: 4,
    episodes: 44,
    runtime: "40h",
    popularity: 95,
    hindiDubbed: true,
    description: "A financial advisor launders money for a drug cartel and moves his family to the Ozarks, where danger and moral compromise await."
  },
  {
    id: 13,
    title: "Taaza Khabar",
    platform: "Disney+ Hotstar",
    genre: "Fantasy Drama",
    year: 2023,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 81,
    hindiDubbed: true,
    description: "A sanitation worker gains the ability to foresee the future and sets out to rewrite his fate — but destiny has other plans."
  },
  {
    id: 14,
    title: "1899",
    platform: "Netflix",
    genre: "Mystery Thriller",
    year: 2022,
    seasons: 1,
    episodes: 8,
    runtime: "8h",
    popularity: 87,
    hindiDubbed: true,
    description: "Mysterious happenings aboard a migrant ship crossing the Atlantic unravel a mind-bending puzzle that blurs time and space."
  },
  {
    id: 15,
    title: "Money Heist",
    platform: "Netflix",
    genre: "Heist Thriller",
    year: 2017,
    seasons: 5,
    episodes: 41,
    runtime: "32h",
    popularity: 96,
    hindiDubbed: true,
    description: "An enigmatic Professor gathers a crew of skilled criminals to pull off the biggest bank heist Spain has ever seen."
  },
  {
    id: 16,
    title: "Cobra Kai",
    platform: "Netflix",
    genre: "Martial Arts Drama",
    year: 2018,
    seasons: 5,
    episodes: 50,
    runtime: "40h",
    popularity: 90,
    hindiDubbed: true,
    description: "Decades after their karate rivalry, Johnny Lawrence and Daniel LaRusso reignite their feud through dojos, teens, and unfinished business."
  },
  {
    id: 17,
    title: "The Watcher",
    platform: "Netflix",
    genre: "True Crime Thriller",
    year: 2022,
    seasons: 1,
    episodes: 7,
    runtime: "6h",
    popularity: 83,
    hindiDubbed: true,
    description: "A couple’s dream home turns into a nightmare when they receive ominous letters from a mysterious stalker watching every move."
  },
  {
    id: 18,
    title: "Loki",
    platform: "Disney+ Hotstar",
    genre: "Superhero Fantasy",
    year: 2021,
    seasons: 2,
    episodes: 12,
    runtime: "10h",
    popularity: 92,
    hindiDubbed: true,
    description: "The God of Mischief bounces through time and timelines while working with the Time Variance Authority to contain cosmic chaos."
  },
  {
    id: 19,
    title: "Moon Knight",
    platform: "Disney+ Hotstar",
    genre: "Superhero Mystery",
    year: 2022,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 85,
    hindiDubbed: true,
    description: "A man with dissociative identity disorder becomes the avatar for an Egyptian moon god, battling both enemies and himself."
  },
  {
    id: 20,
    title: "Alice in Borderland",
    platform: "Netflix",
    genre: "Survival Sci-Fi",
    year: 2020,
    seasons: 2,
    episodes: 16,
    runtime: "15h",
    popularity: 91,
    hindiDubbed: true,
    description: "A gamer and his friends find themselves in an abandoned Tokyo where they must play deadly games to survive and return to reality."
  },
  {
    id: 21,
    title: "Asur",
    platform: "JioCinema",
    genre: "Mythological Crime Thriller",
    year: 2020,
    seasons: 2,
    episodes: 16,
    runtime: "14h",
    popularity: 89,
    hindiDubbed: true,
    description: "A former forensic expert is pulled into a cat-and-mouse chase with a killer inspired by ancient Indian mythology and philosophy."
  },
  {
    id: 22,
    title: "College Romance",
    platform: "Sony LIV",
    genre: "Romantic Comedy",
    year: 2018,
    seasons: 3,
    episodes: 15,
    runtime: "10h",
    popularity: 84,
    hindiDubbed: true,
    description: "Three close-knit friends navigate love, awkward encounters, heartbreak, and humor through the wild world of college life."
  },
  {
    id: 23,
    title: "Mismatched",
    platform: "Netflix",
    genre: "Young Adult Romance",
    year: 2020,
    seasons: 2,
    episodes: 12,
    runtime: "8h",
    popularity: 79,
    hindiDubbed: true,
    description: "A tech whiz and a romantic misfit bond and bicker through a coding camp where sparks — and code — fly."
  },
  {
    id: 24,
    title: "Yeh Kaali Kaali Ankhein",
    platform: "Netflix",
    genre: "Romantic Thriller",
    year: 2022,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 82,
    hindiDubbed: true,
    description: "When a powerful woman’s obsession traps a small-town man into a forced relationship, he’s pushed to dangerous extremes to escape."
  },
  {
    id: 25,
    title: "Mirzapur",
    platform: "Prime Video",
    genre: "Crime Action",
    year: 2018,
    seasons: 2,
    episodes: 19,
    runtime: "16h",
    popularity: 95,
    hindiDubbed: true,
    description: "Gunfights, power struggles, and blood feuds erupt in a lawless town where ambition, revenge, and brutality rule."
  },
  {
    id: 26,
    title: "Criminal Justice",
    platform: "Disney+ Hotstar",
    genre: "Courtroom Drama",
    year: 2019,
    seasons: 3,
    episodes: 18,
    runtime: "14h",
    popularity: 87,
    hindiDubbed: true,
    description: "An intense legal thriller that explores the flaws in India’s criminal justice system through multiple gripping murder cases."
  },
  {
    id: 27,
    title: "Lucifer",
    platform: "Netflix",
    genre: "Fantasy Drama",
    year: 2016,
    seasons: 6,
    episodes: 93,
    runtime: "70h",
    popularity: 93,
    hindiDubbed: true,
    description: "The Devil abandons Hell and opens a nightclub in LA — but soon ends up assisting the police in solving crimes with divine intuition."
  },
  {
    id: 28,
    title: "Saas Bahu Aur Flamingo",
    platform: "Disney+ Hotstar",
    genre: "Crime Drama",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 80,
    hindiDubbed: true,
    description: "A matriarch runs a powerful drug empire from the front of a quirky handicrafts business with her equally badass daughters-in-law."
  },
  {
    id: 29,
    title: "Dahaad",
    platform: "Prime Video",
    genre: "Crime Mystery",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 85,
    hindiDubbed: true,
    description: "A relentless female cop in rural Rajasthan investigates a chilling pattern of disappearances linked to a methodical serial killer."
  },
  {
    id: 30,
    title: "Panchayat",
    platform: "Prime Video",
    genre: "Slice of Life Comedy",
    year: 2020,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 91,
    hindiDubbed: true,
    description: "An urban engineering graduate takes up a low-paying government job in a rural village and slowly discovers meaning, humor, and belonging."
  },
{
  id: 31,
  title: "Lucky Guy",
  platform: "Prime Video",
  genre: "K-Romance Comedy",
  year: 2021,
  seasons: 1,
  episodes: 10,
  runtime: "8h",
  popularity: 77,
  hindiDubbed: false,
  description: "A perpetually unlucky man discovers a chance to reset his fate when he crosses paths with a woman who seems to change his destiny."
},
{
  id: 32,
  title: "Business Proposal",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2022,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 90,
  hindiDubbed: true,
  description: "A food researcher goes on a blind date in place of her friend and unexpectedly ends up in a contract relationship with her company’s CEO."
},
{
  id: 33,
  title: "One Dollar Lawyer",
  platform: "Disney+ Hotstar",
  genre: "Legal Comedy",
  year: 2022,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 84,
  hindiDubbed: true,
  description: "A maverick lawyer who charges only one dollar per case uses his wit to fight injustice and face powerful opponents with flair."
},
{
  id: 34,
  title: "Gen V",
  platform: "Prime Video",
  genre: "Superhero Action",
  year: 2023,
  seasons: 1,
  episodes: 8,
  runtime: "8h",
  popularity: 87,
  hindiDubbed: true,
  description: "At a college for young superheroes run by Vought, students compete and conspire in a Hunger Games–style showdown filled with dark secrets."
},
{
  id: 35,
  title: "November Story",
  platform: "Disney+ Hotstar",
  genre: "Crime Mystery",
  year: 2021,
  seasons: 1,
  episodes: 7,
  runtime: "6h",
  popularity: 79,
  hindiDubbed: true,
  description: "A crime novelist suffering from Alzheimer’s becomes the prime suspect in a murder investigation, forcing his daughter to uncover the truth."
},
{
  id: 36,
  title: "Dhindora",
  platform: "YouTube",
  genre: "Comedy Drama",
  year: 2021,
  seasons: 1,
  episodes: 8,
  runtime: "6h",
  popularity: 83,
  hindiDubbed: true,
  description: "Bhuvan Bam’s fictional universe gets a full-blown series as his lovable characters get swept up in a lottery ticket mix-up and family drama."
},
{
  id: 37,
  title: "Breaking Bad",
  platform: "Netflix",
  genre: "Crime Drama",
  year: 2008,
  seasons: 5,
  episodes: 62,
  runtime: "50h",
  popularity: 99,
  hindiDubbed: true,
  description: "A high school chemistry teacher turns to meth production after a cancer diagnosis, spiraling into a world of danger and deception."
},
{
  id: 38,
  title: "King the Land",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2023,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 86,
  hindiDubbed: true,
  description: "A hotel heir and a cheerful concierge clash and then collide in a heartwarming enemies-to-lovers workplace romance."
},
{
  id: 39,
  title: "The King: Eternal Monarch",
  platform: "Netflix",
  genre: "Fantasy Romance",
  year: 2020,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 88,
  hindiDubbed: true,
  description: "A Korean emperor enters a parallel world and meets a strong-willed detective as they team up to close the rift between dimensions."
},
{
  id: 40,
  title: "Goblin: The Lonely and Great God",
  platform: "Viki",
  genre: "Fantasy Romance",
  year: 2016,
  seasons: 1,
  episodes: 16,
  runtime: "18h",
  popularity: 92,
  hindiDubbed: false,
  description: "An immortal goblin seeks a human bride to end his cursed immortality, crossing fate and centuries of sorrow and love."
},
{
  id: 41,
  title: "What's Wrong with Secretary Kim",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 89,
  hindiDubbed: true,
  description: "When his devoted secretary suddenly resigns, a narcissistic boss tries to win her back, uncovering a shared childhood past."
},
{
  id: 42,
  title: "Behind Your Touch",
  platform: "Netflix",
  genre: "Supernatural Mystery",
  year: 2023,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 82,
  hindiDubbed: true,
  description: "A small-town vet with psychic touch ability teams up with a detective to solve crimes — and maybe fall in love along the way."
},
{
  id: 43,
  title: "Crazy Love",
  platform: "Disney+ Hotstar",
  genre: "Romantic Thriller",
  year: 2022,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 78,
  hindiDubbed: true,
  description: "An arrogant CEO fakes amnesia when he’s threatened with murder — but his secretary may have secrets of her own."
},
{
  id: 44,
  title: "Crash Landing on You",
  platform: "Netflix",
  genre: "Romance Drama",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 94,
  hindiDubbed: true,
  description: "A South Korean heiress lands in North Korea after a paragliding mishap and falls for a stoic soldier who protects her secret."
},
{
  id: 45,
  title: "Flower of Evil",
  platform: "Netflix",
  genre: "Crime Thriller",
  year: 2020,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 91,
  hindiDubbed: true,
  description: "A loving husband hides his serial killer past from his detective wife, until a case threatens to destroy their carefully crafted life."
},
{
  id: 46,
  title: "It's Okay to Not Be Okay",
  platform: "Netflix",
  genre: "Psychological Romance",
  year: 2020,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 90,
  hindiDubbed: true,
  description: "A psychiatric caregiver and a rebellious children's author heal from their past traumas as their lives intertwine emotionally and magically."
},
{
  id: 47,
  title: "The King of Pigs",
  platform: "TVING",
  genre: "Psychological Thriller",
  year: 2022,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 81,
  hindiDubbed: false,
  description: "Two men tied by childhood bullying confront dark secrets and long-buried rage when a series of murders occurs decades later."
},
{
  id: 48,
  title: "Vincenzo",
  platform: "Netflix",
  genre: "Crime Comedy",
  year: 2021,
  seasons: 1,
  episodes: 20,
  runtime: "20h",
  popularity: 94,
  hindiDubbed: true,
  description: "A Korean-Italian mafia consigliere returns to Seoul to recover hidden gold, only to wage war against a corrupt conglomerate."
},
{
  id: 49,
  title: "Lawless Lawyer",
  platform: "Viki",
  genre: "Legal Action",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "15h",
  popularity: 86,
  hindiDubbed: true,
  description: "A former gangster-turned-lawyer uses fists and legal tricks to fight a corrupt judge and avenge his mother’s death."
},
{
  id: 50,
  title: "Strong Girl Nam-soon",
  platform: "Netflix",
  genre: "Superhero Comedy",
  year: 2023,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 88,
  hindiDubbed: true,
  description: "Blessed with superhuman strength, Nam-soon returns to Korea to find her family — but uncovers a dangerous drug ring instead."
},
{
  id: 51,
  title: "Legal High",
  platform: "Viki",
  genre: "Legal Comedy",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "13h",
  popularity: 82,
  hindiDubbed: false,
  description: "A cocky, ruthless lawyer with a perfect win record teams up with an idealistic rookie to face off in quirky and intense courtroom battles."
},
{
  id: 52,
  title: "Big Mouth",
  platform: "Disney+ Hotstar",
  genre: "Crime Mystery",
  year: 2022,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 90,
  hindiDubbed: true,
  description: "A struggling lawyer is mistaken for a genius con artist and thrown into a conspiracy involving corruption, crime, and survival behind bars."
},
{
  id: 53,
  title: "Extraordinary Attorney Woo",
  platform: "Netflix",
  genre: "Legal Drama",
  year: 2022,
  seasons: 1,
  episodes: 16,
  runtime: "20h",
  popularity: 93,
  hindiDubbed: true,
  description: "A brilliant autistic attorney tackles challenging cases and social biases with her sharp mind and heartfelt perspective."
},
{
  id: 54,
  title: "A Time Called You",
  platform: "Netflix",
  genre: "Romantic Mystery",
  year: 2023,
  seasons: 1,
  episodes: 12,
  runtime: "11h",
  popularity: 85,
  hindiDubbed: true,
  description: "After losing her boyfriend, a grieving woman finds herself back in 1998 in someone else’s body — with a familiar face by her side."
},
{
  id: 55,
  title: "She Was Pretty",
  platform: "Viki",
  genre: "Romantic Comedy",
  year: 2015,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 88,
  hindiDubbed: true,
  description: "Years after losing touch, two childhood friends reunite — but with reversed appearances and tangled hearts in a workplace setting."
},
{
  id: 56,
  title: "Kill It",
  platform: "Viki",
  genre: "Action Thriller",
  year: 2019,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 81,
  hindiDubbed: false,
  description: "A vet hiding his identity as a trained assassin crosses paths with a detective searching for her family's killer — unaware he may be her answer."
},
{
  id: 57,
  title: "The Secret Life of My Secretary",
  platform: "Viki",
  genre: "Romantic Comedy",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "13h",
  popularity: 84,
  hindiDubbed: false,
  description: "An arrogant boss with face blindness relies on his quirky secretary — and falls for her, unaware she’s hiding her identity."
},
{
  id: 58,
  title: "I Am Not a Robot",
  platform: "Viki",
  genre: "Sci-Fi Romance",
  year: 2017,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 87,
  hindiDubbed: true,
  description: "A tech genius allergic to humans falls for a woman pretending to be a robot — until emotions disrupt their artificial arrangement."
},
{
  id: 59,
  title: "Where Stars Land",
  platform: "Viki",
  genre: "Romantic Drama",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 80,
  hindiDubbed: false,
  description: "Two airport employees with mysterious pasts navigate ambition, hardship, and a growing connection amid the bustle of departures and arrivals."
},
{
  id: 60,
  title: "Descendants of the Sun",
  platform: "Netflix",
  genre: "Military Romance",
  year: 2016,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 91,
  hindiDubbed: true,
  description: "A soldier and a doctor fall in love across borders, conflict zones, and philosophies as they serve during a humanitarian mission."
},
{
  id: 61,
  title: "Playful Kiss",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2010,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 75,
  hindiDubbed: true,
  description: "A clumsy girl moves into the house of the school’s top student after a disaster strikes her home — and life never stays the same again."
},
{
  id: 62,
  title: "Emergency Couple",
  platform: "Viki",
  genre: "Medical Romance",
  year: 2014,
  seasons: 1,
  episodes: 21,
  runtime: "17h",
  popularity: 79,
  hindiDubbed: false,
  description: "A divorced couple unexpectedly reunites as interns in the same hospital’s emergency department — with sparks, chaos, and awkward tension."
},
{
  id: 63,
  title: "Familiar Wife",
  platform: "Netflix",
  genre: "Romantic Fantasy",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 82,
  hindiDubbed: true,
  description: "A fed-up husband gets a supernatural chance to redo his life and change his marriage — but is a new timeline the right one?"
},
{
  id: 64,
  title: "Dhootha",
  platform: "Prime Video",
  genre: "Paranormal Thriller",
  year: 2023,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 85,
  hindiDubbed: true,
  description: "Newspapers begin predicting gruesome deaths — and a journalist races to uncover the dark force behind these deadly headlines."
},
{
  id: 65,
  title: "Berlin",
  platform: "Netflix",
  genre: "Heist Thriller",
  year: 2023,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 88,
  hindiDubbed: true,
  description: "Before the Royal Mint heist, Berlin leads a new crew through an elaborate plan for one final love-fueled, chaos-laced burglary in Paris."
},
{
  id: 66,
  title: "Killer Soup",
  platform: "Netflix",
  genre: "Dark Comedy Thriller",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 84,
  hindiDubbed: true,
  description: "A small-town cook accidentally simmers up murder and mayhem while dreaming of opening her own restaurant — using a bizarre recipe for reinvention."
},
{
  id: 67,
  title: "The K2",
  platform: "Netflix",
  genre: "Action Thriller",
  year: 2016,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 85,
  hindiDubbed: true,
  description: "A former mercenary becomes a bodyguard to a presidential candidate’s secret daughter, unraveling power plays and buried truths."
},
{
  id: 68,
  title: "Bring It On, Ghost",
  platform: "Netflix",
  genre: "Supernatural Comedy",
  year: 2016,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 81,
  hindiDubbed: false,
  description: "A ghost-fighting college student teams up with a teenage spirit to exorcise ghouls — and sparks fly between worlds."
},
{
  id: 69,
  title: "Catch the Ghost",
  platform: "Viki",
  genre: "Crime Comedy",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 79,
  hindiDubbed: false,
  description: "A passionate subway police officer joins forces with a by-the-book captain to chase a serial killer lurking beneath Seoul’s metro tunnels."
},
{
  id: 70,
  title: "Kill Me, Heal Me",
  platform: "Viki",
  genre: "Psychological Romance",
  year: 2015,
  seasons: 1,
  episodes: 20,
  runtime: "16h",
  popularity: 89,
  hindiDubbed: true,
  description: "A business heir with dissociative identity disorder hides his seven personalities while working with a psychiatrist to heal — and fall in love."
},
{
  id: 71,
  title: "Hotel Del Luna",
  platform: "Netflix",
  genre: "Fantasy Romance",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 91,
  hindiDubbed: true,
  description: "A centuries-old cursed hotel owner meets a human manager and begins her journey toward redemption as lost souls check in for closure."
},
{
  id: 72,
  title: "Miss Hammurabi",
  platform: "Viki",
  genre: "Legal Drama",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 80,
  hindiDubbed: false,
  description: "An idealistic rookie judge teams up with a strict senior to tackle small but meaningful legal cases full of social commentary and moral dilemmas."
},
{
  id: 73,
  title: "Angel's Last Mission: Love",
  platform: "Viki",
  genre: "Fantasy Romance",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 84,
  hindiDubbed: false,
  description: "A mischievous angel is tasked with finding love for a blind ballerina — but ends up breaking celestial rules as he falls for her himself."
},
{
  id: 74,
  title: "Boys Over Flowers",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2009,
  seasons: 1,
  episodes: 25,
  runtime: "20h",
  popularity: 87,
  hindiDubbed: true,
  description: "A working-class girl enrolls in an elite high school and crosses paths with a group of rich, arrogant boys — and sparks chaos and romance."
},
{
  id: 75,
  title: "Sweet Sweet",
  platform: "iQIYI",
  genre: "C-Romance",
  year: 2021,
  seasons: 1,
  episodes: 22,
  runtime: "18h",
  popularity: 80,
  hindiDubbed: false,
  description: "An AI voice assistant developer moves in next door to a quirky girl who can’t speak well — until their fates collide in the sweetest way."
},
{
  id: 76,
  title: "Fight for My Way",
  platform: "Netflix",
  genre: "Slice of Life Romance",
  year: 2017,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 85,
  hindiDubbed: true,
  description: "Two lifelong friends try to break free from dead-end lives and chase their dreams while navigating unspoken feelings and growing pains."
},
{
  id: 77,
  title: "Who Are You: School 2015",
  platform: "Viki",
  genre: "Teen Mystery",
  year: 2015,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 83,
  hindiDubbed: false,
  description: "After a case of mistaken identity between twin sisters, secrets unravel at an elite high school where bullying and trauma hide behind the perfect image."
},
{
  id: 78,
  title: "Reacher",
  platform: "Prime Video",
  genre: "Action Thriller",
  year: 2022,
  seasons: 2,
  episodes: 16,
  runtime: "13h",
  popularity: 88,
  hindiDubbed: true,
  description: "Jack Reacher, a former military police officer, wanders into a small town — and uncovers a deadly conspiracy that demands brutal justice."
},
{
  id: 79,
  title: "Game of Thrones",
  platform: "HBO Max",
  genre: "Epic Fantasy",
  year: 2011,
  seasons: 8,
  episodes: 73,
  runtime: "70h",
  popularity: 99,
  hindiDubbed: true,
  description: "Noble families clash over control of the Iron Throne in a brutal world where alliances shift, dragons return, and winter is always coming."
},
{
  id: 80,
  title: "The Queen's Gambit",
  platform: "Netflix",
  genre: "Drama",
  year: 2020,
  seasons: 1,
  episodes: 7,
  runtime: "6h",
  popularity: 93,
  hindiDubbed: true,
  description: "An orphan chess prodigy rises to global fame while battling addiction, loneliness, and patriarchy in a male-dominated world."
},
{
  id: 81,
  title: "A Simple Murder",
  platform: "Sony LIV",
  genre: "Dark Comedy",
  year: 2020,
  seasons: 1,
  episodes: 7,
  runtime: "6h",
  popularity: 80,
  hindiDubbed: true,
  description: "A man stuck in a loveless marriage takes up a murder-for-hire job — but chaos reigns as multiple parties chase the same target."
},
{
  id: 82,
  title: "The Wind Blows",
  platform: "Viki",
  genre: "Melodrama",
  year: 2019,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 78,
  hindiDubbed: false,
  description: "A terminally ill man fakes divorce to spare his wife — only to cross paths with her again years later and confront heartbreak head-on."
},
{
  id: 83,
  title: "Pill",
  platform: "YouTube",
  genre: "Sci-Fi Short Drama",
  year: 2023,
  seasons: 1,
  episodes: 6,
  runtime: "2h",
  popularity: 75,
  hindiDubbed: false,
  description: "In a dystopian world, a mysterious pill controls memory, love, and loyalty. A man rebels to reclaim his forgotten truth."
},
{
  id: 84,
  title: "Gyaarah Gyaarah",
  platform: "ZEE5",
  genre: "Time Travel Mystery",
  year: 2024,
  seasons: 1,
  episodes: 10,
  runtime: "9h",
  popularity: 86,
  hindiDubbed: true,
  description: "A time-spanning conspiracy unfolds across 1990, 2001, and 2023 — where one crime ripples across generations and dark secrets echo through time."
},
{
  id: 85,
  title: "Tokyo Swindlers",
  platform: "Netflix",
  genre: "Heist Drama",
  year: 2023,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 82,
  hindiDubbed: false,
  description: "In the shadows of Tokyo, a crew of slick con artists take down corrupt elite using charm, deception, and dazzling street smarts."
},
{
  id: 86,
  title: "Tribhuwan Mishra: C.A Topper",
  platform: "Sony LIV",
  genre: "Comedy Drama",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "6h",
  popularity: 79,
  hindiDubbed: true,
  description: "A small-town man lands a government accounting job, stumbling into crime, politics, and chaos — all while trying to hold onto his values."
},
{
  id: 87,
  title: "Legend of the Blue Sea",
  platform: "Netflix",
  genre: "Fantasy Romance",
  year: 2016,
  seasons: 1,
  episodes: 20,
  runtime: "18h",
  popularity: 90,
  hindiDubbed: true,
  description: "A mermaid from the Joseon era lands in modern-day Seoul and meets the reincarnation of her lost love — now a charming con artist."
},
{
  id: 88,
  title: "My Demon",
  platform: "Netflix",
  genre: "Supernatural Romance",
  year: 2023,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 88,
  hindiDubbed: true,
  description: "A fiery heiress enters a contract marriage with a demon who loses his powers — together, they spark chaos, magic, and unexpected love."
},
{
  id: 89,
  title: "Queen of Tears",
  platform: "Netflix",
  genre: "Melodrama",
  year: 2024,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 92,
  hindiDubbed: true,
  description: "A chaebol heiress and her countryside-born husband struggle to save their crumbling marriage — and their empire — from tragedy and betrayal."
},
{
  id: 90,
  title: "Love to Hate You",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2023,
  seasons: 1,
  episodes: 10,
  runtime: "8h",
  popularity: 85,
  hindiDubbed: true,
  description: "A tough lawyer who distrusts men and a top actor who mistrusts women clash in a fake-dating setup — and fall headfirst into real love."
},
{
  id: 91,
  title: "No Gain No Love",
  platform: "YouTube",
  genre: "Short Romantic Comedy",
  year: 2023,
  seasons: 1,
  episodes: 6,
  runtime: "2h",
  popularity: 74,
  hindiDubbed: false,
  description: "In this fast-paced mini-series, a fitness trainer and a finance consultant navigate a love-hate friendship based on challenges and wagers."
},
{
  id: 92,
  title: "The Law Cafe",
  platform: "Viki",
  genre: "Legal Romance",
  year: 2022,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 80,
  hindiDubbed: true,
  description: "A former prosecutor and his quirky tenant open a café that offers coffee and free legal advice — plus a slow-burn love story brewing inside."
},
{
  id: 93,
  title: "Mere Humsafar",
  platform: "MX Player",
  genre: "Pakistani Romance",
  year: 2022,
  seasons: 1,
  episodes: 40,
  runtime: "32h",
  popularity: 87,
  hindiDubbed: true,
  description: "A neglected girl grows into a strong woman after marrying into a conservative household — where love may finally rewrite her fate."
},
{
  id: 94,
  title: "Kabhi Main Kabhi Tum",
  platform: "YouTube",
  genre: "Romantic Drama",
  year: 2024,
  seasons: 1,
  episodes: 10,
  runtime: "7h",
  popularity: 76,
  hindiDubbed: true,
  description: "Two opposites meet by accident and find their lives woven together across years, heartbreaks, and second chances."
},
{
  id: 95,
  title: "Brinda",
  platform: "Sony LIV",
  genre: "Crime Thriller",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "6h",
  popularity: 81,
  hindiDubbed: true,
  description: "A no-nonsense female cop uncovers layers of crime and conspiracy while chasing a serial killer in a city haunted by secrets."
},
{
  id: 96,
  title: "Paatal Lok",
  platform: "Prime Video",
  genre: "Crime Noir",
  year: 2020,
  seasons: 1,
  episodes: 9,
  runtime: "8h",
  popularity: 92,
  hindiDubbed: true,
  description: "A cynical cop gets entangled in a web of politics, media, and violence after investigating a failed assassination plot."
},
{
  id: 97,
  title: "Pinocchio",
  platform: "Viki",
  genre: "Romantic Drama",
  year: 2014,
  seasons: 1,
  episodes: 20,
  runtime: "18h",
  popularity: 84,
  hindiDubbed: true,
  description: "A young journalist with ‘Pinocchio Syndrome’ — who hiccups when lying — joins a news team seeking justice through truth and love."
},
{
  id: 98,
  title: "Destined With You",
  platform: "Netflix",
  genre: "Fantasy Romance",
  year: 2023,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 86,
  hindiDubbed: true,
  description: "A civil servant unleashes a centuries-old curse — and a forbidden romance — when she opens a book locked for generations."
},
{
  id: 99,
  title: "Better Call Saul",
  platform: "Netflix",
  genre: "Crime Drama",
  year: 2015,
  seasons: 6,
  episodes: 63,
  runtime: "55h",
  popularity: 98,
  hindiDubbed: true,
  description: "Before becoming Saul Goodman, slippery lawyer Jimmy McGill navigates moral crises and criminal connections in this masterful Breaking Bad prequel."
},
{
  id: 100,
  title: "Mr. & Mrs. Smith",
  platform: "Prime Video",
  genre: "Action Romance",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 84,
  hindiDubbed: true,
  description: "Two strangers recruited for a top-secret spy organization must pose as a married couple — but the lies run deeper than they expect."
},
{
  id: 101,
  title: "XO, Kitty",
  platform: "Netflix",
  genre: "Teen Romance",
  year: 2023,
  seasons: 1,
  episodes: 10,
  runtime: "7h",
  popularity: 78,
  hindiDubbed: true,
  description: "Kitty Covey heads to South Korea to reunite with her long-distance boyfriend — only to discover love is messier than she thought."
},
{
  id: 102,
  title: "Bank Under Siege",
  platform: "ZEE5",
  genre: "Thriller",
  year: 2023,
  seasons: 1,
  episodes: 7,
  runtime: "6h",
  popularity: 80,
  hindiDubbed: true,
  description: "A seemingly normal bank day turns into a hostage situation, leading to tense standoffs and shocking revelations about the robbers’ motives."
},
{
  id: 103,
  title: "Black Warrant",
  platform: "ZEE5",
  genre: "Action Thriller",
  year: 2022,
  seasons: 1,
  episodes: 6,
  runtime: "5h",
  popularity: 76,
  hindiDubbed: true,
  description: "An elite commando is assigned a secret ‘black warrant’ hit — but soon learns that he might be the one being hunted."
},
{
  id: 104,
  title: "Day of the Jackal",
  platform: "Peacock",
  genre: "Espionage Thriller",
  year: 2024,
  seasons: 1,
  episodes: 10,
  runtime: "8h",
  popularity: 83,
  hindiDubbed: false,
  description: "An elusive assassin known only as 'The Jackal' is contracted to carry out a high-stakes international hit — as authorities scramble to stop him."
},
{
  id: 105,
  title: "Lupin",
  platform: "Netflix",
  genre: "Heist Mystery",
  year: 2021,
  seasons: 3,
  episodes: 17,
  runtime: "14h",
  popularity: 91,
  hindiDubbed: true,
  description: "Inspired by the adventures of gentleman thief Arsène Lupin, a brilliant con artist sets out to avenge his father’s wrongful framing."
},
{
  id: 106,
  title: "The Gentlemen",
  platform: "Netflix",
  genre: "Crime Drama",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 86,
  hindiDubbed: true,
  description: "When a British aristocrat inherits a cannabis empire, he’s pulled into a world of violence and scheming as rival factions close in."
},
{
  id: 107,
  title: "Marry My Husband",
  platform: "Prime Video",
  genre: "Fantasy Revenge Drama",
  year: 2024,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 90,
  hindiDubbed: true,
  description: "A woman returns to the past after being murdered by her cheating husband — this time determined to rewrite fate and take him down first."
},
{
  id: 108,
  title: "The Night Agent",
  platform: "Netflix",
  genre: "Political Thriller",
  year: 2023,
  seasons: 1,
  episodes: 10,
  runtime: "8h",
  popularity: 88,
  hindiDubbed: true,
  description: "A low-level FBI agent gets thrown into a deadly conspiracy after answering a call on a secret emergency line in the White House basement."
},
{
  id: 109,
  title: "The Trauma Code: Heroes on Call",
  platform: "YouTube",
  genre: "Medical Action",
  year: 2024,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 78,
  hindiDubbed: false,
  description: "Set inside a high-pressure ER, skilled trauma doctors fight to save lives during disasters and crises, uncovering their own hidden wounds."
},
{
  id: 110,
  title: "The Lincoln Lawyer",
  platform: "Netflix",
  genre: "Legal Drama",
  year: 2022,
  seasons: 2,
  episodes: 20,
  runtime: "18h",
  popularity: 87,
  hindiDubbed: true,
  description: "An idealistic criminal defense lawyer operates out of the back of his Lincoln, taking on risky cases that blur the lines of justice."
},
{
  id: 111,
  title: "Melo Movie",
  platform: "YouTube",
  genre: "Short Romantic Drama",
  year: 2023,
  seasons: 1,
  episodes: 5,
  runtime: "2h",
  popularity: 73,
  hindiDubbed: false,
  description: "A heartfelt short series exploring love through soft moments, missed chances, and sweet silences between two ordinary souls."
},
{
  id: 112,
  title: "When Life Gives You Tangerines",
  platform: "YouTube",
  genre: "K-Romance Mini",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "3h",
  popularity: 75,
  hindiDubbed: false,
  description: "A quirky girl who delivers fruit and a stoic part-timer find joy, frustration, and something unexpectedly tender in each other’s company."
},
{
  id: 113,
  title: "Severance",
  platform: "Apple TV+",
  genre: "Sci-Fi Mystery",
  year: 2022,
  seasons: 1,
  episodes: 9,
  runtime: "8h",
  popularity: 92,
  hindiDubbed: false,
  description: "In a company where work memories are surgically separated from personal ones, an employee starts questioning the cost of corporate loyalty."
},
{
  id: 114,
  title: "Start-Up",
  platform: "Netflix",
  genre: "Business Romance",
  year: 2020,
  seasons: 1,
  episodes: 16,
  runtime: "16h",
  popularity: 89,
  hindiDubbed: true,
  description: "Set in South Korea’s tech scene, a dreamer girl and two rival entrepreneurs battle for love and innovation in a start-up competition."
},
{
  id: 115,
  title: "A Killer Paradox",
  platform: "Netflix",
  genre: "Thriller",
  year: 2024,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 84,
  hindiDubbed: true,
  description: "A mild-mannered student accidentally kills a predator — and becomes a serial murderer of criminals, hunted by a detective with secrets."
},
{
  id: 116,
  title: "Juvenile Justice",
  platform: "Netflix",
  genre: "Legal Drama",
  year: 2022,
  seasons: 1,
  episodes: 10,
  runtime: "9h",
  popularity: 86,
  hindiDubbed: true,
  description: "A strict judge known for her hatred of juvenile criminals takes over a youth court — and begins confronting the roots of crime and empathy."
},
{
  id: 117,
  title: "The Heirs",
  platform: "Netflix",
  genre: "Teen Romance",
  year: 2013,
  seasons: 1,
  episodes: 20,
  runtime: "17h",
  popularity: 89,
  hindiDubbed: true,
  description: "Elite high schoolers struggle with love, friendship, and family expectations as a scholarship girl shakes up the balance of their glittering world."
},
{
  id: 118,
  title: "My ID is Gangnam Beauty",
  platform: "Netflix",
  genre: "Slice of Life Romance",
  year: 2018,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 85,
  hindiDubbed: true,
  description: "After plastic surgery changes her life, a college freshman confronts bullying, identity, and self-worth — and meets someone who sees her real face."
},
{
  id: 119,
  title: "Suspicious Partner",
  platform: "Viki",
  genre: "Romantic Legal Thriller",
  year: 2017,
  seasons: 1,
  episodes: 40,
  runtime: "32h",
  popularity: 87,
  hindiDubbed: true,
  description: "A prosecutor and his assistant are swept up in romance, laughter — and a murder case that may connect them more deeply than expected."
},
{
  id: 120,
  title: "The Glory",
  platform: "Netflix",
  genre: "Revenge Drama",
  year: 2022,
  seasons: 2,
  episodes: 16,
  runtime: "14h",
  popularity: 93,
  hindiDubbed: true,
  description: "Years after surviving brutal bullying, a woman becomes a teacher at her tormentors’ child’s school — and methodically destroys their lives."
},
{
  id: 121,
  title: "The Golden Spoon",
  platform: "Disney+ Hotstar",
  genre: "Fantasy Drama",
  year: 2022,
  seasons: 1,
  episodes: 16,
  runtime: "14h",
  popularity: 82,
  hindiDubbed: true,
  description: "A poor teen trades lives with a rich classmate using a golden spoon — but the price of borrowed privilege soon becomes unbearable."
},
{
  id: 122,
  title: "Gyeongseong Creature",
  platform: "Netflix",
  genre: "Historical Horror",
  year: 2023,
  seasons: 1,
  episodes: 10,
  runtime: "9h",
  popularity: 90,
  hindiDubbed: true,
  description: "In 1945 Seoul, a wealthy businessman and a bounty hunter confront horrifying creatures born from greed and colonial evil."
},
{
  id: 123,
  title: "Sweet Home",
  platform: "Netflix",
  genre: "Apocalyptic Horror",
  year: 2020,
  seasons: 2,
  episodes: 20,
  runtime: "18h",
  popularity: 91,
  hindiDubbed: true,
  description: "Residents of an apartment complex are trapped as humans begin turning into monsters — and survival means facing inner demons too."
},
{
  id: 124,
  title: "Unlock My Boss",
  platform: "Viki",
  genre: "Tech Fantasy Comedy",
  year: 2022,
  seasons: 1,
  episodes: 12,
  runtime: "10h",
  popularity: 80,
  hindiDubbed: false,
  description: "A young man picks up a smartphone — and finds the soul of a CEO trapped inside. Together, they try to solve his murder and save the company."
},
{
  id: 125,
  title: "Peaky Blinders",
  platform: "Netflix",
  genre: "Crime Period Drama",
  year: 2013,
  seasons: 6,
  episodes: 36,
  runtime: "40h",
  popularity: 96,
  hindiDubbed: true,
  description: "Tommy Shelby leads the Peaky Blinders, a ruthless gang carving their empire out of post-WWI Birmingham. Fueled by ambition and trauma, Tommy ascends from bookmaker to political powerbroker — but every rise comes with blood, betrayal, and ghosts from the past."
}
];