const englishWatchlist = [
  {
    id: 1,
    title: "Breaking Bad",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2008,
    language: "English",
    hindiDubbed: true,
    seasons: 5,
    episodes: 62,
    runtime: "50h",
    popularity: 99,
    imdbRating: 9.5,
    tags: ["meth", "teacher", "transformation", "cartel", "iconic"],
    description: "A high school chemistry teacher turns to meth production after a cancer diagnosis, changing his life — and the criminal world — forever."
  },
  {
    id: 2,
    title: "Better Call Saul",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2015,
    language: "English",
    hindiDubbed: true,
    seasons: 6,
    episodes: 63,
    runtime: "55h",
    popularity: 98,
    imdbRating: 8.9,
    tags: ["lawyer", "prequel", "ethics", "Breaking Bad", "corruption"],
    description: "Before Saul Goodman represented criminals, he was Jimmy McGill — a clever underdog navigating law, morality, and identity."
  },
  {
    id: 3,
    title: "Stranger Things",
    platform: "Netflix",
    genre: "Sci-Fi Horror",
    year: 2016,
    language: "English",
    hindiDubbed: true,
    seasons: 4,
    episodes: 34,
    runtime: "30h",
    popularity: 98,
    imdbRating: 8.7,
    tags: ["supernatural", "80s", "kids", "demogorgon", "alternate dimension"],
    description: "A group of kids uncovers a secret government experiment and befriends a girl with supernatural powers while searching for their missing friend."
  },
  {
    id: 4,
    title: "The Queen's Gambit",
    platform: "Netflix",
    genre: "Drama",
    year: 2020,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 7,
    runtime: "6h",
    popularity: 93,
    imdbRating: 8.6,
    tags: ["chess", "genius", "orphan", "addiction", "girl power"],
    description: "An orphan chess prodigy rises to global stardom while facing addiction, loneliness, and the constraints of a male-dominated game."
  },
  {
    id: 5,
    title: "Wednesday",
    platform: "Netflix",
    genre: "Supernatural Mystery",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 92,
    imdbRating: 8.1,
    tags: ["gothic", "academy", "detective", "teen", "quirky"],
    description: "Wednesday Addams joins Nevermore Academy and uncovers a monstrous mystery while mastering her psychic abilities."
  },
  {
    id: 6,
    title: "The Night Agent",
    platform: "Netflix",
    genre: "Political Thriller",
    year: 2023,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 10,
    runtime: "8h",
    popularity: 88,
    imdbRating: 7.5,
    tags: ["FBI", "White House", "conspiracy", "emergency line", "danger"],
    description: "A low-level FBI agent gets a cryptic call from the White House basement hotline — dragging him into a deadly conspiracy."
  },
  {
    id: 7,
    title: "Lupin",
    platform: "Netflix",
    genre: "Heist Mystery",
    year: 2021,
    language: "French",
    hindiDubbed: true,
    seasons: 3,
    episodes: 17,
    runtime: "14h",
    popularity: 91,
    imdbRating: 7.5,
    tags: ["gentleman thief", "revenge", "Paris", "disguise", "justice"],
    description: "Inspired by Arsène Lupin, a clever thief orchestrates elaborate heists to avenge his father’s framing — charming the public and fooling the elite."
  },
  {
    id: 8,
    title: "The Boys",
    platform: "Prime Video",
    genre: "Superhero Satire",
    year: 2019,
    language: "English",
    hindiDubbed: true,
    seasons: 3,
    episodes: 24,
    runtime: "22h",
    popularity: 94,
    imdbRating: 8.7,
    tags: ["satire", "antihero", "violence", "superpowers", "conspiracy"],
    description: "A group of vigilantes take down corrupt superheroes who abuse their fame and power under a corporate regime."
  },
  {
    id: 9,
    title: "The Last of Us",
    platform: "HBO Max",
    genre: "Post-Apocalyptic Drama",
    year: 2023,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 9,
    runtime: "9h",
    popularity: 97,
    imdbRating: 8.9,
    tags: ["zombie", "fungus", "road trip", "emotion", "survival"],
    description: "A hardened smuggler escorts a girl immune to a fungal apocalypse across a devastated America while bonding along the way."
  },
  {
    id: 10,
    title: "Reacher",
    platform: "Prime Video",
    genre: "Action Thriller",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 2,
    episodes: 16,
    runtime: "13h",
    popularity: 88,
    imdbRating: 8.1,
    tags: ["ex-military", "investigation", "small town", "brutal", "justice"],
    description: "Jack Reacher rolls into a quiet town — only to uncover corruption, murder, and secrets he can't walk away from."
  },
  {
    id: 11,
    title: "The Lincoln Lawyer",
    platform: "Netflix",
    genre: "Legal Drama",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 2,
    episodes: 20,
    runtime: "18h",
    popularity: 87,
    imdbRating: 7.7,
    tags: ["defense lawyer", "cases", "Los Angeles", "justice", "court"],
    description: "A charismatic defense lawyer takes cases from the back of his Lincoln — navigating morality, crime, and courtroom showdowns in L.A."
  },
  {
    id: 12,
    title: "Game of Thrones",
    platform: "HBO Max",
    genre: "Epic Fantasy",
    year: 2011,
    language: "English",
    hindiDubbed: true,
    seasons: 8,
    episodes: 73,
    runtime: "70h",
    popularity: 99,
    imdbRating: 9.2,
    tags: ["dragons", "throne", "betrayal", "winter", "war"],
    description: "Noble families wage war over the Iron Throne in a medieval world where dragons return, alliances crumble, and winter always looms."
  },
  {
    id: 13,
    title: "The Gentlemen",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2024,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 86,
    imdbRating: 7.8,
    tags: ["weed empire", "inheritance", "gangsters", "UK", "violence"],
    description: "When an English aristocrat inherits a cannabis empire, he’s dragged into underworld rivalries, betrayals, and bloodshed."
  },
  {
  id: 14,
  title: "The Witcher",
  platform: "Netflix",
  genre: "Fantasy",
  year: 2019,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 24,
  runtime: "20h",
  popularity: 91,
  imdbRating: 8.1,
  tags: ["witcher", "magic", "monster hunter", "prophecy", "swordplay"],
  description: "Geralt of Rivia, a monster hunter for hire, struggles to find his place in a world where people can be more wicked than beasts."
},
{
  id: 15,
  title: "The Umbrella Academy",
  platform: "Netflix",
  genre: "Superhero Drama",
  year: 2019,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 30,
  runtime: "25h",
  popularity: 89,
  imdbRating: 8.0,
  tags: ["siblings", "superpowers", "time travel", "dysfunctional", "apocalypse"],
  description: "Adopted superpowered siblings reunite to investigate their father's death and prevent the apocalypse — with plenty of bickering along the way."
},
{
  id: 16,
  title: "Lucifer",
  platform: "Netflix",
  genre: "Fantasy Drama",
  year: 2016,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 93,
  runtime: "70h",
  popularity: 93,
  imdbRating: 8.1,
  tags: ["devil", "crime", "LA", "investigation", "romance"],
  description: "The Devil abandons Hell to run a nightclub in LA — but ends up helping the police solve murders and confront his own redemption arc."
},
{
  id: 17,
  title: "Sherlock",
  platform: "Netflix",
  genre: "Crime Mystery",
  year: 2010,
  language: "English",
  hindiDubbed: true,
  seasons: 4,
  episodes: 13,
  runtime: "18h",
  popularity: 95,
  imdbRating: 9.1,
  tags: ["detective", "London", "modern", "Watson", "mind palace"],
  description: "A modern-day Sherlock Holmes solves crimes in London with razor-sharp intellect, eccentric flair, and his loyal friend Dr. Watson."
},
{
  id: 18,
  title: "House of the Dragon",
  platform: "HBO Max",
  genre: "Fantasy Drama",
  year: 2022,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 10,
  runtime: "10h",
  popularity: 90,
  imdbRating: 8.5,
  tags: ["Targaryen", "dragons", "civil war", "Game of Thrones", "prequel"],
  description: "Set 200 years before Game of Thrones, House Targaryen battles itself for the Iron Throne in a brutal family civil war."
},
{
  id: 19,
  title: "YOU",
  platform: "Netflix",
  genre: "Psychological Thriller",
  year: 2018,
  language: "English",
  hindiDubbed: true,
  seasons: 4,
  episodes: 40,
  runtime: "34h",
  popularity: 87,
  imdbRating: 7.7,
  tags: ["obsession", "stalking", "romance", "murder", "twisted"],
  description: "A charming bookstore manager turns stalker and killer in this disturbing dive into modern love and identity."
},
{
  id: 20,
  title: "The Crown",
  platform: "Netflix",
  genre: "Historical Drama",
  year: 2016,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 60,
  runtime: "55h",
  popularity: 89,
  imdbRating: 8.6,
  tags: ["royalty", "Elizabeth II", "UK", "history", "palace intrigue"],
  description: "Explore the reign and personal life of Queen Elizabeth II — from political crises to private grief — in this award-winning royal saga."
},
{
  id: 21,
  title: "Black Mirror",
  platform: "Netflix",
  genre: "Sci-Fi Anthology",
  year: 2011,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 27,
  runtime: "25h",
  popularity: 90,
  imdbRating: 8.8,
  tags: ["technology", "dystopia", "dark", "standalone", "twists"],
  description: "Each episode explores chilling tales of technology gone too far — a digital-age Twilight Zone with modern horror at its core."
},
{
  id: 22,
  title: "The Sandman",
  platform: "Netflix",
  genre: "Fantasy Drama",
  year: 2022,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 11,
  runtime: "9h",
  popularity: 82,
  imdbRating: 7.7,
  tags: ["dreams", "death", "gods", "gothic", "destiny"],
  description: "The Lord of Dreams escapes imprisonment and journeys to restore his realm — encountering gods, mortals, and nightmares alike."
},
{
  id: 23,
  title: "Lockwood & Co.",
  platform: "Netflix",
  genre: "Supernatural Mystery",
  year: 2023,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 82,
  imdbRating: 7.4,
  tags: ["ghost", "teens", "detective", "action", "haunted"],
  description: "In haunted London, teen ghost hunters battle spirits while running their own paranormal agency — without adult interference."
},
{
  id: 24,
  title: "Outer Banks",
  platform: "Netflix",
  genre: "Adventure Thriller",
  year: 2020,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 30,
  runtime: "24h",
  popularity: 85,
  imdbRating: 7.5,
  tags: ["treasure hunt", "teen drama", "beach town", "class divide"],
  description: "A group of working-class teens sets off on a treasure hunt that uncovers secrets, enemies, and high-stakes betrayals in a coastal paradise."
},
{
  id: 25,
  title: "Peaky Blinders",
  platform: "Netflix",
  genre: "Crime Period Drama",
  year: 2013,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 36,
  runtime: "40h",
  popularity: 96,
  imdbRating: 8.8,
  tags: ["gangsters", "1920s", "Birmingham", "Tommy Shelby", "revenge"],
  description: "Tommy Shelby leads the Peaky Blinders — a feared post-WWI gang carving out power in Birmingham through deals, violence, and political cunning."
},
{
  id: 26,
  title: "The 100",
  platform: "Netflix",
  genre: "Post-Apocalyptic Sci-Fi",
  year: 2014,
  language: "English",
  hindiDubbed: true,
  seasons: 7,
  episodes: 100,
  runtime: "75h",
  popularity: 84,
  imdbRating: 7.6,
  tags: ["survival", "earth", "space", "teen", "rebellion"],
  description: "A hundred juvenile delinquents are sent back to Earth from a space station to test if the planet is habitable — and chaos ensues."
},
{
  id: 27,
  title: "The Mandalorian",
  platform: "Disney+ Hotstar",
  genre: "Sci-Fi Adventure",
  year: 2019,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 24,
  runtime: "20h",
  popularity: 90,
  imdbRating: 8.7,
  tags: ["Star Wars", "bounty hunter", "Grogu", "space western", "action"],
  description: "A lone bounty hunter in the outer reaches of the galaxy protects a mysterious child while navigating the remnants of the Empire."
},
{
  id: 28,
  title: "The Flash",
  platform: "Netflix",
  genre: "Superhero Drama",
  year: 2014,
  language: "English",
  hindiDubbed: true,
  seasons: 9,
  episodes: 184,
  runtime: "130h",
  popularity: 88,
  imdbRating: 7.5,
  tags: ["speedster", "DC", "multiverse", "time travel", "hero"],
  description: "After a freak accident, Barry Allen gains super-speed and becomes The Flash — fighting metahumans and time-bending threats across the multiverse."
},
{
  id: 29,
  title: "The Big Bang Theory",
  platform: "Netflix",
  genre: "Comedy",
  year: 2007,
  language: "English",
  hindiDubbed: true,
  seasons: 12,
  episodes: 279,
  runtime: "100h",
  popularity: 90,
  imdbRating: 8.2,
  tags: ["nerds", "roommates", "physics", "sitcom", "friendship"],
  description: "A group of socially awkward scientists navigate life, love, and geek culture in this hilarious and heartwarming sitcom."
},
{
  id: 30,
  title: "Friends",
  platform: "Netflix",
  genre: "Comedy",
  year: 1994,
  language: "English",
  hindiDubbed: true,
  seasons: 10,
  episodes: 236,
  runtime: "85h",
  popularity: 98,
  imdbRating: 8.9,
  tags: ["New York", "friendship", "romance", "90s", "sitcom"],
  description: "Six friends in Manhattan navigate relationships, careers, and life’s ups and downs — with coffee, sarcasm, and unforgettable moments."
},
{
  id: 31,
  title: "The Big Bang Theory",
  platform: "Netflix",
  genre: "Comedy",
  year: 2007,
  language: "English",
  hindiDubbed: true,
  seasons: 12,
  episodes: 279,
  runtime: "100h",
  popularity: 90,
  imdbRating: 8.2,
  tags: ["nerds", "roommates", "physics", "sitcom", "friendship"],
  description: "A group of socially awkward scientists navigate life, love, and geek culture in this hilarious and heartwarming sitcom."
},
{
  id: 32,
  title: "Friends",
  platform: "Netflix",
  genre: "Comedy",
  year: 1994,
  language: "English",
  hindiDubbed: true,
  seasons: 10,
  episodes: 236,
  runtime: "85h",
  popularity: 98,
  imdbRating: 8.9,
  tags: ["New York", "friendship", "romance", "90s", "sitcom"],
  description: "Six friends in Manhattan navigate relationships, careers, and life’s ups and downs — with coffee, sarcasm, and unforgettable moments."
},
{
  id: 33,
  title: "How I Met Your Mother",
  platform: "Disney+ Hotstar",
  genre: "Comedy",
  year: 2005,
  language: "English",
  hindiDubbed: true,
  seasons: 9,
  episodes: 208,
  runtime: "75h",
  popularity: 89,
  imdbRating: 8.3,
  tags: ["storytelling", "romance", "friendship", "New York", "bar"],
  description: "Ted recounts to his kids the epic tale of how he met their mother — filled with love, laughter, and legendary moments."
},
{
  id: 34,
  title: "Suits",
  platform: "Netflix",
  genre: "Legal Drama",
  year: 2011,
  language: "English",
  hindiDubbed: true,
  seasons: 9,
  episodes: 134,
  runtime: "100h",
  popularity: 92,
  imdbRating: 8.4,
  tags: ["law firm", "Harvey Specter", "Mike Ross", "courtroom", "witty"],
  description: "A college dropout with a photographic memory lands a job at a top law firm — and must keep his secret while winning cases."
},
{
  id: 35,
  title: "13 Reasons Why",
  platform: "Netflix",
  genre: "Teen Drama",
  year: 2017,
  language: "English",
  hindiDubbed: true,
  seasons: 4,
  episodes: 49,
  runtime: "40h",
  popularity: 84,
  imdbRating: 7.5,
  tags: ["high school", "mental health", "tapes", "bullying", "tragedy"],
  description: "After a teen girl’s suicide, her classmates receive tapes explaining the reasons behind her decision — unraveling secrets and guilt."
},
{
  id: 36,
  title: "The Good Doctor",
  platform: "Sony LIV",
  genre: "Medical Drama",
  year: 2017,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 116,
  runtime: "90h",
  popularity: 88,
  imdbRating: 8.1,
  tags: ["autism", "surgery", "hospital", "brilliance", "empathy"],
  description: "A young surgeon with autism and savant syndrome joins a prestigious hospital, challenging norms with his extraordinary skills and heart."
},
{
  id: 37,
  title: "The Mentalist",
  platform: "Amazon Prime Video",
  genre: "Crime Drama",
  year: 2008,
  language: "English",
  hindiDubbed: true,
  seasons: 7,
  episodes: 151,
  runtime: "110h",
  popularity: 87,
  imdbRating: 8.1,
  tags: ["consultant", "CBI", "Red John", "psychic", "investigation"],
  description: "A former psychic uses his keen observational skills to help the CBI solve crimes — while hunting the serial killer who shattered his life."
},
{
  id: 38,
  title: "Dexter",
  platform: "Amazon Prime Video",
  genre: "Crime Thriller",
  year: 2006,
  language: "English",
  hindiDubbed: true,
  seasons: 8,
  episodes: 96,
  runtime: "80h",
  popularity: 86,
  imdbRating: 8.6,
  tags: ["serial killer", "forensics", "Miami", "dark", "justice"],
  description: "By day, Dexter is a blood-spatter analyst. By night, he’s a vigilante serial killer targeting criminals who escaped justice."
},
{
  id: 39,
  title: "Prison Break",
  platform: "Disney+ Hotstar",
  genre: "Action Thriller",
  year: 2005,
  language: "English",
  hindiDubbed: true,
  seasons: 5,
  episodes: 90,
  runtime: "70h",
  popularity: 90,
  imdbRating: 8.3,
  tags: ["prison", "escape", "brothers", "conspiracy", "tattoos"],
  description: "A structural engineer gets himself imprisoned to break out his innocent brother — using an elaborate plan inked on his body."
},
{
  id: 40,
  title: "The Blacklist",
  platform: "Netflix",
  genre: "Crime Thriller",
  year: 2013,
  language: "English",
  hindiDubbed: true,
  seasons: 10,
  episodes: 218,
  runtime: "160h",
  popularity: 89,
  imdbRating: 8.0,
  tags: ["FBI", "criminal", "Red Reddington", "list", "mystery"],
  description: "A notorious criminal surrenders to the FBI with a list of dangerous fugitives — but only if he works with a rookie profiler."
},
{
  id: 41,
  title: "The Originals",
  platform: "Netflix",
  genre: "Supernatural Drama",
  year: 2013,
  language: "English",
  hindiDubbed: true,
  seasons: 5,
  episodes: 92,
  runtime: "70h",
  popularity: 85,
  imdbRating: 8.2,
  tags: ["vampires", "New Orleans", "family", "hybrids", "power"],
  description: "The first family of vampires returns to reclaim New Orleans — facing ancient enemies, family feuds, and supernatural politics."
},
{
  id: 42,
  title: "The Vampire Diaries",
  platform: "Netflix",
  genre: "Supernatural Romance",
  year: 2009,
  language: "English",
  hindiDubbed: true,
  seasons: 8,
  episodes: 171,
  runtime: "130h",
  popularity: 90,
  imdbRating: 7.7,
  tags: ["vampires", "love triangle", "mystic falls", "witches", "teen"],
  description: "A teenage girl is drawn into a world of vampires, witches, and werewolves — and the two immortal brothers who love her."
},
{
  id: 43,
  title: "Shadow and Bone",
  platform: "Netflix",
  genre: "Fantasy Adventure",
  year: 2021,
  language: "English",
  hindiDubbed: true,
  seasons: 2,
  episodes: 16,
  runtime: "14h",
  popularity: 83,
  imdbRating: 7.6,
  tags: ["Grisha", "magic", "war", "darkness", "chosen one"],
  description: "In a war-torn world divided by a wall of darkness, a young soldier discovers a power that could unite her country — or destroy it."
},
{
  id: 44,
  title: "The Society",
  platform: "Netflix",
  genre: "Teen Mystery",
  year: 2019,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 10,
  runtime: "9h",
  popularity: 78,
  imdbRating: 7.0,
  tags: ["disappearance", "teenagers", "new world", "power", "chaos"],
  description: "Teenagers return from a trip to find their town empty — no adults, no rules, and no way out. Can they build a society or destroy it?"
},
{
  id: 45,
  title: "The Haunting of Hill House",
  platform: "Netflix",
  genre: "Horror Drama",
  year: 2018,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 10,
  runtime: "9h",
  popularity: 86,
  imdbRating: 8.6,
  tags: ["ghosts", "family", "trauma", "flashbacks", "haunted house"],
  description: "A fractured family confronts terrifying memories of their childhood home — where grief, guilt, and ghosts still linger in the shadows."
},
{
  id: 46,
  title: "The Punisher",
  platform: "Netflix",
  genre: "Action Thriller",
  year: 2017,
  language: "English",
  hindiDubbed: true,
  seasons: 2,
  episodes: 26,
  runtime: "22h",
  popularity: 85,
  imdbRating: 8.5,
  tags: ["vigilante", "revenge", "military", "Marvel", "brutal"],
  description: "After the murder of his family, Frank Castle becomes The Punisher — a relentless vigilante waging a one-man war on crime."
},
{
  id: 47,
  title: "The Walking Dead",
  platform: "Netflix",
  genre: "Post-Apocalyptic Horror",
  year: 2010,
  language: "English",
  hindiDubbed: true,
  seasons: 11,
  episodes: 177,
  runtime: "140h",
  popularity: 92,
  imdbRating: 8.1,
  tags: ["zombies", "survival", "group", "apocalypse", "drama"],
  description: "In a world overrun by zombies, a group of survivors must fight for their lives — and their humanity — in a collapsing society."
},
{
  id: 48,
  title: "The Rookie",
  platform: "Disney+ Hotstar",
  genre: "Police Drama",
  year: 2018,
  language: "English",
  hindiDubbed: true,
  seasons: 5,
  episodes: 98,
  runtime: "75h",
  popularity: 84,
  imdbRating: 8.0,
  tags: ["rookie cop", "LAPD", "second chance", "action", "crime"],
  description: "A 40-year-old man joins the LAPD as a rookie, proving it's never too late to chase your dream — or face danger head-on."
},
{
  id: 49,
  title: "The Peripheral",
  platform: "Prime Video",
  genre: "Sci-Fi Thriller",
  year: 2022,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 80,
  imdbRating: 7.6,
  tags: ["future", "simulation", "VR", "mystery", "technology"],
  description: "A young woman discovers a portal to a dark future through a VR headset — and becomes entangled in a conspiracy that spans timelines."
},
{
  id: 50,
  title: "The Terminal List",
  platform: "Prime Video",
  genre: "Action Thriller",
  year: 2022,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 83,
  imdbRating: 7.9,
  tags: ["Navy SEAL", "revenge", "conspiracy", "military", "psychological"],
  description: "After his team is ambushed, a Navy SEAL uncovers a deadly conspiracy — and sets out for vengeance with nothing left to lose."
},
{
  id: 51,
  title: "The Night Manager",
  platform: "Disney+ Hotstar",
  genre: "Spy Thriller",
  year: 2016,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 6,
  runtime: "6h",
  popularity: 86,
  imdbRating: 8.0,
  tags: ["espionage", "arms dealer", "undercover", "luxury", "betrayal"],
  description: "A former soldier turned hotel night manager is recruited to infiltrate the inner circle of a dangerous arms dealer."
},
{
  id: 52,
  title: "The Fall",
  platform: "Netflix",
  genre: "Crime Thriller",
  year: 2013,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 17,
  runtime: "15h",
  popularity: 82,
  imdbRating: 8.1,
  tags: ["serial killer", "detective", "psychological", "cat and mouse", "Belfast"],
  description: "A brilliant detective hunts a charming serial killer in Belfast — but the closer she gets, the more personal the game becomes."
},
{
  id: 53,
  title: "Bodyguard",
  platform: "Netflix",
  genre: "Political Thriller",
  year: 2018,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 6,
  runtime: "6h",
  popularity: 84,
  imdbRating: 8.1,
  tags: ["security", "politics", "PTSD", "suspense", "UK"],
  description: "A war veteran assigned to protect a controversial politician finds himself caught between duty, trauma, and a deadly conspiracy."
},
{
  id: 54,
  title: "The End of the F***ing World",
  platform: "Netflix",
  genre: "Dark Comedy Drama",
  year: 2017,
  language: "English",
  hindiDubbed: true,
  seasons: 2,
  episodes: 16,
  runtime: "6h",
  popularity: 81,
  imdbRating: 8.0,
  tags: ["runaways", "teen", "murder", "awkward", "road trip"],
  description: "A self-proclaimed psychopath and a rebellious girl hit the road — and their twisted journey turns into something unexpectedly tender."
},
{
  id: 55,
  title: "The Good Place",
  platform: "Netflix",
  genre: "Fantasy Comedy",
  year: 2016,
  language: "English",
  hindiDubbed: true,
  seasons: 4,
  episodes: 50,
  runtime: "35h",
  popularity: 88,
  imdbRating: 8.2,
  tags: ["afterlife", "ethics", "twist", "humor", "heaven"],
  description: "A woman wakes up in the afterlife — but realizes she doesn’t belong there. Can she become a better person before it’s too late?"
},
{
  id: 56,
  title: "Brooklyn Nine-Nine",
  platform: "Netflix",
  genre: "Comedy",
  year: 2013,
  language: "English",
  hindiDubbed: true,
  seasons: 8,
  episodes: 153,
  runtime: "60h",
  popularity: 94,
  imdbRating: 8.4,
  tags: ["police", "humor", "squad", "New York", "sitcom"],
  description: "Detective Jake Peralta and his quirky team solve crimes and crack jokes in Brooklyn’s 99th precinct — one hilarious case at a time."
},
{
  id: 57,
  title: "The Office (US)",
  platform: "Netflix",
  genre: "Mockumentary Comedy",
  year: 2005,
  language: "English",
  hindiDubbed: true,
  seasons: 9,
  episodes: 201,
  runtime: "90h",
  popularity: 96,
  imdbRating: 9.0,
  tags: ["workplace", "Dunder Mifflin", "Michael Scott", "paper company", "awkward"],
  description: "A documentary crew captures the daily absurdities of office life at a paper company — where awkwardness and heart collide."
},
{
  id: 58,
  title: "Modern Family",
  platform: "Disney+ Hotstar",
  genre: "Family Comedy",
  year: 2009,
  language: "English",
  hindiDubbed: true,
  seasons: 11,
  episodes: 250,
  runtime: "100h",
  popularity: 90,
  imdbRating: 8.5,
  tags: ["family", "mockumentary", "diversity", "parenting", "humor"],
  description: "Three wildly different families navigate love, chaos, and parenting in this heartwarming and hilarious mockumentary-style sitcom."
},
{
  id: 59,
  title: "Young Sheldon",
  platform: "Netflix",
  genre: "Comedy",
  year: 2017,
  language: "English",
  hindiDubbed: true,
  seasons: 6,
  episodes: 127,
  runtime: "50h",
  popularity: 87,
  imdbRating: 7.6,
  tags: ["child prodigy", "Texas", "family", "Big Bang Theory", "school"],
  description: "A young Sheldon Cooper navigates childhood in East Texas — where his genius mind clashes hilariously with small-town life."
},
{
  id: 60,
  title: "The Politician",
  platform: "Netflix",
  genre: "Dark Comedy Drama",
  year: 2019,
  language: "English",
  hindiDubbed: true,
  seasons: 2,
  episodes: 15,
  runtime: "12h",
  popularity: 78,
  imdbRating: 7.5,
  tags: ["student politics", "ambition", "satire", "election", "elite"],
  description: "A wealthy high school student is determined to become President of the United States — starting with winning his school election at any cost."
},
{
  id: 61,
  title: "Designated Survivor",
  platform: "Netflix",
  genre: "Political Thriller",
  year: 2016,
  language: "English",
  hindiDubbed: true,
  seasons: 3,
  episodes: 53,
  runtime: "45h",
  popularity: 85,
  imdbRating: 7.5,
  tags: ["President", "conspiracy", "unexpected leader", "government", "terrorism"],
  description: "When a terrorist attack kills the entire U.S. government leadership, a low-level cabinet member suddenly becomes President — and chaos follows."
},
{
  id: 62,
  title: "Snowpiercer",
  platform: "Netflix",
  genre: "Sci-Fi Thriller",
  year: 2020,
  language: "English",
  hindiDubbed: true,
  seasons: 4,
  episodes: 40,
  runtime: "35h",
  popularity: 81,
  imdbRating: 6.9,
  tags: ["train", "apocalypse", "revolution", "class", "survival"],
  description: "In a frozen future, the last remnants of humanity live aboard a giant train — where class warfare, secrets, and survival drive the ride."
},
{
  id: 63,
  title: "Archive 81",
  platform: "Netflix",
  genre: "Horror Mystery",
  year: 2022,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 76,
  imdbRating: 7.3,
  tags: ["tapes", "cult", "restoration", "mystery", "ritual"],
  description: "An archivist is hired to restore old video tapes — but finds a haunting connection to a woman investigating a dangerous cult."
},
{
  id: 64,
  title: "The Diplomat",
  platform: "Netflix",
  genre: "Political Drama",
  year: 2023,
  language: "English",
  hindiDubbed: true,
  seasons: 1,
  episodes: 8,
  runtime: "7h",
  popularity: 80,
  imdbRating: 8.0,
  tags: ["ambassador", "marriage", "crisis", "international", "negotiation"],
  description: "A career diplomat is thrust into global turmoil and personal chaos as she takes on a high-stakes post — while managing her rocky marriage."
},
