// englishrecommendations.js - updated posterUrl fields by scripts/fetch_tmdb_posters.js
// DO NOT COMMIT your TMDB API key. This file is safe to commit (contains only data).

window.englishWatchlist = [
  {
    "id": 1,
    "title": "Breaking Bad",
    "platform": "Netflix",
    "genre": "Crime, Drama",
    "year": 2008,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 5,
    "episodes": 62,
    "runtime": "50h",
    "popularity": 99,
    "imdbRating": 9.5,
    "mustwatch": true,
    "tags": [
      "meth",
      "teacher",
      "transformation",
      "cartel",
      "iconic"
    ],
    "description": "A high school chemistry teacher turns to meth production after a cancer diagnosis, changing his life — and the criminal world — forever.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg"
  },
  {
    "id": 2,
    "title": "Better Call Saul",
    "platform": "Netflix",
    "genre": "Crime, Drama",
    "year": 2015,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 63,
    "runtime": "55h",
    "popularity": 98,
    "imdbRating": 8.9,
    "mustwatch": false,
    "tags": [
      "lawyer",
      "prequel",
      "ethics",
      "Breaking Bad",
      "corruption"
    ],
    "description": "Before Saul Goodman represented criminals, he was Jimmy McGill — a clever underdog navigating law, morality, and identity.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg"
  },
  {
    "id": 3,
    "title": "Stranger Things",
    "platform": "Netflix",
    "genre": "Sci-Fi, Horror",
    "year": 2016,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 4,
    "episodes": 34,
    "runtime": "30h",
    "popularity": 98,
    "imdbRating": 8.7,
    "mustwatch": false,
    "tags": [
      "supernatural",
      "80s",
      "kids",
      "demogorgon",
      "alternate dimension"
    ],
    "description": "A group of kids uncovers a secret government experiment and befriends a girl with supernatural powers while searching for their missing friend.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg"
  },
  {
    "id": 4,
    "title": "The Queen's Gambit",
    "platform": "Netflix",
    "genre": "Drama",
    "year": 2020,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 7,
    "runtime": "6h",
    "popularity": 93,
    "imdbRating": 8.6,
    "mustwatch": false,
    "tags": [
      "chess",
      "genius",
      "orphan",
      "addiction",
      "girl power"
    ],
    "description": "An orphan chess prodigy rises to global stardom while facing addiction, loneliness, and the constraints of a male-dominated game.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg"
  },
  {
    "id": 5,
    "title": "Wednesday",
    "platform": "Netflix",
    "genre": "Supernatural, Mystery",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 8,
    "runtime": "6.5h",
    "popularity": 92,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "gothic",
      "academy",
      "detective",
      "teen",
      "quirky"
    ],
    "description": "Wednesday Addams joins Nevermore Academy and uncovers a monstrous mystery while mastering her psychic abilities.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg"
  },
  {
    "id": 6,
    "title": "The Night Agent",
    "platform": "Netflix",
    "genre": "Political, Thriller",
    "year": 2023,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 10,
    "runtime": "8h",
    "popularity": 88,
    "imdbRating": 7.5,
    "mustwatch": false,
    "tags": [
      "FBI",
      "White House",
      "conspiracy",
      "emergency line",
      "danger"
    ],
    "description": "A low-level FBI agent gets a cryptic call from the White House basement hotline — dragging him into a deadly conspiracy.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/4c5yUNcaff4W4aPrkXE6zr7papX.jpg"
  },
  {
    "id": 7,
    "title": "Lupin",
    "platform": "Netflix",
    "genre": "Heist, Mystery",
    "year": 2021,
    "language": "French",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 17,
    "runtime": "14h",
    "popularity": 91,
    "imdbRating": 7.5,
    "mustwatch": false,
    "tags": [
      "gentleman thief",
      "revenge",
      "Paris",
      "disguise",
      "justice"
    ],
    "description": "Inspired by Arsène Lupin, a clever thief orchestrates elaborate heists to avenge his father’s framing — charming the public and fooling the elite.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/h6Z2oogE4mJk2uffdtIlLhb0EHx.jpg"
  },
  {
    "id": 8,
    "title": "The Boys",
    "platform": "Prime Video",
    "genre": "Superhero, Satire",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 24,
    "runtime": "22h",
    "popularity": 94,
    "imdbRating": 8.7,
    "mustwatch": false,
    "tags": [
      "satire",
      "antihero",
      "violence",
      "superpowers",
      "conspiracy"
    ],
    "description": "A group of vigilantes take down corrupt superheroes who abuse their fame and power under a corporate regime.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg"
  },
  {
    "id": 9,
    "title": "The Last of Us",
    "platform": "HBO Max",
    "genre": "Post-Apocalyptic, Drama",
    "year": 2023,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 9,
    "runtime": "9h",
    "popularity": 97,
    "imdbRating": 8.9,
    "mustwatch": false,
    "tags": [
      "zombie",
      "fungus",
      "road trip",
      "emotion",
      "survival"
    ],
    "description": "A hardened smuggler escorts a girl immune to a fungal apocalypse across a devastated America while bonding along the way.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg"
  },
  {
    "id": 10,
    "title": "Reacher",
    "platform": "Prime Video",
    "genre": "Action, Thriller",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 16,
    "runtime": "13h",
    "popularity": 88,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "ex-military",
      "investigation",
      "small town",
      "brutal",
      "justice"
    ],
    "description": "Jack Reacher rolls into a quiet town — only to uncover corruption, murder, and secrets he can't walk away from.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/31GlRQMiDunO8cl3NxTz34U64rf.jpg"
  },
  {
    "id": 11,
    "title": "The Lincoln Lawyer",
    "platform": "Netflix",
    "genre": "Legal, Drama",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 20,
    "runtime": "18h",
    "popularity": 87,
    "imdbRating": 7.7,
    "mustwatch": false,
    "tags": [
      "defense lawyer",
      "cases",
      "Los Angeles",
      "justice",
      "court"
    ],
    "description": "A charismatic defense lawyer takes cases from the back of his Lincoln — navigating morality, crime, and courtroom showdowns in L.A.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/4jSaIqEU8CPBBNn4iVCK6wzPjSx.jpg"
  },
  {
    "id": 12,
    "title": "Game of Thrones",
    "platform": "HBO Max",
    "genre": "Epic, Fantasy",
    "year": 2011,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 8,
    "episodes": 73,
    "runtime": "70h",
    "popularity": 99,
    "imdbRating": 9.2,
    "mustwatch": true,
    "tags": [
      "dragons",
      "throne",
      "betrayal",
      "winter",
      "war"
    ],
    "description": "Noble families wage war over the Iron Throne in a medieval world where dragons return, alliances crumble, and winter always looms.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg"
  },
  {
    "id": 13,
    "title": "The Gentlemen",
    "platform": "Netflix",
    "genre": "Crime, Drama",
    "year": 2024,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 8,
    "runtime": "7h",
    "popularity": 86,
    "imdbRating": 7.8,
    "mustwatch": false,
    "tags": [
      "weed empire",
      "inheritance",
      "gangsters",
      "UK",
      "violence"
    ],
    "description": "When an English aristocrat inherits a cannabis empire, he’s dragged into underworld rivalries, betrayals, and bloodshed.",
    "isNew": true,
    "posterUrl": "https://image.tmdb.org/t/p/w500/tw3tzfXaSpmUZIB8ZNqNEGzMBCy.jpg"
  },
  {
    "id": 14,
    "title": "The Witcher",
    "platform": "Netflix",
    "genre": "Fantasy",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 24,
    "runtime": "20h",
    "popularity": 91,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "witcher",
      "magic",
      "monster hunter",
      "prophecy",
      "swordplay"
    ],
    "description": "Geralt of Rivia, a monster hunter for hire, struggles to find his place in a world where people can be more wicked than beasts.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/AoGsDM02UVt0npBA8OvpDcZbaMi.jpg"
  },
  {
    "id": 15,
    "title": "The Umbrella Academy",
    "platform": "Netflix",
    "genre": "Superhero, Drama",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 30,
    "runtime": "25h",
    "popularity": 89,
    "imdbRating": 8,
    "mustwatch": false,
    "tags": [
      "siblings",
      "superpowers",
      "time travel",
      "dysfunctional",
      "apocalypse"
    ],
    "description": "Adopted superpowered siblings reunite to investigate their father's death and prevent the apocalypse — with plenty of bickering along the way.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/qhcwrnnCnN8NE1N6XXKHFmveJR9.jpg"
  },
  {
    "id": 16,
    "title": "Lucifer",
    "platform": "Netflix",
    "genre": "Fantasy, Drama",
    "year": 2016,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 93,
    "runtime": "70h",
    "popularity": 93,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "devil",
      "crime",
      "LA",
      "investigation",
      "romance"
    ],
    "description": "The Devil abandons Hell to run a nightclub in LA — but ends up helping the police solve murders and confront his own redemption arc.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ekZobS8isE6mA53RAiGDG93hBxL.jpg"
  },
  {
    "id": 17,
    "title": "Sherlock",
    "platform": "Netflix",
    "genre": "Crime, Mystery",
    "year": 2010,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 4,
    "episodes": 13,
    "runtime": "18h",
    "popularity": 95,
    "imdbRating": 9.1,
    "mustwatch": true,
    "tags": [
      "detective",
      "London",
      "modern",
      "Watson",
      "mind palace"
    ],
    "description": "A modern-day Sherlock Holmes solves crimes in London with razor-sharp intellect, eccentric flair, and his loyal friend Dr. Watson.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/cIfGAkpvWD2zxHrXzhv3uptYbyV.jpg"
  },
  {
    "id": 18,
    "title": "House of the Dragon",
    "platform": "HBO Max",
    "genre": "Fantasy, Drama",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 10,
    "runtime": "10h",
    "popularity": 90,
    "imdbRating": 8.5,
    "mustwatch": false,
    "tags": [
      "Targaryen",
      "dragons",
      "civil war",
      "Game of Thrones",
      "prequel"
    ],
    "description": "Set 200 years before Game of Thrones, House Targaryen battles itself for the Iron Throne in a brutal family civil war.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/oxmdHR5Ka28HAJuMmS2hk5K6QQY.jpg"
  },
  {
    "id": 19,
    "title": "YOU",
    "platform": "Netflix",
    "genre": "Psychological, Thriller",
    "year": 2018,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 4,
    "episodes": 40,
    "runtime": "34h",
    "popularity": 87,
    "imdbRating": 7.7,
    "mustwatch": false,
    "tags": [
      "obsession",
      "stalking",
      "romance",
      "murder",
      "twisted"
    ],
    "description": "A charming bookstore manager turns stalker and killer in this disturbing dive into modern love and identity.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/oANi0vEE92nuijiZQgPZ88FSxqQ.jpg"
  },
  {
    "id": 20,
    "title": "The Crown",
    "platform": "Netflix",
    "genre": "Historical, Drama",
    "year": 2016,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 60,
    "runtime": "55h",
    "popularity": 89,
    "imdbRating": 8.6,
    "mustwatch": false,
    "tags": [
      "royalty",
      "Elizabeth II",
      "UK",
      "history",
      "palace intrigue"
    ],
    "description": "Explore the reign and personal life of Queen Elizabeth II — from political crises to private grief — in this award-winning royal saga.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/1DDE0Z2Y805rqfkEjPbZsMLyPwa.jpg"
  },
  {
    "id": 21,
    "title": "Black Mirror",
    "platform": "Netflix",
    "genre": "Sci-Fi, Anthology",
    "year": 2011,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 27,
    "runtime": "25h",
    "popularity": 90,
    "imdbRating": 8.8,
    "mustwatch": false,
    "tags": [
      "technology",
      "dystopia",
      "dark",
      "standalone",
      "twists"
    ],
    "description": "Each episode explores chilling tales of technology gone too far — a digital-age Twilight Zone with modern horror at its core.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg"
  },
  {
    "id": 22,
    "title": "The Sandman",
    "platform": "Netflix",
    "genre": "Fantasy, Drama",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 11,
    "runtime": "9h",
    "popularity": 82,
    "imdbRating": 7.7,
    "mustwatch": false,
    "tags": [
      "dreams",
      "death",
      "gods",
      "gothic",
      "destiny"
    ],
    "description": "The Lord of Dreams escapes imprisonment and journeys to restore his realm — encountering gods, mortals, and nightmares alike.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/q54qEgagGOYCq5D1903eBVMNkbo.jpg"
  },
  {
    "id": 23,
    "title": "Lockwood & Co.",
    "platform": "Netflix",
    "genre": "Supernatural, Mystery",
    "year": 2023,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 8,
    "runtime": "7h",
    "popularity": 82,
    "imdbRating": 7.4,
    "mustwatch": false,
    "tags": [
      "ghost",
      "teens",
      "detective",
      "action",
      "haunted"
    ],
    "description": "In haunted London, teen ghost hunters battle spirits while running their own paranormal agency — without adult interference.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/lxWSGo8D6MbFbQmM9tqhbaG80TP.jpg"
  },
  {
    "id": 24,
    "title": "Outer Banks",
    "platform": "Netflix",
    "genre": "Adventure, Thriller",
    "year": 2020,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 30,
    "runtime": "24h",
    "popularity": 85,
    "imdbRating": 7.5,
    "mustwatch": false,
    "tags": [
      "treasure hunt",
      "teen drama",
      "beach town",
      "class divide"
    ],
    "description": "A group of working-class teens sets off on a treasure hunt that uncovers secrets, enemies, and high-stakes betrayals in a coastal paradise.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ovDgO2LPfwdVRfvScAqo9aMiIW.jpg"
  },
  {
    "id": 25,
    "title": "Peaky Blinders",
    "platform": "Netflix",
    "genre": "Crime, Period Drama",
    "year": 2013,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 36,
    "runtime": "40h",
    "popularity": 96,
    "imdbRating": 8.8,
    "mustwatch": false,
    "tags": [
      "gangsters",
      "1920s",
      "Birmingham",
      "Tommy Shelby",
      "revenge"
    ],
    "description": "Tommy Shelby leads the Peaky Blinders — a feared post-WWI gang carving out power in Birmingham through deals, violence, and political cunning.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg"
  },
  {
    "id": 26,
    "title": "The 100",
    "platform": "Netflix",
    "genre": "Post-Apocalyptic, Sci-Fi",
    "year": 2014,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 7,
    "episodes": 100,
    "runtime": "75h",
    "popularity": 84,
    "imdbRating": 7.6,
    "mustwatch": false,
    "tags": [
      "survival",
      "earth",
      "space",
      "teen",
      "rebellion"
    ],
    "description": "A hundred juvenile delinquents are sent back to Earth from a space station to test if the planet is habitable — and chaos ensues.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg"
  },
  {
    "id": 27,
    "title": "The Mandalorian",
    "platform": "Disney+ Hotstar",
    "genre": "Sci-Fi, Adventure",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 24,
    "runtime": "20h",
    "popularity": 90,
    "imdbRating": 8.7,
    "mustwatch": false,
    "tags": [
      "Star Wars",
      "bounty hunter",
      "Grogu",
      "space western",
      "action"
    ],
    "description": "A lone bounty hunter in the outer reaches of the galaxy protects a mysterious child while navigating the remnants of the Empire.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg"
  },
  {
    "id": 28,
    "title": "The Flash",
    "platform": "Netflix",
    "genre": "Superhero, Drama",
    "year": 2014,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 9,
    "episodes": 184,
    "runtime": "130h",
    "popularity": 88,
    "imdbRating": 7.5,
    "mustwatch": false,
    "tags": [
      "speedster",
      "DC",
      "multiverse",
      "time travel",
      "hero"
    ],
    "description": "After a freak accident, Barry Allen gains super-speed and becomes The Flash — fighting metahumans and time-bending threats across the multiverse.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/yZevl2vHQgmosfwUdVNzviIfaWS.jpg"
  },
  {
    "id": 29,
    "title": "The Expanse",
    "platform": "Prime Video",
    "genre": "Sci-Fi, Thriller",
    "year": 2015,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 62,
    "runtime": "55h",
    "popularity": 85,
    "imdbRating": 8.5,
    "mustwatch": false,
    "tags": [
      "space",
      "politics",
      "colonies",
      "mystery",
      "future"
    ],
    "description": "In a colonized solar system, tensions rise between Earth, Mars, and the Belt — until a mysterious alien technology threatens to tip the balance of power and survival.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/8djpxDeWpINnGhjpFXQjnBe6zbx.jpg"
  },
  {
    "id": 30,
    "title": "Mindhunter",
    "platform": "Netflix",
    "genre": "Crime, Thriller",
    "year": 2017,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 19,
    "runtime": "17h",
    "popularity": 87,
    "imdbRating": 8.6,
    "mustwatch": false,
    "tags": [
      "FBI",
      "serial killers",
      "psychology",
      "interviews",
      "1970s"
    ],
    "description": "In the late 1970s, two FBI agents pioneer criminal profiling by interviewing serial killers — diving deep into the darkest minds to solve active cases.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/fbKE87mojpIETWepSbD5Qt741fp.jpg"
  },
  {
    "id": 31,
    "title": "The Big Bang Theory",
    "platform": "Netflix",
    "genre": "Comedy",
    "year": 2007,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 12,
    "episodes": 279,
    "runtime": "100h",
    "popularity": 90,
    "imdbRating": 8.2,
    "mustwatch": false,
    "tags": [
      "nerds",
      "roommates",
      "physics",
      "sitcom",
      "friendship"
    ],
    "description": "A group of socially awkward scientists navigate life, love, and geek culture in this hilarious and heartwarming sitcom.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg"
  },
  {
    "id": 32,
    "title": "Friends",
    "platform": "Netflix",
    "genre": "Comedy",
    "year": 1994,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 10,
    "episodes": 236,
    "runtime": "85h",
    "popularity": 98,
    "imdbRating": 8.9,
    "mustwatch": false,
    "tags": [
      "New York",
      "friendship",
      "romance",
      "90s",
      "sitcom"
    ],
    "description": "Six friends in Manhattan navigate relationships, careers, and life’s ups and downs — with coffee, sarcasm, and unforgettable moments.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg"
  },
  {
    "id": 33,
    "title": "How I Met Your Mother",
    "platform": "Disney+ Hotstar",
    "genre": "Comedy",
    "year": 2005,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 9,
    "episodes": 208,
    "runtime": "75h",
    "popularity": 89,
    "imdbRating": 8.3,
    "mustwatch": false,
    "tags": [
      "storytelling",
      "romance",
      "friendship",
      "New York",
      "bar"
    ],
    "description": "Ted recounts to his kids the epic tale of how he met their mother — filled with love, laughter, and legendary moments.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg"
  },
  {
    "id": 34,
    "title": "Suits",
    "platform": "Netflix",
    "genre": "Legal, Drama",
    "year": 2011,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 9,
    "episodes": 134,
    "runtime": "100h",
    "popularity": 92,
    "imdbRating": 8.4,
    "mustwatch": false,
    "tags": [
      "law firm",
      "Harvey Specter",
      "Mike Ross",
      "courtroom",
      "witty"
    ],
    "description": "A college dropout with a photographic memory lands a job at a top law firm — and must keep his secret while winning cases.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/vQiryp6LioFxQThywxbC6TuoDjy.jpg"
  },
  {
    "id": 35,
    "title": "13 Reasons Why",
    "platform": "Netflix",
    "genre": "Teen, Drama",
    "year": 2017,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 4,
    "episodes": 49,
    "runtime": "40h",
    "popularity": 84,
    "imdbRating": 7.5,
    "mustwatch": false,
    "tags": [
      "high school",
      "mental health",
      "tapes",
      "bullying",
      "tragedy"
    ],
    "description": "After a teen girl’s suicide, her classmates receive tapes explaining the reasons behind her decision — unraveling secrets and guilt.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/nel144y4dIOdFFid6twN5mAX9Yd.jpg"
  },
  {
    "id": 36,
    "title": "The Good Doctor",
    "platform": "Sony LIV",
    "genre": "Medical, Drama",
    "year": 2017,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 6,
    "episodes": 116,
    "runtime": "90h",
    "popularity": 88,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "autism",
      "surgery",
      "hospital",
      "brilliance",
      "empathy"
    ],
    "description": "A young surgeon with autism and savant syndrome joins a prestigious hospital, challenging norms with his extraordinary skills and heart.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/luhKkdD80qe62fwop6sdrXK9jUT.jpg"
  },
  {
    "id": 37,
    "title": "The Mentalist",
    "platform": "Amazon Prime Video",
    "genre": "Crime, Drama",
    "year": 2008,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 7,
    "episodes": 151,
    "runtime": "110h",
    "popularity": 87,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "consultant",
      "CBI",
      "Red John",
      "psychic",
      "investigation"
    ],
    "description": "A former psychic uses his keen observational skills to help the CBI solve crimes — while hunting the serial killer who shattered his life.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/acYXu4KaDj1NIkMgObnhe4C4a0T.jpg"
  },
  {
    "id": 38,
    "title": "Dexter",
    "platform": "Amazon Prime Video",
    "genre": "Crime, Thriller",
    "year": 2006,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 8,
    "episodes": 96,
    "runtime": "80h",
    "popularity": 86,
    "imdbRating": 8.6,
    "mustwatch": false,
    "tags": [
      "serial killer",
      "forensics",
      "Miami",
      "dark",
      "justice"
    ],
    "description": "By day, Dexter is a blood-spatter analyst. By night, he’s a vigilante serial killer targeting criminals who escaped justice.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/q8dWfc4JwQuv3HayIZeO84jAXED.jpg"
  },
  {
    "id": 39,
    "title": "Prison Break",
    "platform": "Disney+ Hotstar",
    "genre": "Action, Thriller",
    "year": 2005,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 5,
    "episodes": 90,
    "runtime": "70h",
    "popularity": 90,
    "imdbRating": 8.3,
    "mustwatch": false,
    "tags": [
      "prison",
      "escape",
      "brothers",
      "conspiracy",
      "tattoos"
    ],
    "description": "A structural engineer gets himself imprisoned to break out his innocent brother — using an elaborate plan inked on his body.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/z885tJn5kkUHppjIK1g2Q54iTff.jpg"
  },
  {
    "id": 40,
    "title": "The Blacklist",
    "platform": "Netflix",
    "genre": "Crime, Thriller",
    "year": 2013,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 10,
    "episodes": 218,
    "runtime": "160h",
    "popularity": 89,
    "imdbRating": 8,
    "mustwatch": false,
    "tags": [
      "FBI",
      "criminal",
      "Red Reddington",
      "list",
      "mystery"
    ],
    "description": "A notorious criminal surrenders to the FBI with a list of dangerous fugitives — but only if he works with a rookie profiler.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/4HTfd1PhgFUenJxVuBDNdLmdr0c.jpg"
  },
  {
    "id": 41,
    "title": "The Originals",
    "platform": "Netflix",
    "genre": "Supernatural, Drama",
    "year": 2013,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 5,
    "episodes": 92,
    "runtime": "70h",
    "popularity": 85,
    "imdbRating": 8.2,
    "mustwatch": false,
    "tags": [
      "vampires",
      "New Orleans",
      "family",
      "hybrids",
      "power"
    ],
    "description": "The first family of vampires returns to reclaim New Orleans — facing ancient enemies, family feuds, and supernatural politics.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/keJOhJXGiLL54EW6QocbyvQGquA.jpg"
  },
  {
    "id": 42,
    "title": "The Vampire Diaries",
    "platform": "Netflix",
    "genre": "Supernatural, Romance",
    "year": 2009,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 8,
    "episodes": 171,
    "runtime": "130h",
    "popularity": 90,
    "imdbRating": 7.7,
    "mustwatch": false,
    "tags": [
      "vampires",
      "love triangle",
      "mystic falls",
      "witches",
      "teen"
    ],
    "description": "A teenage girl is drawn into a world of vampires, witches, and werewolves — and the two immortal brothers who love her.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/b3vl6wV1W8PBezFfntKTrhrehCY.jpg"
  },
  {
    "id": 43,
    "title": "Shadow and Bone",
    "platform": "Netflix",
    "genre": "Fantasy, Adventure",
    "year": 2021,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 16,
    "runtime": "14h",
    "popularity": 83,
    "imdbRating": 7.6,
    "mustwatch": false,
    "tags": [
      "Grisha",
      "magic",
      "war",
      "darkness",
      "chosen one"
    ],
    "description": "In a war-torn world divided by a wall of darkness, a young soldier discovers a power that could unite her country — or destroy it.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/mS9O9mjPlwpLTne4JgQlDkgREWA.jpg"
  },
  {
    "id": 44,
    "title": "The Society",
    "platform": "Netflix",
    "genre": "Teen, Mystery",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 10,
    "runtime": "9h",
    "popularity": 78,
    "imdbRating": 7,
    "mustwatch": false,
    "tags": [
      "disappearance",
      "teenagers",
      "new world",
      "power",
      "chaos"
    ],
    "description": "Teenagers return from a trip to find their town empty — no adults, no rules, and no way out. Can they build a society or destroy it?",
    "posterUrl": "https://image.tmdb.org/t/p/w500/mxOlnFEQMpxjIltr9Ox06iyjjvK.jpg"
  },
  {
    "id": 45,
    "title": "The Haunting of Hill House",
    "platform": "Netflix",
    "genre": "Horror, Drama",
    "year": 2018,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 10,
    "runtime": "9h",
    "popularity": 86,
    "imdbRating": 8.6,
    "mustwatch": false,
    "tags": [
      "ghosts",
      "family",
      "trauma",
      "flashbacks",
      "haunted house"
    ],
    "description": "A fractured family confronts terrifying memories of their childhood home — where grief, guilt, and ghosts still linger in the shadows.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/38PkhBGRQtmVx2drvPik3F42qHO.jpg"
  },
  {
    "id": 46,
    "title": "The Punisher",
    "platform": "Netflix",
    "genre": "Action, Thriller",
    "year": 2017,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 26,
    "runtime": "22h",
    "popularity": 85,
    "imdbRating": 8.5,
    "mustwatch": false,
    "tags": [
      "vigilante",
      "revenge",
      "military",
      "Marvel",
      "brutal"
    ],
    "description": "After the murder of his family, Frank Castle becomes The Punisher — a relentless vigilante waging a one-man war on crime.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/tM6xqRKXoloH9UchaJEyyRE9O1w.jpg"
  },
  {
    "id": 47,
    "title": "The Walking Dead",
    "platform": "Netflix",
    "genre": "Post-Apocalyptic, Horror",
    "year": 2010,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 11,
    "episodes": 177,
    "runtime": "140h",
    "popularity": 92,
    "imdbRating": 8.1,
    "mustwatch": false,
    "tags": [
      "zombies",
      "survival",
      "group",
      "apocalypse",
      "drama"
    ],
    "description": "In a world overrun by zombies, a group of survivors must fight for their lives — and their humanity — in a collapsing society.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/ng3cMtxYKt1OSQYqFlnKWnVsqNO.jpg"
  },
  {
    "id": 48,
    "title": "The Rookie",
    "platform": "Disney+ Hotstar",
    "genre": "Police, Drama",
    "year": 2018,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 5,
    "episodes": 98,
    "runtime": "75h",
    "popularity": 84,
    "imdbRating": 8,
    "mustwatch": false,
    "tags": [
      "rookie cop",
      "LAPD",
      "second chance",
      "action",
      "crime"
    ],
    "description": "A 40-year-old man joins the LAPD as a rookie, proving it's never too late to chase your dream — or face danger head-on.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/bL1mwXDnH5fCxqc4S2n40hoVyoe.jpg"
  },
  {
    "id": 49,
    "title": "The Peripheral",
    "platform": "Prime Video",
    "genre": "Sci-Fi, Thriller",
    "year": 2022,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 8,
    "runtime": "8h",
    "popularity": 80,
    "imdbRating": 7.6,
    "mustwatch": false,
    "tags": [
      "future",
      "technology",
      "virtual reality",
      "murder",
      "conspiracy"
    ],
    "description": "A young woman playing advanced virtual reality games uncovers a connection to a dark future and a deadly conspiracy.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/2e5NNQu9B1fXBNllRj8fzysCguP.jpg"
  },
  {
    "id": 50,
    "title": "Arcane",
    "platform": "Netflix",
    "genre": "Animation, Action",
    "year": 2021,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 9,
    "runtime": "7h",
    "popularity": 96,
    "imdbRating": 9,
    "mustwatch": true,
    "tags": [
      "League of Legends",
      "sisters",
      "Piltover",
      "Zaun",
      "magic"
    ],
    "description": "Two sisters in a divided city find themselves on opposite sides of a war over arcane magic — a thrilling tale of power and family.",
    "isNew": true,
    "posterUrl": "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg"
  },
  {
    "id": 51,
    "title": "Squid Game",
    "platform": "Netflix",
    "genre": "Survival, Thriller",
    "year": 2021,
    "language": "Korean",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 9,
    "runtime": "8h",
    "popularity": 99,
    "imdbRating": 8,
    "mustwatch": false,
    "tags": [
      "dystopia",
      "money",
      "games",
      "survival",
      "debt"
    ],
    "description": "Hundreds of cash-strapped players accept an invitation to compete in children's games for a massive prize, with deadly stakes.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg"
  },
  {
    "id": 52,
    "title": "Sex Education",
    "platform": "Netflix",
    "genre": "Comedy, Drama",
    "year": 2019,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 4,
    "episodes": 32,
    "runtime": "25h",
    "popularity": 88,
    "imdbRating": 8.3,
    "mustwatch": false,
    "tags": [
      "high school",
      "sex therapy",
      "friendship",
      "romance"
    ],
    "description": "A high school student with an overbearing sex therapist mother starts his own sex advice clinic at school, with hilarious and heartfelt results.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/bc3bmTdnoKcRuO9xdQKgAbB7Y9Z.jpg"
  },
  {
    "id": 53,
    "title": "Money Heist",
    "platform": "Netflix",
    "genre": "Crime, Thriller",
    "year": 2017,
    "language": "Spanish",
    "hindiDubbed": true,
    "seasons": 5,
    "episodes": 41,
    "runtime": "40h",
    "popularity": 97,
    "imdbRating": 8.2,
    "mustwatch": false,
    "tags": [
      "heist",
      "professor",
      "Spain",
      "red jumpsuit",
      "money"
    ],
    "description": "A criminal mastermind orchestrates the biggest heists in history — a group of robbers with code names, a plan, and a whole lot of drama.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg"
  },
  {
    "id": 54,
    "title": "Chucky",
    "platform": "Prime Video",
    "genre": "Horror, Mystery",
    "year": 2021,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 3,
    "episodes": 24,
    "runtime": "18h",
    "popularity": 80,
    "imdbRating": 7.4,
    "mustwatch": false,
    "tags": [
      "killer doll",
      "teenagers",
      "supernatural",
      "80s",
      "gothic"
    ],
    "description": "A vintage Chucky doll turns up at a suburban yard sale, throwing a peaceful town into chaos as a series of gruesome murders begin.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/7KbhQpg6OV2o58SoulRbEtK9HYT.jpg"
  },
  {
    "id": 55,
    "title": "Gen V",
    "platform": "Prime Video",
    "genre": "Superhero, Satire",
    "year": 2023,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 1,
    "episodes": 8,
    "runtime": "8h",
    "popularity": 85,
    "imdbRating": 7.9,
    "mustwatch": false,
    "tags": [
      "college",
      "superheroes",
      "spin-off",
      "satire",
      "bloody"
    ],
    "description": "In a college for young superheroes, gifted students put their moral boundaries to the test, competing for the top ranks and a spot in The Seven.",
    "isNew": true,
    "posterUrl": "https://image.tmdb.org/t/p/w500/tEv842Nd5uMSavURG4aQO1pNtst.jpg"
  },
  {
    "id": 56,
    "title": "Invincible",
    "platform": "Prime Video",
    "genre": "Superhero, Animation",
    "year": 2021,
    "language": "English",
    "hindiDubbed": true,
    "seasons": 2,
    "episodes": 16,
    "runtime": "14h",
    "popularity": 91,
    "imdbRating": 8.7,
    "mustwatch": false,
    "tags": [
      "teen",
      "powers",
      "superheroes",
      "betrayal",
      "bloody"
    ],
    "description": "The son of the world's most powerful superhero grapples with his father's legacy and his own developing powers, revealing a dark truth.",
    "posterUrl": "https://image.tmdb.org/t/p/w500/jBn4LWlgdsf6xIUYhYBwpctBVsj.jpg"
  }
];
