const englishWatchlist = [
  {
    id: 1,
    title: "Breaking Bad",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2008,
    language: "English",
    hindiDubbed: true,
    seasons: 5,
    episodes: 62,
    runtime: "50h",
    popularity: 99,
    imdbRating: 9.5,
    tags: ["meth", "teacher", "transformation", "cartel", "iconic"],
    description: "A high school chemistry teacher turns to meth production after a cancer diagnosis, changing his life — and the criminal world — forever."
  },
  {
    id: 2,
    title: "Better Call Saul",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2015,
    language: "English",
    hindiDubbed: true,
    seasons: 6,
    episodes: 63,
    runtime: "55h",
    popularity: 98,
    imdbRating: 8.9,
    tags: ["lawyer", "prequel", "ethics", "Breaking Bad", "corruption"],
    description: "Before Saul Goodman represented criminals, he was Jimmy McGill — a clever underdog navigating law, morality, and identity."
  },
  {
    id: 3,
    title: "Stranger Things",
    platform: "Netflix",
    genre: "Sci-Fi Horror",
    year: 2016,
    language: "English",
    hindiDubbed: true,
    seasons: 4,
    episodes: 34,
    runtime: "30h",
    popularity: 98,
    imdbRating: 8.7,
    tags: ["supernatural", "80s", "kids", "demogorgon", "alternate dimension"],
    description: "A group of kids uncovers a secret government experiment and befriends a girl with supernatural powers while searching for their missing friend."
  },
  {
    id: 4,
    title: "The Queen's Gambit",
    platform: "Netflix",
    genre: "Drama",
    year: 2020,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 7,
    runtime: "6h",
    popularity: 93,
    imdbRating: 8.6,
    tags: ["chess", "genius", "orphan", "addiction", "girl power"],
    description: "An orphan chess prodigy rises to global stardom while facing addiction, loneliness, and the constraints of a male-dominated game."
  },
  {
    id: 5,
    title: "Wednesday",
    platform: "Netflix",
    genre: "Supernatural Mystery",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 92,
    imdbRating: 8.1,
    tags: ["gothic", "academy", "detective", "teen", "quirky"],
    description: "Wednesday Addams joins Nevermore Academy and uncovers a monstrous mystery while mastering her psychic abilities."
  },
  {
    id: 6,
    title: "The Night Agent",
    platform: "Netflix",
    genre: "Political Thriller",
    year: 2023,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 10,
    runtime: "8h",
    popularity: 88,
    imdbRating: 7.5,
    tags: ["FBI", "White House", "conspiracy", "emergency line", "danger"],
    description: "A low-level FBI agent gets a cryptic call from the White House basement hotline — dragging him into a deadly conspiracy."
  },
  {
    id: 7,
    title: "Lupin",
    platform: "Netflix",
    genre: "Heist Mystery",
    year: 2021,
    language: "French",
    hindiDubbed: true,
    seasons: 3,
    episodes: 17,
    runtime: "14h",
    popularity: 91,
    imdbRating: 7.5,
    tags: ["gentleman thief", "revenge", "Paris", "disguise", "justice"],
    description: "Inspired by Arsène Lupin, a clever thief orchestrates elaborate heists to avenge his father’s framing — charming the public and fooling the elite."
  },
  {
    id: 8,
    title: "The Boys",
    platform: "Prime Video",
    genre: "Superhero Satire",
    year: 2019,
    language: "English",
    hindiDubbed: true,
    seasons: 3,
    episodes: 24,
    runtime: "22h",
    popularity: 94,
    imdbRating: 8.7,
    tags: ["satire", "antihero", "violence", "superpowers", "conspiracy"],
    description: "A group of vigilantes take down corrupt superheroes who abuse their fame and power under a corporate regime."
  },
  {
    id: 9,
    title: "The Last of Us",
    platform: "HBO Max",
    genre: "Post-Apocalyptic Drama",
    year: 2023,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 9,
    runtime: "9h",
    popularity: 97,
    imdbRating: 8.9,
    tags: ["zombie", "fungus", "road trip", "emotion", "survival"],
    description: "A hardened smuggler escorts a girl immune to a fungal apocalypse across a devastated America while bonding along the way."
  },
  {
    id: 10,
    title: "Reacher",
    platform: "Prime Video",
    genre: "Action Thriller",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 2,
    episodes: 16,
    runtime: "13h",
    popularity: 88,
    imdbRating: 8.1,
    tags: ["ex-military", "investigation", "small town", "brutal", "justice"],
    description: "Jack Reacher rolls into a quiet town — only to uncover corruption, murder, and secrets he can't walk away from."
  },
  {
    id: 11,
    title: "The Lincoln Lawyer",
    platform: "Netflix",
    genre: "Legal Drama",
    year: 2022,
    language: "English",
    hindiDubbed: true,
    seasons: 2,
    episodes: 20,
    runtime: "18h",
    popularity: 87,
    imdbRating: 7.7,
    tags: ["defense lawyer", "cases", "Los Angeles", "justice", "court"],
    description: "A charismatic defense lawyer takes cases from the back of his Lincoln — navigating morality, crime, and courtroom showdowns in L.A."
  },
  {
    id: 12,
    title: "Game of Thrones",
    platform: "HBO Max",
    genre: "Epic Fantasy",
    year: 2011,
    language: "English",
    hindiDubbed: true,
    seasons: 8,
    episodes: 73,
    runtime: "70h",
    popularity: 99,
    imdbRating: 9.2,
    tags: ["dragons", "throne", "betrayal", "winter", "war"],
    description: "Noble families wage war over the Iron Throne in a medieval world where dragons return, alliances crumble, and winter always looms."
  },
  {
    id: 13,
    title: "The Gentlemen",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2024,
    language: "English",
    hindiDubbed: true,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 86,
    imdbRating: 7.8,
    tags: ["weed empire", "inheritance", "gangsters", "UK", "violence"],
    description: "When an English aristocrat inherits a cannabis empire, he’s dragged into underworld rivalries, betrayals, and bloodshed."
  },
  {
    id: 14,
    title: "The Witcher",
    platform: "Netflix",
    genre: "Fantasy",
    year: 2019,
    language: "English",
    hindiDubbed: true,
    seasons: 3,
    episodes: 24,
    runtime: "20h",
    popularity: 91,
    imdbRating: 8.1,
    tags: ["witcher", "magic", "monster hunter", "prophecy", "swordplay"],
    description: "Geralt of Rivia, a monster hunter for hire, struggles to find his place in a world where people can be more wicked than beasts."