const recommendedHindiSeries = [
  {
    id: 1,
    title: "Scam 1992",
    platform: "Sony LIV",
    genre: "Crime / Biopic / Finance",
    year: 2020,
    popularity: 97,
    seasons: 1,
    episodes: 10,
    runtime: "50 min",
    language: "Hindi",
    ref: "H1"
  },
  {
    id: 2,
    title: "Aspirants",
    platform: "TVF / YouTube",
    genre: "Drama / Motivation / UPSC",
    year: 2021,
    popularity: 95,
    seasons: 1,
    episodes: 5,
    runtime: "45 min",
    language: "Hindi",
    ref: "H2"
  },
  {
    id: 3,
    title: "Paatal Lok",
    platform: "Amazon Prime Video",
    genre: "Crime / Mystery / Thriller",
    year: 2020,
    popularity: 93,
    seasons: 1,
    episodes: 9,
    runtime: "45 min",
    language: "Hindi",
    ref: "H3"
  },
  {
    id: 4,
    title: "The Family Man",
    platform: "Amazon Prime Video",
    genre: "Action / Spy / Drama",
    year: 2019,
    popularity: 92,
    seasons: 2,
    episodes: 19,
    runtime: "40 min",
    language: "Hindi",
    ref: "H4"
  },
  {
    id: 5,
    title: "Kota Factory",
    platform: "TVF / Netflix",
    genre: "Drama / Youth / Education",
    year: 2019,
    popularity: 94,
    seasons: 2,
    episodes: 10,
    runtime: "45 min",
    language: "Hindi",
    ref: "H5"
  },
  {
    id: 6,
    title: "Rocket Boys",
    platform: "Sony LIV",
    genre: "Biopic / Historical / Drama",
    year: 2022,
    popularity: 89,
    seasons: 2,
    episodes: 16,
    runtime: "45 min",
    language: "Hindi",
    ref: "H6"
  },
  {
    id: 7,
    title: "Gullak",
    platform: "TVF / Sony LIV",
    genre: "Slice of Life / Family / Comedy",
    year: 2019,
    popularity: 91,
    seasons: 3,
    episodes: 15,
    runtime: "30 min",
    language: "Hindi",
    ref: "H7"
  },
  {
    id: 8,
    title: "Delhi Crime",
    platform: "Netflix",
    genre: "Crime / Police Procedural / Drama",
    year: 2019,
    popularity: 90,
    seasons: 2,
    episodes: 12,
    runtime: "55 min",
    language: "Hindi",
    ref: "H8"
  },
  {
    id: 9,
    title: "Mirzapur",
    platform: "Amazon Prime Video",
    genre: "Crime / Action / Drama",
    year: 2018,
    popularity: 94,
    seasons: 2,
    episodes: 19,
    runtime: "50 min",
    language: "Hindi",
    ref: "H9"
  },
  {
    id: 10,
    title: "Made in Heaven",
    platform: "Amazon Prime Video",
    genre: "Drama / Romance / Social",
    year: 2019,
    popularity: 88,
    seasons: 2,
    episodes: 16,
    runtime: "50 min",
    language: "Hindi",
    ref: "H10"
  },
  {
    id: 11,
    title: "TVF Pitchers",
    platform: "TVF Play / ZEE5",
    genre: "Drama / Startups / Friendship",
    year: 2015,
    popularity: 90,
    seasons: 2,
    episodes: 11,
    runtime: "45 min",
    language: "Hindi",
    ref: "H11"
  },
  {
    id: 12,
    title: "Special Ops",
    platform: "Hotstar",
    genre: "Spy / Thriller / Action",
    year: 2020,
    popularity: 88,
    seasons: 1,
    episodes: 8,
    runtime: "50 min",
    language: "Hindi",
    ref: "H12"
  },
  {
    id: 13,
    title: "Jubilee",
    platform: "Amazon Prime Video",
    genre: "Historical / Drama / Bollywood",
    year: 2023,
    popularity: 87,
    seasons: 1,
    episodes: 10,
    runtime: "55 min",
    language: "Hindi",
    ref: "H13"
  },
  {
    id: 14,
    title: "Panchayat",
    platform: "Amazon Prime Video",
    genre: "Comedy / Rural / Slice of Life",
    year: 2020,
    popularity: 96,
    seasons: 2,
    episodes: 16,
    runtime: "35 min",
    language: "Hindi",
    ref: "H14"
  },
  {
    id: 15,
    title: "Rana Naidu",
    platform: "Netflix",
    genre: "Crime / Family / Adaptation",
    year: 2023,
    popularity: 85,
    seasons: 1,
    episodes: 10,
    runtime: "45 min",
    language: "Hindi",
    ref: "H15"
  },
  {
    id: 16,
    title: "Criminal Justice",
    platform: "Disney+ Hotstar",
    genre: "Crime / Legal / Psychological",
    year: 2019,
    popularity: 89,
    seasons: 3,
    episodes: 19,
    runtime: "45 min",
    language: "Hindi",
    ref: "H16"
  },
  {
    id: 17,
    title: "Asur",
    platform: "Voot / JioCinema",
    genre: "Crime / Mythology / Thriller",
    year: 2020,
    popularity: 93,
    seasons: 2,
    episodes: 16,
    runtime: "45 min",
    language: "Hindi",
    ref: "H17"
  },
  {
    id: 18,
    title: "The Great Indian Murder",
    platform: "Hotstar",
    genre: "Mystery / Political / Drama",
    year: 2022,
    popularity: 83,
    seasons: 1,
    episodes: 9,
    runtime: "50 min",
    language: "Hindi",
    ref: "H18"
  },
  {
    id: 19,
    title: "Taaza Khabar",
    platform: "Disney+ Hotstar",
    genre: "Fantasy / Dark Humor / Social",
    year: 2023,
    popularity: 84,
    seasons: 1,
    episodes: 6,
    runtime: "30 min",
    language: "Hindi",
    ref: "H19"
  },
  {
    id: 20,
    title: "Bandish Bandits",
    platform: "Amazon Prime Video",
    genre: "Music / Romance / Classical",
    year: 2020,
    popularity: 89,
    seasons: 1,
    episodes: 10,
    runtime: "40 min",
    language: "Hindi",
    ref: "H20"
  },
{
    id: 21,
    title: "Grahan",
    platform: "Disney+ Hotstar",
    genre: "Historical / Crime / Drama",
    year: 2021,
    popularity: 86,
    seasons: 1,
    episodes: 8,
    runtime: "45 min",
    language: "Hindi",
    ref: "H21"
  },
  {
    id: 22,
    title: "Mumbai Diaries 26/11",
    platform: "Amazon Prime Video",
    genre: "Medical / Thriller / Historical",
    year: 2021,
    popularity: 88,
    seasons: 1,
    episodes: 8,
    runtime: "45 min",
    language: "Hindi",
    ref: "H22"
  },
  {
    id: 23,
    title: "Hostel Daze",
    platform: "Amazon Prime Video",
    genre: "Comedy / College / Youth",
    year: 2019,
    popularity: 85,
    seasons: 4,
    episodes: 20,
    runtime: "30 min",
    language: "Hindi",
    ref: "H23"
  },
  {
    id: 24,
    title: "Ray",
    platform: "Netflix",
    genre: "Anthology / Psychological / Thriller",
    year: 2021,
    popularity: 83,
    seasons: 1,
    episodes: 4,
    runtime: "55 min",
    language: "Hindi",
    ref: "H24"
  },
  {
    id: 25,
    title: "Jehanabad – Of Love & War",
    platform: "Sony LIV",
    genre: "Romance / Crime / Political",
    year: 2023,
    popularity: 82,
    seasons: 1,
    episodes: 10,
    runtime: "45 min",
    language: "Hindi",
    ref: "H25"
  },
  {
    id: 26,
    title: "Suzhal: The Vortex (Hindi Dub)",
    platform: "Amazon Prime Video",
    genre: "Crime / Mystery / Tamil Original",
    year: 2022,
    popularity: 84,
    seasons: 1,
    episodes: 8,
    runtime: "50 min",
    language: "Hindi Dubbed",
    ref: "H26"
  },
  {
    id: 27,
    title: "13 Mussoorie",
    platform: "Voot",
    genre: "Crime / Mystery / Thriller",
    year: 2018,
    popularity: 80,
    seasons: 1,
    episodes: 13,
    runtime: "40 min",
    language: "Hindi",
    ref: "H27"
  },
  {
    id: 28,
    title: "Illegal",
    platform: "Voot / JioCinema",
    genre: "Legal / Drama / Thriller",
    year: 2020,
    popularity: 83,
    seasons: 2,
    episodes: 16,
    runtime: "45 min",
    language: "Hindi",
    ref: "H28"
  },
  {
    id: 29,
    title: "College Romance",
    platform: "Sony LIV",
    genre: "Comedy / Romance / Campus",
    year: 2018,
    popularity: 87,
    seasons: 4,
    episodes: 20,
    runtime: "30 min",
    language: "Hindi",
    ref: "H29"
  },
  {
    id: 30,
    title: "Undekhi",
    platform: "Sony LIV",
    genre: "Crime / Thriller / Small Town",
    year: 2020,
    popularity: 85,
    seasons: 2,
    episodes: 18,
    runtime: "45 min",
    language: "Hindi",
    ref: "H30"
  },
  {
    id: 31,
    title: "Bhaukaal",
    platform: "MX Player",
    genre: "Crime / Action / Biopic",
    year: 2020,
    popularity: 84,
    seasons: 2,
    episodes: 20,
    runtime: "35 min",
    language: "Hindi",
    ref: "H31"
  },
  {
    id: 32,
    title: "Avrodh: The Siege Within",
    platform: "Sony LIV",
    genre: "Military / Action / Political",
    year: 2020,
    popularity: 82,
    seasons: 2,
    episodes: 17,
    runtime: "40 min",
    language: "Hindi",
    ref: "H32"
  },
  {
    id: 33,
    title: "The Broken News",
    platform: "ZEE5",
    genre: "Media / Political / Drama",
    year: 2022,
    popularity: 81,
    seasons: 2,
    episodes: 16,
    runtime: "40 min",
    language: "Hindi",
    ref: "H33"
  },
  {
    id: 34,
    title: "Tandav",
    platform: "Amazon Prime Video",
    genre: "Political / Thriller / Drama",
    year: 2021,
    popularity: 80,
    seasons: 1,
    episodes: 9,
    runtime: "45 min",
    language: "Hindi",
    ref: "H34"
  },
  {
    id: 35,
    title: "Kaafir",
    platform: "ZEE5",
    genre: "Drama / Humanity / Border Conflict",
    year: 2019,
    popularity: 86,
    seasons: 1,
    episodes: 8,
    runtime: "40 min",
    language: "Hindi",
    ref: "H35"
  },
  {
    id: 36,
    title: "London Files",
    platform: "Voot / JioCinema",
    genre: "Crime / Mystery / Drama",
    year: 2022,
    popularity: 79,
    seasons: 1,
    episodes: 6,
    runtime: "40 min",
    language: "Hindi",
    ref: "H36"
  },
  {
    id: 37,
    title: "Breathe: Into the Shadows",
    platform: "Amazon Prime Video",
    genre: "Psychological / Crime / Drama",
    year: 2020,
    popularity: 83,
    seasons: 2,
    episodes: 20,
    runtime: "45 min",
    language: "Hindi",
    ref: "H37"
  },
  {
    id: 38,
    title: "Hello Mini",
    platform: "MX Player",
    genre: "Thriller / Psychological / Romance",
    year: 2019,
    popularity: 81,
    seasons: 3,
    episodes: 35,
    runtime: "25 min",
    language: "Hindi",
    ref: "H38"
  },
  {
    id: 39,
    title: "Abhay",
    platform: "ZEE5",
    genre: "Crime / Police / Thriller",
    year: 2019,
    popularity: 84,
    seasons: 3,
    episodes: 24,
    runtime: "45 min",
    language: "Hindi",
    ref: "H39"
  },
  {
    id: 40,
    title: "Aranyak",
    platform: "Netflix",
    genre: "Mystery / Police Procedural / Thriller",
    year: 2021,
    popularity: 82,
    seasons: 1,
    episodes: 8,
    runtime: "45 min",
    language: "Hindi",
    ref: "H40"
  }
];