const hindiWatchlist = [
  {
    id: 1,
    title: "Sacred Games",
    platform: "Netflix",
    genre: "Crime Thriller",
    year: 2018,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 95,
    imdbRating: 8.5,
    description: "A troubled cop and a mysterious gangster unravel a deadly conspiracy that threatens Mumbai’s soul.",
    mustwatch: true
  },
  {
    id: 2,
    title: "Mirzapur",
    platform: "Amazon Prime Video",
    genre: "Action Crime",
    year: 2018,
    seasons: 3,
    episodes: 30,
    runtime: "25h",
    popularity: 92,
    imdbRating: 8.6,
    description: "Power, politics, and bloodshed collide in the lawless town of Mirzapur ruled by a ruthless mafia family.",
    mustwatch: true
  },
  {
    id: 3,
    title: "Paatal Lok",
    platform: "Amazon Prime Video",
    genre: "Crime Drama",
    year: 2020,
    seasons: 1,
    episodes: 9,
    runtime: "7h",
    popularity: 88,
    imdbRating: 8.0,
    description: "A cynical cop lands a high-profile case that leads him into the dark underbelly of Indian society.",
    mustwatch: false
  },
  {
    id: 4,
    title: "Asur",
    platform: "JioCinema",
    genre: "Mythological Thriller",
    year: 2020,
    seasons: 2,
    episodes: 16,
    runtime: "13h",
    popularity: 90,
    imdbRating: 8.4,
    description: "A forensic expert and a serial killer clash in a battle of intellect, rooted in ancient mythology.",
    mustwatch: true
  },
  {
    id: 5,
    title: "The Family Man",
    platform: "Amazon Prime Video",
    genre: "Spy Thriller",
    year: 2019,
    seasons: 2,
    episodes: 19,
    runtime: "15h",
    popularity: 94,
    imdbRating: 8.7,
    description: "A middle-class man secretly works as an intelligence officer while juggling family life and national threats.",
    mustwatch: true
  },
  {
    id: 6,
    title: "Delhi Crime",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2019,
    seasons: 2,
    episodes: 12,
    runtime: "10h",
    popularity: 89,
    imdbRating: 8.5,
    description: "Based on true events, this gripping series follows the Delhi Police’s investigation into a brutal crime.",
    mustwatch: false
  },
  {
    id: 7,
    title: "Aashram",
    platform: "MX Player",
    genre: "Crime Drama",
    year: 2020,
    seasons: 3,
    episodes: 28,
    runtime: "20h",
    popularity: 82,
    imdbRating: 8.1,
    description: "An exploration of a powerful godman’s secrets, deception, and the blind faith surrounding him.",
    mustwatch: false
  },
  {
    id: 8,
    title: "Rangbaaz",
    platform: "ZEE5",
    genre: "Crime Biography",
    year: 2018,
    seasons: 3,
    episodes: 24,
    runtime: "18h",
    popularity: 84,
    imdbRating: 8.0,
    description: "Inspired by real-life gangsters, this series traces the rise and fall of notorious criminals in India.",
    mustwatch: false
  },
  {
    id: 9,
    title: "Breathe",
    platform: "Amazon Prime Video",
    genre: "Psychological Thriller",
    year: 2018,
    seasons: 2,
    episodes: 20,
    runtime: "16h",
    popularity: 86,
    imdbRating: 7.9,
    description: "A desperate father turns to dark choices to save his son, triggering a deadly game of cat and mouse.",
    mustwatch: false
  },
  {
    id: 10,
    title: "Undekhi",
    platform: "SonyLIV",
    genre: "Crime Thriller",
    year: 2020,
    seasons: 2,
    episodes: 18,
    runtime: "14h",
    popularity: 83,
    imdbRating: 7.8,
    description: "A murder at a wedding sets off a chain of cover-ups and chaos in this gritty tale of power and justice.",
    mustwatch: false
  },
  {
    id: 11,
    title: "Special OPS",
    platform: "Disney+ Hotstar",
    genre: "Spy Thriller",
    year: 2020,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 87,
    imdbRating: 8.6,
    description: "An elite RAW agent chases down the architect behind terror attacks over 19 years across continents.",
    mustwatch: false
  },
  {
    id: 12,
    title: "Criminal Justice",
    platform: "Disney+ Hotstar",
    genre: "Legal Drama",
    year: 2019,
    seasons: 3,
    episodes: 21,
    runtime: "16h",
    popularity: 85,
    imdbRating: 8.4,
    description: "A man’s life spirals after a single night. This courtroom-crime drama explores justice, guilt, and redemption.",
    mustwatch: true
  },
  {
    id: 13,
    title: "Kota Factory",
    platform: "Netflix",
    genre: "Teen Drama",
    year: 2019,
    seasons: 2,
    episodes: 10,
    runtime: "8h",
    popularity: 91,
    imdbRating: 9.0,
    description: "A monochrome masterpiece capturing the competitive pressure and friendship among IIT aspirants in Kota.",
    mustwatch: true
  },
  {
    id: 14,
    title: "Aarya",
    platform: "Disney+ Hotstar",
    genre: "Crime Thriller",
    year: 2020,
    seasons: 3,
    episodes: 24,
    runtime: "19h",
    popularity: 88,
    imdbRating: 7.9,
    description: "When her family is threatened, a mother must embrace the underworld her late husband left behind.",
    mustwatch: false
  },
  {
    id: 15,
    title: "Hostages",
    platform: "Disney+ Hotstar",
    genre: "Thriller",
    year: 2019,
    seasons: 2,
    episodes: 22,
    runtime: "17h",
    popularity: 80,
    imdbRating: 6.9,
    description: "A surgeon’s family is taken hostage, and she must make an impossible decision to save them.",
    mustwatch: false
  },
  {
    id: 16,
    title: "JL50",
    platform: "SonyLIV",
    genre: "Sci-Fi Mystery",
    year: 2020,
    seasons: 1,
    episodes: 4,
    runtime: "3h",
    popularity: 75,
    imdbRating: 7.5,
    description: "A plane lost for 35 years crashes again — unraveling a time travel mystery buried in secrecy.",
    mustwatch: false
  },
  {
    id: 17,
    title: "Bhaukaal",
    platform: "MX Player",
    genre: "Crime Action",
    year: 2020,
    seasons: 2,
    episodes: 20,
    runtime: "14h",
    popularity: 81,
    imdbRating: 7.9,
    description: "Inspired by real events, an IPS officer takes on a city held hostage by two powerful crime syndicates.",
    mustwatch: false
  },
  {
    id: 18,
    title: "Panchayat",
    platform: "Amazon Prime Video",
    genre: "Comedy Drama",
    year: 2020,
    seasons: 3,
    episodes: 24,
    runtime: "20h",
    popularity: 96,
    imdbRating: 9.1,
    description: "An engineering graduate takes a government posting in a village — and gets a hilarious crash course in life.",
    mustwatch: true
  },
  {
    id: 19,
    title: "Inside Edge",
    platform: "Amazon Prime Video",
    genre: "Sports Drama",
    year: 2017,
    seasons: 3,
    episodes: 30,
    runtime: "24h",
    popularity: 77,
    imdbRating: 7.6,
    description: "Set in a T20 cricket league, this drama exposes the power play and corruption behind the sport’s spotlight.",
    mustwatch: false
  },
  {
    id: 20,
    title: "Grahan",
    platform: "Disney+ Hotstar",
    genre: "Period Drama",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 79,
    imdbRating: 8.4,
    description: "While investigating 1984 riots, a police officer discovers a haunting connection to her father’s past.",
    mustwatch: false
  },
  {
    id: 21,
    title: "TVF Pitchers",
    platform: "ZEE5",
    genre: "Drama",
    year: 2015,
    seasons: 2,
    episodes: 10,
    runtime: "7h",
    popularity: 90,
    imdbRating: 9.1,
    description: "Four friends quit their jobs to launch a startup, learning business, friendship, and grit the hard way.",
    mustwatch: true
  },
  {
    id: 22,
    title: "Rocket Boys",
    platform: "SonyLIV",
    genre: "Historical Drama",
    year: 2022,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 85,
    imdbRating: 8.9,
    description: "The inspiring journey of Homi Bhabha and Vikram Sarabhai as they shape India’s nuclear and space ambitions.",
    mustwatch: false
  },
  {
    id: 23,
    title: "Avrodh: The Siege Within",
    platform: "SonyLIV",
    genre: "Military Thriller",
    year: 2020,
    seasons: 2,
    episodes: 17,
    runtime: "12h",
    popularity: 78,
    imdbRating: 7.5,
    description: "Based on true events, this gripping military drama recounts India’s surgical strikes after the Uri attack.",
    mustwatch: false
  },
  {
    id: 24,
    title: "Tabbar",
    platform: "SonyLIV",
    genre: "Family Crime Drama",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 82,
    imdbRating: 8.3,
    description: "A retired cop does the unthinkable to protect his family when a mistake spirals into chaos.",
    mustwatch: false
  },
  {
    id: 25,
    title: "Maharani",
    platform: "SonyLIV",
    genre: "Political Drama",
    year: 2021,
    seasons: 3,
    episodes: 30,
    runtime: "23h",
    popularity: 80,
    imdbRating: 7.8,
    description: "A woman rises from the shadows to become CM of Bihar — facing caste, corruption, and patriarchy head-on.",
    mustwatch: false
  },
  {
    id: 26,
    title: "Scam 1992: The Harshad Mehta Story",
    platform: "SonyLIV",
    genre: "Financial Thriller",
    year: 2020,
    seasons: 1,
    episodes: 10,
    runtime: "9h",
    popularity: 97,
    imdbRating: 9.3,
    description: "The meteoric rise and dramatic downfall of Harshad Mehta — the stock market genius who shook India’s economy.",
    mustwatch: true
  },
  {
    id: 27,
    title: "Trial by Fire",
    platform: "Netflix",
    genre: "True Crime Drama",
    year: 2023,
    seasons: 1,
    episodes: 7,
    runtime: "5h",
    popularity: 78,
    imdbRating: 8.0,
    description: "Based on the Uphaar tragedy, a couple fights the system for justice after losing their children in a cinema fire.",
    mustwatch: false
  },
  {
    id: 28,
    title: "Jeet Ki Zid",
    platform: "ZEE5",
    genre: "Military Biopic",
    year: 2021,
    seasons: 1,
    episodes: 7,
    runtime: "6h",
    popularity: 76,
    imdbRating: 8.3,
    description: "Inspired by Kargil war hero Major Deep Singh, who overcame paralysis to reclaim his identity and honor.",
    mustwatch: false
  },
  {
    id: 29,
    title: "The Broken News",
    platform: "ZEE5",
    genre: "Newsroom Drama",
    year: 2022,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 74,
    imdbRating: 7.4,
    description: "Two rival newsrooms — one idealistic, one aggressive — battle over journalism, ethics, and TRP-driven truth.",
    mustwatch: false
  },
  {
    id: 30,
    title: "Gullak",
    platform: "SonyLIV",
    genre: "Slice of Life",
    year: 2019,
    seasons: 4,
    episodes: 20,
    runtime: "11h",
    popularity: 89,
    imdbRating: 9.1,
    description: "A heartwarming tale of a small-town Mishra family — steeped in nostalgia, humor, and middle-class magic.",
    mustwatch: true
  },
  {
    id: 31,
    title: "Scoop",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2023,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 84,
    imdbRating: 7.8,
    description: "A journalist’s life spirals after she’s accused of murdering a fellow reporter — inspired by true events.",
    mustwatch: false
  },
  {
    id: 32,
    title: "Mumbai Diaries 26/11",
    platform: "Amazon Prime Video",
    genre: "Medical Thriller",
    year: 2021,
    seasons: 2,
    episodes: 16,
    runtime: "13h",
    popularity: 82,
    imdbRating: 8.0,
    description: "Doctors and first responders navigate chaos during the 26/11 Mumbai attacks in this gripping hospital drama.",
    mustwatch: false
  },
  {
    id: 33,
    title: "Taj: Divided by Blood",
    platform: "ZEE5",
    genre: "Historical Drama",
    year: 2023,
    seasons: 2,
    episodes: 20,
    runtime: "16h",
    popularity: 79,
    imdbRating: 7.7,
    description: "A Mughal emperor’s succession battle turns into a brutal saga of ambition, betrayal, and bloodlines.",
    mustwatch: false
  },
  {
    id: 34,
    title: "Saas Bahu Aur Flamingo",
    platform: "Disney+ Hotstar",
    genre: "Action Crime",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 76,
    imdbRating: 7.6,
    description: "A matriarch runs a drug empire with her daughters-in-law — fierce, violent, and unapologetically wild.",
    mustwatch: false
  },
  {
    id: 35,
    title: "Kaala",
    platform: "Disney+ Hotstar",
    genre: "Financial Crime Thriller",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 74,
    imdbRating: 7.5,
    description: "A gritty tale of reverse hawala, black money, and a relentless officer chasing the truth.",
    mustwatch: false
  },
  {
    id: 36,
    title: "Sultan of Delhi",
    platform: "Disney+ Hotstar",
    genre: "Period Crime Drama",
    year: 2023,
    seasons: 1,
    episodes: 9,
    runtime: "7h",
    popularity: 72,
    imdbRating: 7.2,
    description: "A young man rises through the underworld ranks in post-Partition Delhi — but power always comes at a price.",
    mustwatch: false
  },
  {
    id: 37,
    title: "Poacher",
    platform: "Amazon Prime Video",
    genre: "Eco-Crime Thriller",
    year: 2024,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 80,
    imdbRating: 8.2,
    description: "Inspired by true events, a forest officer uncovers a massive ivory poaching ring in Kerala’s jungles.",
    mustwatch: false
  },
  {
    id: 38,
    title: "Bard of Blood",
    platform: "Netflix",
    genre: "Spy Thriller",
    year: 2019,
    seasons: 1,
    episodes: 7,
    runtime: "5.5h",
    popularity: 70,
    imdbRating: 6.9,
    description: "A former RAW agent, now a professor, is called back into action to save four Indian intelligence officers held hostage by the Taliban.",
    mustwatch: false
  },
  {
    id: 39,
    title: "She",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2020,
    seasons: 2,
    episodes: 14,
    runtime: "10h",
    popularity: 68,
    imdbRating: 6.4,
    description: "An unassuming female constable goes undercover to bust a drug gang, navigating a dangerous world and discovering her own power.",
    mustwatch: false
  },
  {
    id: 40,
    title: "Aranyak",
    platform: "Netflix",
    genre: "Crime Thriller",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 75,
    imdbRating: 7.8,
    description: "When a foreign teenage tourist disappears in a misty Himalayan town, a local cop unearths a forgotten myth and a web of crimes.",
    mustwatch: false
  },
  {
    id: 41,
    title: "Chakravyuh",
    platform: "MX Player",
    genre: "Cyber Crime Thriller",
    year: 2020,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 65,
    imdbRating: 6.0,
    description: "A tech genius is found dead, leading a cybercrime investigator into a dark maze of hackers, digital secrets, and conspiracy.",
    mustwatch: false
  },
  {
    id: 42,
    title: "Jamtara - Sabka Number Ayega",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2020,
    seasons: 2,
    episodes: 18,
    runtime: "12h",
    popularity: 77,
    imdbRating: 7.3,
    description: "Based on true events, a group of young men run a successful phishing operation from a remote village, but soon face political and criminal threats.",
    mustwatch: false
  },
  {
    id: 43,
    title: "Ray",
    platform: "Netflix",
    genre: "Drama Anthology",
    year: 2021,
    seasons: 1,
    episodes: 4,
    runtime: "6h",
    popularity: 72,
    imdbRating: 7.1,
    description: "Four gripping stories inspired by the works of legendary filmmaker Satyajit Ray, exploring themes of ego, revenge, and betrayal.",
    mustwatch: false
  },
  {
    id: 44,
    title: "Dahaad",
    platform: "Amazon Prime Video",
    genre: "Crime Thriller",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 81,
    imdbRating: 7.8,
    description: "A female police officer investigates a series of mysterious disappearances in a small town, uncovering a serial killer preying on women.",
    mustwatch: false
  },
  {
    id: 45,
    title: "Farzi",
    platform: "Amazon Prime Video",
    genre: "Crime Thriller",
    year: 2023,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 93,
    imdbRating: 8.4,
    description: "A brilliant con artist enters the world of high-stakes counterfeit money, pursued by a fiery task force officer.",
    mustwatch: true
  },
  {
    id: 46,
    title: "Aspirants",
    platform: "YouTube/TVF",
    genre: "Drama",
    year: 2021,
    seasons: 1,
    episodes: 5,
    runtime: "4h",
    popularity: 94,
    imdbRating: 9.2,
    description: "The story of three friends navigating the challenges of cracking the UPSC civil services exam in Delhi's Old Rajinder Nagar.",
    mustwatch: true
  },
  {
    id: 47,
    title: "Made In Heaven",
    platform: "Amazon Prime Video",
    genre: "Drama",
    year: 2019,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 87,
    imdbRating: 8.3,
    description: "Follows the lives of two wedding planners in Delhi, exploring the social fabric, traditions, and hidden truths behind big Indian weddings.",
    mustwatch: false
  },
  {
    id: 48,
    title: "Kohrra",
    platform: "Netflix",
    genre: "Crime Thriller",
    year: 2023,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 80,
    imdbRating: 8.0,
    description: "A dark and atmospheric crime series where two police officers uncover deceit and secrets while investigating a murder in Punjab.",
    mustwatch: false
  },
  {
    id: 49,
    title: "Apharan",
    platform: "Alt Balaji / ZEE5",
    genre: "Action Thriller",
    year: 2018,
    seasons: 3,
    episodes: 30,
    runtime: "25h",
    popularity: 75,
    imdbRating: 8.2,
    description: "A senior inspector is blackmailed into kidnapping a girl, leading to a tangled web of lies, deceit, and unexpected twists.",
    mustwatch: false
  },
  {
    id: 50,
    title: "Bandish Bandits",
    platform: "Amazon Prime Video",
    genre: "Musical Drama",
    year: 2020,
    seasons: 1,
    episodes: 10,
    runtime: "8h",
    popularity: 78,
    imdbRating: 7.9,
    description: "A classical music prodigy and a pop star from different worlds embark on a musical journey, facing challenges and falling in love.",
    mustwatch: false
  },
  {
    id: 51,
    title: "Yeh Meri Family",
    platform: "Netflix / TVF Play",
    genre: "Family Drama",
    year: 2018,
    seasons: 2,
    episodes: 14,
    runtime: "9h",
    popularity: 85,
    imdbRating: 9.0,
    description: "A nostalgic journey through the eyes of a 12-year-old, depicting the everyday life, joys, and challenges of a middle-class Indian family in the 90s.",
    mustwatch: true
  },
  {
    id: 52,
    title: "Chacha Vidhayak Hain Humare",
    platform: "Amazon Prime Video",
    genre: "Comedy",
    year: 2018,
    seasons: 3,
    episodes: 24,
    runtime: "10h",
    popularity: 70,
    imdbRating: 7.9,
    description: "Ronny, a jobless young man, pretends to be a local MLA's nephew, leading to hilarious misadventures and satirical takes on small-town politics.",
    mustwatch: false
  },
  {
    id: 53,
    title: "Sunflower",
    platform: "ZEE5",
    genre: "Black Comedy, Crime",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 73,
    imdbRating: 7.0,
    description: "A peculiar murder mystery unfolds in the 'Sunflower' housing society, with the quirky resident Sonu Singh becoming the prime suspect.",
    mustwatch: false
  },
  {
    id: 54,
    title: "Taaza Khabar",
    platform: "Disney+ Hotstar",
    genre: "Comedy Drama, Fantasy",
    year: 2023,
    seasons: 1,
    episodes: 6,
    runtime: "4h",
    popularity: 70,
    imdbRating: 7.7,
    description: "A sanitation worker gains a magical ability to foresee future news headlines, changing his life and the lives of those around him.",
    mustwatch: true
  },
  {
    id: 55,
    title: "Murder In Mahim",
    platform: "JioCinema",
    genre: "Crime, Mystery",
    year: 2024,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 78,
    imdbRating: 7.5,
    description: "Based on the book by Jerry Pinto, this series delves into a chilling murder investigation in Mumbai's Mahim area, uncovering dark secrets.",
    mustwatch: false
  },
  {
    id: 56,
    title: "Heeramandi: The Diamond Bazaar",
    platform: "Netflix",
    genre: "Period Drama, Historical",
    year: 2024,
    seasons: 1,
    episodes: 8,
    runtime: "8h",
    popularity: 88,
    imdbRating: 7.0,
    description: "Set in the Lahore's Heeramandi during the Indian independence movement, it explores the lives of courtesans and their struggles for freedom and dignity.",
    mustwatch: false
  },
  {
    id: 57,
    title: "Gyaarah Gyaarah",
    platform: "ZEE5",
    genre: "Sci-Fi, Mystery",
    year: 2024,
    seasons: 1,
    episodes: 8,
    runtime: "6h",
    popularity: 70,
    imdbRating: 7.0,
    description: "A sci-fi thriller spanning three different timelines, intertwining the investigation of a serial killer across decades.",
    mustwatch: false
  },
  {
    id: 58,
    title: "Citadel: Honey Bunny",
    platform: "Amazon Prime Video",
    genre: "Spy Thriller, Action",
    year: 2024,
    seasons: 1,
    episodes: 7,
    runtime: "6h",
    popularity: 80,
    imdbRating: 7.5,
    description: "The Indian installment of the global Citadel universe, a high-octane spy thriller with a blend of action, emotion, and espionage.",
    mustwatch: false
  },
  {
    id: 59,
    title: "Maamla Legal Hai",
    platform: "Netflix",
    genre: "Comedy, Legal",
    year: 2024,
    seasons: 1,
    episodes: 8,
    runtime: "5h",
    popularity: 82,
    imdbRating: 7.8,
    description: "A quirky comedy set in a district court, following the chaotic yet endearing lives of lawyers and their unconventional cases.",
    mustwatch: true
  },
  {
    id: 60,
    title: "Shekhar Home",
    platform: "JioCinema",
    genre: "Crime, Anthology",
    year: 2024,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 65,
    imdbRating: 6.8,
    description: "An anthology series featuring gripping crime stories, each episode presenting a new mystery from different corners of society.",
    mustwatch: false
  },
  {
    id: 61,
    title: "The Great Indian Kapil Show",
    platform: "Netflix",
    genre: "Comedy, Talk Show",
    year: 2024,
    seasons: 1,
    episodes: 10,
    runtime: "8h",
    popularity: 85,
    imdbRating: 6.5,
    description: "Kapil Sharma returns with his signature comedy and celebrity interviews, bringing laughter and entertainment to a global audience.",
    mustwatch: false
  }
];
