const hindiWatchlist = [
  {
    id: 1,
    title: "Sacred Games",
    platform: "Netflix",
    genre: "Crime Thriller",
    year: 2018,
    seasons: 2,
    episodes: 16,
    runtime: "12h",
    popularity: 95,
    imdbRating: 8.5,
    description: "A troubled cop and a mysterious gangster unravel a deadly conspiracy that threatens Mumbai’s soul.",
    mustwatch: true
  },
  {
    id: 2,
    title: "Mirzapur",
    platform: "Amazon Prime Video",
    genre: "Action Crime",
    year: 2018,
    seasons: 3,
    episodes: 30,
    runtime: "25h",
    popularity: 92,
    imdbRating: 8.6,
    description: "Power, politics, and bloodshed collide in the lawless town of Mirzapur ruled by a ruthless mafia family.",
    mustwatch: true
  },
  {
    id: 3,
    title: "Paatal Lok",
    platform: "Amazon Prime Video",
    genre: "Crime Drama",
    year: 2020,
    seasons: 1,
    episodes: 9,
    runtime: "7h",
    popularity: 88,
    imdbRating: 8.0,
    description: "A cynical cop lands a high-profile case that leads him into the dark underbelly of Indian society.",
    mustwatch: false
  },
  {
    id: 4,
    title: "Asur",
    platform: "JioCinema",
    genre: "Mythological Thriller",
    year: 2020,
    seasons: 2,
    episodes: 16,
    runtime: "13h",
    popularity: 90,
    imdbRating: 8.4,
    description: "A forensic expert and a serial killer clash in a battle of intellect, rooted in ancient mythology.",
    mustwatch: false
  },
  {
    id: 5,
    title: "The Family Man",
    platform: "Amazon Prime Video",
    genre: "Spy Thriller",
    year: 2019,
    seasons: 2,
    episodes: 19,
    runtime: "15h",
    popularity: 94,
    imdbRating: 8.7,
    description: "A middle-class man secretly works as an intelligence officer while juggling family life and national threats.",
    mustwatch: true
  },
  {
    id: 6,
    title: "Delhi Crime",
    platform: "Netflix",
    genre: "Crime Drama",
    year: 2019,
    seasons: 2,
    episodes: 12,
    runtime: "10h",
    popularity: 89,
    imdbRating: 8.5,
    description: "Based on true events, this gripping series follows the Delhi Police’s investigation into a brutal crime.",
    mustwatch: false
  },
  {
    id: 7,
    title: "Aashram",
    platform: "MX Player",
    genre: "Crime Drama",
    year: 2020,
    seasons: 3,
    episodes: 28,
    runtime: "20h",
    popularity: 82,
    imdbRating: 8.1,
    description: "An exploration of a powerful godman’s secrets, deception, and the blind faith surrounding him.",
    mustwatch: false
  },
  {
    id: 8,
    title: "Rangbaaz",
    platform: "ZEE5",
    genre: "Crime Biography",
    year: 2018,
    seasons: 3,
    episodes: 24,
    runtime: "18h",
    popularity: 84,
    imdbRating: 8.0,
    description: "Inspired by real-life gangsters, this series traces the rise and fall of notorious criminals in India.",
    mustwatch: false
  },
  {
    id: 9,
    title: "Breathe",
    platform: "Amazon Prime Video",
    genre: "Psychological Thriller",
    year: 2018,
    seasons: 2,
    episodes: 20,
    runtime: "16h",
    popularity: 86,
    imdbRating: 7.9,
    description: "A desperate father turns to dark choices to save his son, triggering a deadly game of cat and mouse.",
    mustwatch: false
  },
  {
    id: 10,
    title: "Undekhi",
    platform: "SonyLIV",
    genre: "Crime Thriller",
    year: 2020,
    seasons: 2,
    episodes: 18,
    runtime: "14h",
    popularity: 83,
    imdbRating: 7.8,
    description: "A murder at a wedding sets off a chain of cover-ups and chaos in this gritty tale of power and justice.",
    mustwatch: false
  },
  {
    id: 11,
    title: "Special OPS",
    platform: "Disney+ Hotstar",
    genre: "Spy Thriller",
    year: 2020,
    seasons: 1,
    episodes: 8,
    runtime: "6.5h",
    popularity: 87,
    imdbRating: 8.6,
    description: "An elite RAW agent chases down the architect behind terror attacks over 19 years across continents.",
    mustwatch: false
  },
  {
    id: 12,
    title: "Criminal Justice",
    platform: "Disney+ Hotstar",
    genre: "Legal Drama",
    year: 2019,
    seasons: 3,
    episodes: 21,
    runtime: "16h",
    popularity: 85,
    imdbRating: 8.4,
    description: "A man’s life spirals after a single night. This courtroom-crime drama explores justice, guilt, and redemption.",
    mustwatch: false
  },
  {
    id: 13,
    title: "Kota Factory",
    platform: "Netflix",
    genre: "Teen Drama",
    year: 2019,
    seasons: 2,
    episodes: 10,
    runtime: "8h",
    popularity: 91,
    imdbRating: 9.0,
    description: "A monochrome masterpiece capturing the competitive pressure and friendship among IIT aspirants in Kota.",
    mustwatch: true
  },
  {
    id: 14,
    title: "Aarya",
    platform: "Disney+ Hotstar",
    genre: "Crime Thriller",
    year: 2020,
    seasons: 3,
    episodes: 24,
    runtime: "19h",
    popularity: 88,
    imdbRating: 7.9,
    description: "When her family is threatened, a mother must embrace the underworld her late husband left behind.",
    mustwatch: false
  },
  {
    id: 15,
    title: "Hostages",
    platform: "Disney+ Hotstar",
    genre: "Thriller",
    year: 2019,
    seasons: 2,
    episodes: 22,
    runtime: "17h",
    popularity: 80,
    imdbRating: 6.9,
    description: "A surgeon’s family is taken hostage, and she must make an impossible decision to save them.",
    mustwatch: false
  },
  {
    id: 16,
    title: "JL50",
    platform: "SonyLIV",
    genre: "Sci-Fi Mystery",
    year: 2020,
    seasons: 1,
    episodes: 4,
    runtime: "3h",
    popularity: 75,
    imdbRating: 7.5,
    description: "A plane lost for 35 years crashes again — unraveling a time travel mystery buried in secrecy.",
    mustwatch: false
  },
  {
    id: 17,
    title: "Bhaukaal",
    platform: "MX Player",
    genre: "Crime Action",
    year: 2020,
    seasons: 2,
    episodes: 20,
    runtime: "14h",
    popularity: 81,
    imdbRating: 7.9,
    description: "Inspired by real events, an IPS officer takes on a city held hostage by two powerful crime syndicates.",
    mustwatch: false
  },
  {
    id: 18,
    title: "Panchayat",
    platform: "Amazon Prime Video",
    genre: "Comedy Drama",
    year: 2020,
    seasons: 3,
    episodes: 24,
    runtime: "20h",
    popularity: 96,
    imdbRating: 9.1,
    description: "An engineering graduate takes a government posting in a village — and gets a hilarious crash course in life.",
    mustwatch: true
  },
