const koreanWatchlist = [
  {
    id: 1,
    title: "Mouse",
    platform: "tvN / Viki",
    genre: "Psychological Thriller",
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 92,
    imdbRating: 8.7,
    hindiDubbed: false,
    description: "A rookie cop becomes entangled in a string of serial murders — but who’s hunting whom in this intense mind game?"
  },
  {
    id: 2,
    title: "Hellbound",
    platform: "Netflix",
    genre: "Supernatural Thriller",
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 89,
    imdbRating: 6.6,
    hindiDubbed: true,
    description: "Mysterious creatures sentence people to hell — triggering chaos and cults in this dark commentary on justice and faith."
  },
  {
    id: 3,
    title: "My Mister",
    platform: "Netflix",
    genre: "Slice of Life Drama",
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 94,
    imdbRating: 9.1,
    hindiDubbed: false,
    description: "A weary middle-aged man and a stoic young woman find strength and solace in each other’s quiet pain."
  },
  {
    id: 4,
    title: "Stranger (Secret Forest)",
    platform: "Netflix",
    genre: "Crime Mystery",
    year: 2017,
    seasons: 2,
    episodes: 32,
    runtime: "24h",
    popularity: 91,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A prosecutor who feels no emotion and a principled detective team up to uncover systemic corruption."
  },
  {
    id: 5,
    title: "Crash Landing on You",
    platform: "Netflix",
    genre: "Romantic Drama",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 98,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A South Korean heiress crash-lands in North Korea and finds love, danger, and destiny on the other side of the DMZ."
  },
  {
    id: 6,
    title: "Kingdom",
    platform: "Netflix",
    genre: "Historical Zombie Thriller",
    year: 2019,
    seasons: 2,
    episodes: 13,
    runtime: "12h",
    popularity: 93,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In medieval Joseon, a mysterious plague unleashes the undead — and only a crown prince can stop it."
  },
  {
    id: 7,
    title: "Extraordinary Attorney Woo",
    platform: "Netflix",
    genre: "Legal Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 95,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A brilliant young attorney on the autism spectrum tackles complex cases with logic, empathy, and whale facts."
  },
  {
    id: 8,
    title: "Hospital Playlist",
    platform: "tvN / Netflix",
    genre: "Medical Slice of Life",
    year: 2020,
    seasons: 2,
    episodes: 24,
    runtime: "28h",
    popularity: 96,
    imdbRating: 8.8,
    hindiDubbed: false,
    description: "Five doctors, lifelong friends, and their patients share joy, loss, and music in this warmhearted medical drama."
  },
  {
    id: 9,
    title: "Flower of Evil",
    platform: "tvN / Viki / Airtel Xstream",
    genre: "Crime Melodrama",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 90,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A loving husband hides a twisted past — but when his detective wife starts investigating, can love survive suspicion?"
  },
  {
    id: 10,
    title: "Signal",
    platform: "tvN / Netflix",
    genre: "Crime Sci-Fi",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 88,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A mysterious walkie-talkie connects two detectives across time to solve cold cases and stop future crimes."
  },
  {
    id: 11,
    title: "The Glory",
    platform: "Netflix",
    genre: "Revenge Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 97,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A woman scarred by brutal school bullying crafts a decades-long revenge plot against her tormentors."
  },
  {
    id: 12,
    title: "D.P.",
    platform: "Netflix",
    genre: "Military / Social Drama",
    year: 2021,
    seasons: 2,
    episodes: 12,
    runtime: "10h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Two army privates in the Deserter Pursuit Unit chase runaway soldiers — and confront the trauma inside military ranks."
  },
  {
    id: 13,
    title: "My Name",
    platform: "Netflix",
    genre: "Action Noir",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 86,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "After her father's death, a woman enters the underworld and the police force — to exact her bloody revenge."
  },
  {
    id: 14,
    title: "Beyond Evil",
    platform: "JTBC / Netflix",
    genre: "Psychological Crime",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 84,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Two detectives with dark pasts chase a serial killer — but what if the monster is one of them?"
  },
  {
    id: 15,
    title: "Through the Darkness",
    platform: "SBS / Viki",
    genre: "True Crime Psychological",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: false,
    description: "Based on real events, Korea’s first profiler enters the twisted minds of serial killers to stop them before they strike again."
  },
  {
    id: 16,
    title: "The Devil Judge",
    platform: "tvN / Viki",
    genre: "Legal Dystopia",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 85,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In a dystopian Korea, a charismatic judge turns the courtroom into reality TV — delivering justice his own way amid dark secrets."
  },
  {
    id: 17,
    title: "Vincenzo",
    platform: "tvN / Netflix",
    genre: "Mafia Satire / Action",
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "24h",
    popularity: 98,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A Korean-Italian mafia consigliere returns to Seoul for hidden gold — but ends up fighting corporate villains with fire and flair."
  },
  {
    id: 18,
    title: "Queenmaker",
    platform: "Netflix",
    genre: "Political Drama",
    year: 2023,
    seasons: 1,
    episodes: 11,
    runtime: "10h",
    popularity: 87,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A shrewd fixer transforms a humble lawyer into a political force — setting the stage for justice, revenge, and ruthless strategy."
  },
  {
    id: 19,
    title: "Revenant",
    platform: "SBS / Disney+",
    genre: "Occult Thriller",
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 82,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A young woman’s body is haunted by a vengeful spirit, unraveling a trail of suicides and folklore tied to her family’s past."
  },
  {
    id: 20,
    title: "Big Mouth",
    platform: "MBC / Disney+",
    genre: "Legal Mystery Thriller",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 90,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Framed as Korea’s most infamous con artist, a naive lawyer must outwit a criminal empire — or become the monster they fear."
  },
  {
    id: 21,
    title: "One Ordinary Day",
    platform: "Coupang Play / Viu",
    genre: "Crime Courtroom Thriller",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 81,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "After waking beside a murdered woman, a college student becomes the prime suspect — in a system that assumes guilt over truth."
  },
  {
    id: 22,
    title: "The Good Bad Mother",
    platform: "JTBC / Netflix",
    genre: "Healing / Family Drama",
    year: 2023,
    seasons: 1,
    episodes: 14,
    runtime: "13h",
    popularity: 89,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "When a coldhearted prosecutor regresses to a childlike state, his stern mother is given a second chance at motherhood."
  },
  {
    id: 23,
    title: "My Liberation Notes",
    platform: "JTBC / Netflix",
    genre: "Existential Slice of Life",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 85,
    imdbRating: 8.4,
    hindiDubbed: false,
    description: "Three siblings and a silent stranger yearn to escape their empty routines — in search of meaning, freedom, and something to worship."
  },
  {
    id: 24,
    title: "Juvenile Justice",
    platform: "Netflix",
    genre: "Courtroom Drama",
    year: 2022,
    seasons: 1,
    episodes: 10,
    runtime: "9h",
    popularity: 84,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A no-nonsense judge who despises youth offenders is forced to confront the root of violence in a broken legal system."
  },
  {
    id: 25,
    title: "Queen of Tears",
    platform: "tvN / Netflix",
    genre: "Romance / Legal Melodrama",
    year: 2024,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 98,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A powerhouse couple on the verge of collapse must fight for each other — as love, betrayal, and legacy hang in the balance."
  },
  {
    id: 26,
    title: "Watcher",
    platform: "OCN / Viki",
    genre: "Psychological Crime / Corruption",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 79,
    imdbRating: 8.0,
    hindiDubbed: false,
    description: "An anti-corruption team digs into the rot inside law enforcement — but every revelation risks destroying their own morality."
  },
  {
    id: 27,
    title: "Live",
    platform: "tvN / Netflix",
    genre: "Police / Slice of Life",
    year: 2018,
    seasons: 1,
    episodes: 18,
    runtime: "18h",
    popularity: 83,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Through daily beatdowns and bureaucratic hurdles, frontline officers try to uphold justice — while protecting their own hearts."
  },
  {
    id: 28,
    title: "Mr. Sunshine",
    platform: "tvN / Netflix",
    genre: "Historical Epic / Romance",
    year: 2018,
    seasons: 1,
    episodes: 24,
    runtime: "26h",
    popularity: 94,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A Korean-born U.S. marine returns to his occupied homeland — and falls for a noblewoman igniting a rebellion for freedom."
  },
  {
    id: 29,
    title: "Arthdal Chronicles",
    platform: "tvN / Netflix",
    genre: "Mythical Historical Fantasy",
    year: 2019,
    seasons: 2,
    episodes: 30,
    runtime: "30h",
    popularity: 88,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In the ancient land of Arth, tribes clash for power, prophecy, and survival — as a blue-blooded outcast rises to challenge fate."
  },
  {
    id: 30,
    title: "Goblin (Guardian: The Lonely and Great God)",
    platform: "tvN / MX Player / Airtel Xstream",
    genre: "Fantasy Romance",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "20h",
    popularity: 97,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "An immortal goblin seeks a human bride to end his cursed life — but destiny has other plans when love enters the equation."
  },
  {
    id: 31,
    title: "Alchemy of Souls",
    platform: "tvN / Netflix",
    genre: "Fantasy / Historical Romance",
    year: 2022,
    seasons: 2,
    episodes: 30,
    runtime: "30h",
    popularity: 91,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "In a kingdom where souls can shift bodies, a powerful sorceress trapped in a weak form trains a nobleman to defy fate and reclaim power."
  },
  {
    id: 32,
    title: "Mr. Queen",
    platform: "tvN / Netflix",
    genre: "Historical Comedy / Body Swap",
    year: 2020,
    seasons: 1,
    episodes: 20,
    runtime: "22h",
    popularity: 93,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A modern male chef wakes up in the body of a Joseon-era queen — and must navigate palace politics, royal secrets, and gender chaos."
  },
  {
    id: 33,
    title: "The Red Sleeve",
    platform: "MBC / Viki",
    genre: "Historical Romance",
    year: 2021,
    seasons: 1,
    episodes: 17,
    runtime: "18h",
    popularity: 86,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A court lady values freedom over love — but fate binds her to a crown prince torn between duty and desire."
  },
  {
    id: 34,
    title: "Moon Lovers: Scarlet Heart Ryeo",
    platform: "SBS / Viki",
    genre: "Historical Fantasy / Tragedy",
    year: 2016,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 95,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A 21st-century woman is transported to Goryeo-era Korea — where she’s caught in a deadly game of love, power, and princes."
  },
  {
    id: 35,
    title: "Rookie Historian Goo Hae-ryung",
    platform: "MBC / Netflix",
    genre: "Historical / Feminist Romance",
    year: 2019,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 82,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "In a time when women were forbidden to write history, one bold scholar challenges the system — and the heart of a secret prince."
  },
  {
    id: 36,
    title: "Joseon Attorney",
    platform: "MBC / Amazon miniTV / WeTV",
    genre: "Historical Legal Drama",
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 80,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A cunning lawyer uses the law for revenge — but finds justice, redemption, and love in the courtroom of Joseon."
  },
  {
    id: 37,
    title: "Queen for Seven Days",
    platform: "KBS2 / Netflix",
    genre: "Historical Melodrama",
    year: 2017,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 81,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A noblewoman becomes queen — only to be dethroned after seven days. A tragic love story unfolds between power and sacrifice."
  },
  {
    id: 38,
    title: "Under the Queen’s Umbrella",
    platform: "tvN / Netflix",
    genre: "Historical / Political Family Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 88,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A fierce queen mother must whip her unruly sons into shape — before palace rivals steal the throne from under her umbrella."
  },
  {
    id: 39,
    title: "The Crowned Clown",
    platform: "tvN / Netflix",
    genre: "Historical Thriller",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 84,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "To escape assassination, a paranoid king replaces himself with a lookalike clown — but the imposter may rule better than the real monarch."
  },
  {
    id: 40,
    title: "100 Days My Prince",
    platform: "tvN / Netflix",
    genre: "Historical Romance / Comedy",
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 87,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "After losing his memory, a crown prince ends up living as a commoner — and unknowingly marries the kingdom’s oldest bachelorette."
  },
  {
    id: 41,
    title: "Love in the Moonlight",
    platform: "KBS2 / Viki",
    genre: "Historical Romance / Youth",
    year: 2016,
    seasons: 1,
    episodes: 18,
    runtime: "18h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A cross-dressing girl becomes a eunuch in the royal palace — and captures the heart of a lonely crown prince."
  },
  {
    id: 42,
    title: "The King’s Affection",
    platform: "KBS2 / Netflix",
    genre: "Historical Romance / Gender Swap",
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 90,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "After her twin brother’s death, a princess disguises herself as the crown prince — hiding her identity while ruling the kingdom."
  },
  {
    id: 43,
    title: "Sweet Home",
    platform: "Netflix",
    genre: "Apocalyptic Horror / Monster",
    year: 2020,
    seasons: 3,
    episodes: 30,
    runtime: "30h",
    popularity: 95,
    imdbRating: 7.3,
    hindiDubbed: true,
    description: "In a world where humans turn into monsters driven by desire, a reclusive teen and his neighbors fight to survive inside a cursed apartment complex."
  },
  {
    id: 44,
    title: "The Uncanny Counter",
    platform: "OCN / Netflix",
    genre: "Supernatural Action",
    year: 2020,
    seasons: 2,
    episodes: 28,
    runtime: "28h",
    popularity: 90,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "By day, they run a noodle shop. By night, they hunt evil spirits — using superpowers to protect the living from the dead."
  },
  {
    id: 45,
    title: "Happiness",
    platform: "tvN / Netflix",
    genre: "Apocalyptic Thriller",
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 88,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A mysterious virus turns people into rage-filled monsters. Trapped in a high-rise, residents must survive both infection and each other."
  },
  {
    id: 46,
    title: "All of Us Are Dead",
    platform: "Netflix",
    genre: "Zombie Survival / Teen Horror",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "13h",
    popularity: 96,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A zombie virus outbreak traps high school students inside their school — and survival becomes a brutal lesson in fear, loyalty, and sacrifice."
  },
  {
    id: 47,
    title: "Duty After School",
    platform: "TVING / Viki",
    genre: "Sci-Fi Military Thriller",
    year: 2023,
    seasons: 1,
    episodes: 10,
    runtime: "11h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "When alien spheres invade Earth, high school seniors are drafted into military service — and must fight for survival before graduation."
  },
  {
    id: 48,
    title: "Dark Hole",
    platform: "OCN / Viki / DramaLine",
    genre: "Horror / Mystery Thriller",
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 78,
    imdbRating: 7.0,
    hindiDubbed: true,
    description: "A black fog from a sinkhole turns people into mutants. Survivors must uncover the truth behind the outbreak — or be consumed by it."
  },
  {
    id: 49,
    title: "Island",
    platform: "TVING / Amazon Prime Video",
    genre: "Fantasy / Demon Hunter",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 85,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "On Jeju Island, a demon hunter, a priest, and a reincarnated goddess must unite to stop an ancient evil from awakening."
  },
  {
    id: 50,
    title: "Bulgasal: Immortal Souls",
    platform: "tvN / Netflix",
    genre: "Fantasy / Revenge Thriller",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 83,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Cursed with immortality, a man seeks revenge on the woman who stole his soul — across 600 years of blood, betrayal, and rebirth."
  },
{
    id: 51,
    title: "Sisyphus: The Myth",
    platform: "JTBC / Netflix",
    genre: "Sci-Fi / Time Travel Thriller",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 80,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "A genius engineer meets a warrior from the future — and together they must stop a time-travel conspiracy that threatens humanity."
  },
  {
    id: 52,
    title: "SF8",
    platform: "MBC / PlayFlix / Tata Play Binge",
    genre: "Sci-Fi Anthology",
    year: 2020,
    seasons: 1,
    episodes: 8,
    runtime: "8h",
    popularity: 75,
    imdbRating: 7.2,
    hindiDubbed: true,
    description: "Eight standalone sci-fi stories explore AI, VR, robots, and dystopia — Korea’s answer to Black Mirror, now dubbed in Hindi."
  },
  {
    id: 53,
    title: "Alice",
    platform: "SBS / DramaLine / BiliBili",
    genre: "Sci-Fi / Time Travel Mystery",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 79,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "A detective discovers a time-travel agency called Alice — and uncovers secrets about his mother, his fate, and the future of time itself."
  },
  {
    id: 54,
    title: "Memories of the Alhambra",
    platform: "tvN / Netflix",
    genre: "AR Sci-Fi / Romance Thriller",
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 91,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A CEO travels to Spain to find the creator of an AR game — but the line between game and reality begins to blur dangerously."
  },
  {
    id: 55,
    title: "The Silent Sea",
    platform: "Netflix",
    genre: "Sci-Fi / Space Thriller",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "8h",
    popularity: 86,
    imdbRating: 6.9,
    hindiDubbed: true,
    description: "On a mission to the moon, astronauts must retrieve a mysterious sample from an abandoned base — but something deadly awaits inside."
  },
  {
    id: 56,
    title: "Dr. Brain",
    platform: "Apple TV+ / Tata Play Binge",
    genre: "Sci-Fi / Psychological Thriller",
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "6h",
    popularity: 77,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "A brilliant neuroscientist syncs with the brains of the dead to solve his family’s tragedy — but the memories he inherits may destroy him."
  },
  {
    id: 57,
    title: "Twenty-Five Twenty-One",
    platform: "tvN / Netflix",
    genre: "Romance / Coming-of-Age",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "20h",
    popularity: 97,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A teen fencer and a struggling reporter fall in love during Korea’s IMF crisis — a nostalgic tale of dreams, heartbreak, and growing up."
  },
  {
    id: 58,
    title: "Our Beloved Summer",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Slice of Life",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 90,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Years after filming a viral high school documentary, two ex-lovers are forced to reunite — and maybe rewrite their ending."
  },
  {
    id: 59,
    title: "Business Proposal",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Workplace",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 95,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A food researcher goes on a blind date pretending to be her friend — only to discover her date is her company’s CEO."
  },
  {
    id: 60,
    title: "True Beauty",
    platform: "tvN / Viki / Crunchyroll",
    genre: "Romantic Comedy / High School",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 92,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A bullied teen masters makeup to reinvent herself — but two boys threaten to expose her secret and steal her heart."
  },
  {
    id: 61,
    title: "Nevertheless",
    platform: "JTBC / Netflix",
    genre: "Romance / Youth Drama",
    year: 2021,
    seasons: 1,
    episodes: 10,
    runtime: "10h",
    popularity: 88,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "A love cynic and a flirtatious art student enter a complicated relationship — where attraction doesn’t always mean love."
  },
  {
    id: 62,
    title: "Love Alarm",
    platform: "Netflix",
    genre: "Romance / Sci-Fi",
    year: 2019,
    seasons: 2,
    episodes: 14,
    runtime: "14h",
    popularity: 89,
    imdbRating: 6.8,
    hindiDubbed: true,
    description: "In a world where an app alerts you if someone nearby likes you, a high school girl is caught in a love triangle — and a digital dilemma."
  },
  {
    id: 63,
    title: "Crash Course in Romance",
    platform: "tvN / Netflix",
    genre: "Romantic Comedy / Family Drama",
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 91,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A banchan shop owner and a celebrity math tutor collide in Korea’s cutthroat education world — and discover love in the chaos."
  },
  {
    id: 64,
    title: "See You in My 19th Life",
    platform: "tvN / Netflix",
    genre: "Fantasy Romance",
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "13h",
    popularity: 87,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "A woman who remembers all her past lives sets out to reconnect with her childhood love — now grown and grieving her former self."
  },
  {
    id: 65,
    title: "King the Land",
    platform: "JTBC / Netflix",
    genre: "Romantic Comedy / Chaebol Romance",
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 93,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "A hotel heir who hates fake smiles falls for the sunniest concierge in the building — and sparks fly in the land of luxury."
  },
  {
    id: 66,
    title: "My Demon",
    platform: "SBS / Netflix",
    genre: "Fantasy Romance / Supernatural",
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 90,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A cold-hearted heiress and a demon who loses his powers are forced into a contract marriage — and fall into a love neither expected."
  },
{
    id: 67,
    title: "Castaway Diva",
    platform: "tvN / Netflix",
    genre: "Romance / Music / Slice of Life",
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "13h",
    popularity: 85,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Fifteen years after being stranded on an island, a once-aspiring singer returns to chase her dream — and confront the past she left behind."
  },
  {
    id: 68,
    title: "Doona!",
    platform: "Netflix",
    genre: "Romance / Idol Drama",
    year: 2023,
    seasons: 1,
    episodes: 9,
    runtime: "9h",
    popularity: 88,
    imdbRating: 7.2,
    hindiDubbed: true,
    description: "A college student moves into a sharehouse — only to discover his roommate is a retired K-pop idol with secrets and scars."
  },
  {
    id: 69,
    title: "Daily Dose of Sunshine",
    platform: "Netflix",
    genre: "Medical / Healing Drama",
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "13h",
    popularity: 86,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A kind-hearted psychiatric nurse brings light to her patients’ lives — while battling her own mental health struggles with courage and care."
  },
  {
    id: 70,
    title: "Behind Your Touch",
    platform: "JTBC / Netflix",
    genre: "Supernatural / Crime Comedy",
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 84,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A psychic vet and a hot-headed detective team up to solve small-town crimes — but a serial killer case tests their powers and partnership."
  },
  {
    id: 71,
    title: "Reborn Rich",
    platform: "JTBC / Disney+ / Viki",
    genre: "Fantasy Revenge / Corporate Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 95,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "After being betrayed and killed by the chaebol family he served, a loyal employee is reborn as their youngest son — and plots a hostile takeover from within."
  },
  {
    id: 72,
    title: "The Veil",
    platform: "MBC / Viki / BiliBili",
    genre: "Spy Thriller / Action",
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "13h",
    popularity: 84,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A top NIS agent returns after a year-long disappearance — with no memory and a mission to expose the traitor who destroyed him."
  },
  {
    id: 73,
    title: "Taxi Driver",
    platform: "SBS / Netflix / Amazon miniTV",
    genre: "Action / Vigilante Justice",
    year: 2021,
    seasons: 2,
    episodes: 32,
    runtime: "32h",
    popularity: 92,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A secret organization disguised as a taxi service delivers justice for victims failed by the law — one ride at a time."
  },
  {
    id: 74,
    title: "Boys Over Flowers",
    platform: "Netflix",
    genre: "Romantic Comedy",
    year: 2009,
    seasons: 1,
    episodes: 25,
    runtime: "20h",
    popularity: 87,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A spirited girl enters an elite high school and clashes with a powerful group of boys known as F4 — sparking chaos and romance."
  },
  {
    id: 75,
    title: "Healer",
    platform: "KBS2 / Netflix",
    genre: "Romantic Thriller / Action",
    year: 2014,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 90,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A night courier with secret skills, a passionate reporter, and a hidden conspiracy collide in this genre-bending thriller."
  },
  {
    id: 76,
    title: "Pinocchio",
    platform: "SBS / Viki",
    genre: "Romantic Legal Drama",
    year: 2014,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 85,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A rookie reporter with a syndrome that forces her to hiccup when she lies teams up with a mysterious man to expose corrupt media."
  },
  {
    id: 77,
    title: "Strong Woman Do Bong Soon",
    platform: "JTBC / Netflix",
    genre: "Romantic Comedy / Superhero",
    year: 2017,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 93,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A petite but superpowered woman gets hired as a bodyguard by a quirky game CEO — and finds love, danger, and herself."
  },
  {
    id: 78,
    title: "Weightlifting Fairy Kim Bok-joo",
    platform: "MBC / Viki",
    genre: "Romantic Comedy / Sports",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 89,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A talented weightlifter meets a charming swimmer, and together they navigate youth, competition, and first love."
  },
  {
    id: 79,
    title: "You're Beautiful",
    platform: "SBS / Viki",
    genre: "Romantic Comedy / Idol Drama",
    year: 2009,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 82,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A nun-in-training disguises herself as her twin brother to join a boy band — but secrets and sparkles fly behind the scenes."
  },
  {
    id: 80,
    title: "School 2017",
    platform: "KBS2 / Viki",
    genre: "High School / Youth Drama",
    year: 2017,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 83,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "Students struggle against corruption, bullying, and academic pressure in a school system that rewards obedience over passion."
  },
  {
    id: 81,
    title: "Cheese in the Trap",
    platform: "tvN / Netflix",
    genre: "Romantic Mystery / Campus Drama",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 84,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "An introverted student falls for a charming senior who may be hiding a manipulative streak — and tangled secrets follow."
  },
  {
    id: 82,
    title: "Dream High",
    platform: "KBS2 / Viki",
    genre: "Idol Romance / Youth Drama",
    year: 2011,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 88,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A group of aspiring idols chase fame, friendship, and first love at Korea’s top performing arts high school."
  },
{
    id: 83,
    title: "Itaewon Class",
    platform: "JTBC / Netflix",
    genre: "Youth / Revenge Drama",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 94,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "An ex-con with a moral compass opens a street bar in Itaewon — challenging a food empire while gathering a misfit family."
  },
  {
    id: 84,
    title: "Kill Me, Heal Me",
    platform: "MBC / Viki",
    genre: "Psychological Romance",
    year: 2015,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 88,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "A man with seven personalities and a secret past meets a psychiatrist who may help — or unravel everything."
  },
  {
    id: 85,
    title: "Sky Castle",
    platform: "JTBC / Netflix",
    genre: "Satirical Thriller / Family Drama",
    year: 2018,
    seasons: 1,
    episodes: 20,
    runtime: "21h",
    popularity: 97,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Elite families spiral into obsession over success — and secrets start bleeding through the Ivy League curtains."
  },
  {
    id: 86,
    title: "The Heirs",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Teen Drama",
    year: 2013,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 91,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A poor girl gets tangled in the elite world of chaebols — and becomes the heart of a glittery love triangle."
  },
  {
    id: 87,
    title: "Faith (The Great Doctor)",
    platform: "SBS / Viki",
    genre: "Historical Fantasy Romance",
    year: 2012,
    seasons: 1,
    episodes: 24,
    runtime: "26h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A Goryeo warrior kidnaps a modern surgeon to save his queen — and fate throws them into war, love, and history."
  },
  {
    id: 88,
    title: "While You Were Sleeping",
    platform: "SBS / Netflix",
    genre: "Fantasy Legal Thriller",
    year: 2017,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 90,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "A woman who dreams of future tragedies joins forces with a prosecutor — but can they rewrite fate before it strikes?"
  },
  {
    id: 89,
    title: "Legend of the Blue Sea",
    platform: "SBS / Viki",
    genre: "Fantasy Romance / Mermaid",
    year: 2016,
    seasons: 1,
    episodes: 20,
    runtime: "21h",
    popularity: 89,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A mermaid from the Joseon era reunites with her modern soulmate — and memories of a past love resurface in magical ways."
  },
  {
    id: 90,
    title: "W: Two Worlds",
    platform: "MBC / Netflix",
    genre: "Fantasy / Sci-Fi Romance",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 92,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A surgeon enters the world of a webtoon — where the lines between fiction and reality blur with deadly stakes."
  },
  {
    id: 91,
    title: "Tunnel",
    platform: "OCN / Viki",
    genre: "Crime / Time Travel Thriller",
    year: 2017,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 87,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "While chasing a killer in 1986, a detective finds himself in 2016 — where the crimes continue and the mystery deepens."
  },
  {
    id: 92,
    title: "Kairos",
    platform: "MBC / Viki",
    genre: "Time-Slip Thriller",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 81,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A man whose daughter disappears and a woman searching for her mother connect across time — and unravel fate together."
  },
  {
    id: 93,
    title: "Hyena",
    platform: "SBS / Netflix",
    genre: "Legal Drama / Romance",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 85,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Two ruthless lawyers battle in court and in romance — chasing clients, fame, and each other’s hearts."
  },
  {
    id: 94,
    title: "It's Okay to Not Be Okay",
    platform: "tvN / Netflix",
    genre: "Healing Romance / Psychological",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 96,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A psychiatric caregiver and an antisocial fairytale author discover healing, love, and the courage to face childhood trauma."
  },
  {
    id: 95,
    title: "Law School",
    platform: "JTBC / Netflix",
    genre: "Legal Thriller / Mystery",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 84,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A professor is arrested for murder — and law students scramble to uncover the truth hidden in textbooks and testimonies."
  },
  {
    id: 96,
    title: "Doctor Stranger",
    platform: "SBS / Viki",
    genre: "Medical / Spy Drama",
    year: 2014,
    seasons: 1,
    episodes: 20,
    runtime: "22h",
    popularity: 86,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A brilliant surgeon trained in North Korea faces espionage, love, and sacrifice while trying to find his lost soulmate."
  },
  {
    id: 97,
    title: "Romance Is a Bonus Book",
    platform: "tvN / Netflix",
    genre: "Romantic Comedy / Publishing",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 88,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A talented editor and a struggling single mom reunite in the literary world — where second chances and love write their own chapters."
  },
  {
    id: 98,
    title: "The Master's Sun",
    platform: "SBS / Viki",
    genre: "Romantic Horror / Supernatural",
    year: 2013,
    seasons: 1,
    episodes: 17,
    runtime: "18h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A woman who sees ghosts meets a cold CEO who cancels out her visions — but their bond grows deeper than either expects."
  },
  {
    id: 99,
    title: "Business Proposal",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Workplace",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 95,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A food researcher goes on a blind date pretending to be her friend — only to discover her date is her company’s CEO."
  },
 {
    id: 100,
    title: "May I Help You",
    platform: "MBC / Viki",
    genre: "Fantasy Healing / Funeral Romance",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 82,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A funeral director who grants wishes of the dead teams up with a delivery man who carries mysterious burdens — and both start healing together."
  },
  {
    id: 101,
    title: "A Business Proposal",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 95,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "A blind date between a CEO and a woman impersonating her friend spirals into contract chaos — and unexpected romance."
  },
  {
    id: 102,
    title: "Forecasting Love and Weather",
    platform: "JTBC / Netflix",
    genre: "Romantic Drama / Workplace",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 83,
    imdbRating: 7.0,
    hindiDubbed: true,
    description: "At Korea’s national weather office, love is as unpredictable as the forecast — and romance heats up between two meteorologists."
  },
  {
    id: 103,
    title: "Hello Me!",
    platform: "KBS2 / Netflix",
    genre: "Fantasy / Self-Love Comedy",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 81,
    imdbRating: 7.3,
    hindiDubbed: true,
    description: "A 37-year-old woman meets her spirited 17-year-old self — and rediscovers dreams she had left behind."
  },
  {
    id: 104,
    title: "Sh**ting Stars",
    platform: "tvN / Netflix",
    genre: "Romantic Comedy / Celebrity Workplace",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 84,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A celebrity PR manager tangles with the actor she secretly dislikes — but love may be lurking behind sarcastic texts and old wounds."
  },
  {
    id: 105,
    title: "Love in Contract",
    platform: "tvN / Viki",
    genre: "Romantic Comedy / Mystery",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A professional contract wife juggles two husbands on different weekdays — but her emotions start breaking the rules."
  },
  {
    id: 106,
    title: "So I Married the Anti-Fan",
    platform: "Naver TV / Amazon Prime",
    genre: "Romantic Comedy / Idol Romance",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 83,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A fiery reporter becomes an idol’s involuntary housemate after a viral scandal — cue enemies-to-lovers antics and spark-stuffed chemistry."
  },
  {
    id: 107,
    title: "Find Me in Your Memory",
    platform: "MBC / Netflix",
    genre: "Romantic Drama / Psychological",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 81,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A news anchor with hyperthymesia — who remembers everything — meets a rising actress who’s forgotten her past."
  },
  {
    id: 108,
    title: "When the Camellia Blooms",
    platform: "KBS2 / Netflix",
    genre: "Romantic Thriller / Slice of Life",
    year: 2019,
    seasons: 1,
    episodes: 20,
    runtime: "21h",
    popularity: 92,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A single mom runs a bar in a sleepy town — and finds herself in the middle of a murder mystery and an unlikely love story."
  },
  {
    id: 109,
    title: "Angel's Last Mission: Love",
    platform: "KBS2 / Viki",
    genre: "Fantasy Romance / Ballet",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A mischievous angel must find true love for a cold-hearted ballerina — or vanish forever. But fate has other plans."
  },
  {
    id: 110,
    title: "Melting Me Softly",
    platform: "tvN / Viki",
    genre: "Sci-Fi Romance / Cryogenic Drama",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 78,
    imdbRating: 7.3,
    hindiDubbed: true,
    description: "Two people wake up 20 years after a cryogenic experiment gone wrong — and try to navigate a fast-changing world with slower emotions."
  },
  {
    id: 111,
    title: "My Roommate is a Gumiho",
    platform: "tvN / Netflix",
    genre: "Fantasy Romance / Supernatural Comedy",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 87,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A college student accidentally swallows a fox bead — now she’s living with a 999-year-old gumiho until he can retrieve it."
  },
  {
    id: 112,
    title: "The Tale of Nokdu",
    platform: "KBS2 / Viki",
    genre: "Historical Comedy / Gender Swap",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 84,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A man infiltrates a widow village disguised as a woman — and falls for a spirited young assassin training to avenge her past."
  },
  {
    id: 113,
    title: "Ruler: Master of the Mask",
    platform: "MBC / Viki",
    genre: "Historical Political Drama",
    year: 2017,
    seasons: 1,
    episodes: 40,
    runtime: "35h",
    popularity: 82,
    imdbRating: 7.6,
    hindiDubbed: true,
    description: "A masked crown prince fights against a corrupt water monopoly — and learns to rule with wisdom, love, and sacrifice."
  },
  {
    id: 114,
    title: "Shopping King Louie",
    platform: "MBC / Viki",
    genre: "Romantic Comedy / Amnesia",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 80,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "A sheltered chaebol with memory loss finds himself in the care of a countryside girl — love blooms through coupons and canned tuna."
  },
  {
    id: 115,
    title: "Oh My Venus",
    platform: "KBS2 / Netflix",
    genre: "Romantic Comedy / Fitness Healing",
    year: 2015,
    seasons: 1,
    episodes: 16,
    runtime: "17h",
    popularity: 85,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A once-popular lawyer hits a rough patch and meets a mysterious fitness trainer — both heal their scars through sweat and laughter."
  },