const recommendedKoreanSeries = [
  {
    id: 1,
    title: "When the Stars Gossip",
    platform: "Netflix",
    genre: "Romantic Comedy / Sci-Fi",
    year: 2025,
    popularity: 91,
    seasons: 1,
    episodes: 16,
    runtime: "60 min",
    language: "Hindi Dubbed"
  },
  {
    id: 2,
    title: "Hyper Knife",
    platform: "Disney+",
    genre: "Medical Thriller",
    year: 2025,
    popularity: 88,
    seasons: 1,
    episodes: 8,
    runtime: "55 min",
    language: "English Dubbed"
  },
  {
    id: 3,
    title: "Newtopia",
    platform: "Prime Video",
    genre: "Zombie / Romance / Action",
    year: 2025,
    popularity: 86,
    seasons: 1,
    episodes: 10,
    runtime: "50–60 min",
    language: "Hindi Dubbed"
  },
  {
    id: 4,
    title: "Resident Playbook",
    platform: "Netflix",
    genre: "Medical / Slice of Life",
    year: 2025,
    popularity: 89,
    seasons: 1,
    episodes: 12,
    runtime: "60 min",
    language: "English Dubbed"
  },
  {
    id: 5,
    title: "Crash Landing on You",
    platform: "Netflix",
    genre: "Romance / Drama",
    year: 2019,
    popularity: 95,
    seasons: 1,
    episodes: 16,
    runtime: "70 min",
    language: "Hindi Dubbed"
  },
  {
    id: 6,
    title: "Business Proposal",
    platform: "Netflix",
    genre: "Romantic Comedy",
    year: 2022,
    popularity: 93,
    seasons: 1,
    episodes: 12,
    runtime: "60 min",
    language: "Hindi Dubbed"
  },
  {
    id: 7,
    title: "Squid Game",
    platform: "Netflix",
    genre: "Survival / Thriller",
    year: 2021,
    popularity: 98,
    seasons: 2,
    episodes: 15,
    runtime: "55–60 min",
    language: "Hindi Dubbed"
  },
  {
    id: 8,
    title: "The Queen Who Crowns",
    platform: "TVING",
    genre: "Historical / Political",
    year: 2025,
    popularity: 84,
    seasons: 1,
    episodes: 12,
    runtime: "58 min",
    language: "Korean (Subs)"
  },
  {
    id: 9,
    title: "Melo Movie",
    platform: "Netflix",
    genre: "Romance / Drama",
    year: 2025,
    popularity: 87,
    seasons: 1,
    episodes: 10,
    runtime: "60 min",
    language: "Hindi Dubbed"
  },
  {
    id: 10,
    title: "My Name",
    platform: "Netflix",
    genre: "Action / Revenge",
    year: 2021,
    popularity: 90,
    seasons: 1,
    episodes: 8,
    runtime: "50 min",
    language: "Hindi Dubbed"
  },
  {
    id: 11,
    title: "All of Us Are Dead",
    platform: "Netflix",
    genre: "Zombie / Horror",
    year: 2022,
    popularity: 92,
    seasons: 1,
    episodes: 12,
    runtime: "55 min",
    language: "Hindi Dubbed"
  },
  {
    id: 12,
    title: "The Trauma Code: Heroes on Call",
    platform: "Netflix",
    genre: "Medical / Action",
    year: 2025,
    popularity: 85,
    seasons: 1,
    episodes: 8,
    runtime: "60 min",
    language: "English Dubbed"
  },
  {
    id: 13,
    title: "Itaewon Class",
    platform: "Netflix",
    genre: "Drama / Revenge",
    year: 2020,
    popularity: 91,
    seasons: 1,
    episodes: 16,
    runtime: "70 min",
    language: "Hindi Dubbed"
  },
  {
    id: 14,
    title: "Unmasked",
    platform: "Disney+",
    genre: "Mystery / Comedy",
    year: 2025,
    popularity: 83,
    seasons: 1,
    episodes: 12,
    runtime: "60 min",
    language: "English Dubbed"
  },
  {
    id: 15,
    title: "Extraordinary Attorney Woo",
    platform: "Netflix",
    genre: "Legal / Slice of Life",
    year: 2022,
    popularity: 94,
    seasons: 1,
    episodes: 16,
    runtime: "60 min",
    language: "Hindi Dubbed"
  },
{
  id: 16,
  title: "Love Scout",
  platform: "Netflix",
  genre: "Romantic Comedy / Workplace",
  year: 2025,
  popularity: 84,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 17,
  title: "Dear Hongrang",
  platform: "Netflix",
  genre: "Historical / Romance",
  year: 2025,
  popularity: 85,
  seasons: 1,
  episodes: 11,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 18,
  title: "Study Group",
  platform: "Netflix",
  genre: "Action / School / Comedy",
  year: 2025,
  popularity: 88,
  seasons: 1,
  episodes: 10,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 19,
  title: "Undercover High School",
  platform: "Disney+",
  genre: "Action / Comedy / Romance",
  year: 2025,
  popularity: 83,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "Korean (Subs)"
},
{
  id: 20,
  title: "The Potato Lab",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2025,
  popularity: 80,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 21,
  title: "Heavenly Ever After",
  platform: "Netflix",
  genre: "Fantasy / Romance",
  year: 2025,
  popularity: 87,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 22,
  title: "Trigger",
  platform: "TVING",
  genre: "Action / Thriller",
  year: 2025,
  popularity: 82,
  seasons: 1,
  episodes: 4,
  runtime: "55 min",
  language: "Korean (Subs)"
},
{
  id: 23,
  title: "Mercy for None",
  platform: "Netflix",
  genre: "Crime / Revenge / Action",
  year: 2025,
  popularity: 89,
  seasons: 1,
  episodes: 7,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 24,
  title: "Low Life",
  platform: "TVING",
  genre: "Mystery / Thriller",
  year: 2025,
  popularity: 81,
  seasons: 1,
  episodes: 3,
  runtime: "60 min",
  language: "Korean (Subs)"
},
{
  id: 25,
  title: "Anyway Thirty",
  platform: "Netflix",
  genre: "Slice of Life / Romance",
  year: 2025,
  popularity: 78,
  seasons: 1,
  episodes: 5,
  runtime: "30 min",
  language: "English Dubbed"
},
{
  id: 26,
  title: "FC Soldout",
  platform: "Wavve",
  genre: "Sports / Satire / BL",
  year: 2025,
  popularity: 76,
  seasons: 1,
  episodes: 8,
  runtime: "25 min",
  language: "Korean (Subs)"
},
{
  id: 27,
  title: "The Divorce Insurance",
  platform: "Prime Video",
  genre: "Romantic Comedy / Legal",
  year: 2025,
  popularity: 83,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 28,
  title: "The Haunted Palace",
  platform: "SBS",
  genre: "Horror / Mystery",
  year: 2025,
  popularity: 79,
  seasons: 1,
  episodes: 10,
  runtime: "55 min",
  language: "Korean (Subs)"
},
{
  id: 29,
  title: "Buried Hearts",
  platform: "SBS",
  genre: "Political / Revenge",
  year: 2025,
  popularity: 80,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "Korean (Subs)"
},
{
  id: 30,
  title: "The Hot Spot",
  platform: "TV Asahi",
  genre: "Sci-Fi / Slice of Life",
  year: 2025,
  popularity: 77,
  seasons: 1,
  episodes: 10,
  runtime: "50 min",
  language: "English Dubbed"
},
{
  id: 31,
  title: "Vincenzo",
  platform: "Netflix",
  genre: "Crime / Comedy / Action",
  year: 2021,
  popularity: 94,
  seasons: 1,
  episodes: 20,
  runtime: "70 min",
  language: "Hindi Dubbed"
},
{
  id: 32,
  title: "King the Land",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2023,
  popularity: 91,
  seasons: 1,
  episodes: 16,
  runtime: "65 min",
  language: "Hindi Dubbed"
},
{
  id: 33,
  title: "The Glory",
  platform: "Netflix",
  genre: "Revenge / School / Thriller",
  year: 2022,
  popularity: 93,
  seasons: 2,
  episodes: 16,
  runtime: "55 min",
  language: "Hindi Dubbed"
},
{
  id: 34,
  title: "Strong Girl Nam-soon",
  platform: "Netflix",
  genre: "Superpower / Comedy / Action",
  year: 2023,
  popularity: 88,
  seasons: 1,
  episodes: 16,
  runtime: "60 min",
  language: "Hindi Dubbed"
},
{
  id: 35,
  title: "See You in My 19th Life",
  platform: "Netflix",
  genre: "Romance / Fantasy",
  year: 2023,
  popularity: 86,
  seasons: 1,
  episodes: 12,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 36,
  title: "Alchemy of Souls",
  platform: "Netflix",
  genre: "Fantasy / Romance / Action",
  year: 2022,
  popularity: 90,
  seasons: 2,
  episodes: 30,
  runtime: "70 min",
  language: "Hindi Dubbed"
},
{
  id: 37,
  title: "Hospital Playlist",
  platform: "Netflix",
  genre: "Medical / Slice of Life",
  year: 2020,
  popularity: 92,
  seasons: 2,
  episodes: 24,
  runtime: "70–80 min",
  language: "Hindi Dubbed"
},
{
  id: 38,
  title: "A Business Proposal",
  platform: "Netflix",
  genre: "Romantic Comedy",
  year: 2022,
  popularity: 93,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 39,
  title: "Sweet Home",
  platform: "Netflix",
  genre: "Horror / Action / Thriller",
  year: 2020,
  popularity: 89,
  seasons: 2,
  episodes: 18,
  runtime: "50–60 min",
  language: "Hindi Dubbed"
},
{
  id: 40,
  title: "Nevertheless",
  platform: "Netflix",
  genre: "Romance / Youth / Drama",
  year: 2021,
  popularity: 84,
  seasons: 1,
  episodes: 10,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 41,
  title: "Tale of the Nine Tailed",
  platform: "Netflix",
  genre: "Fantasy / Romance / Thriller",
  year: 2020,
  popularity: 89,
  seasons: 2,
  episodes: 24,
  runtime: "60 min",
  language: "Hindi Dubbed"
},
{
  id: 42,
  title: "Mask Girl",
  platform: "Netflix",
  genre: "Thriller / Dark Comedy",
  year: 2023,
  popularity: 87,
  seasons: 1,
  episodes: 7,
  runtime: "50–55 min",
  language: "English Dubbed"
},
{
  id: 43,
  title: "The Sound of Magic",
  platform: "Netflix",
  genre: "Fantasy / Musical / Youth",
  year: 2022,
  popularity: 82,
  seasons: 1,
  episodes: 6,
  runtime: "60 min",
  language: "Hindi Dubbed"
},
{
  id: 44,
  title: "Love Alarm",
  platform: "Netflix",
  genre: "Romance / Tech / Youth",
  year: 2019,
  popularity: 86,
  seasons: 2,
  episodes: 14,
  runtime: "50 min",
  language: "Hindi Dubbed"
},
{
  id: 45,
  title: "Doctor Cha",
  platform: "Netflix",
  genre: "Medical / Comedy / Family",
  year: 2023,
  popularity: 88,
  seasons: 1,
  episodes: 16,
  runtime: "60 min",
  language: "Hindi Dubbed"
},
{
  id: 46,
  title: "Start-Up",
  platform: "Netflix",
  genre: "Romance / Tech / Drama",
  year: 2020,
  popularity: 90,
  seasons: 1,
  episodes: 16,
  runtime: "70 min",
  language: "Hindi Dubbed"
},
{
  id: 47,
  title: "The Silent Sea",
  platform: "Netflix",
  genre: "Sci-Fi / Thriller",
  year: 2021,
  popularity: 85,
  seasons: 1,
  episodes: 8,
  runtime: "50 min",
  language: "Hindi Dubbed"
},
{
  id: 48,
  title: "D.P.",
  platform: "Netflix",
  genre: "Military / Action / Drama",
  year: 2021,
  popularity: 88,
  seasons: 2,
  episodes: 12,
  runtime: "50 min",
  language: "Hindi Dubbed"
},
{
  id: 49,
  title: "The King’s Affection",
  platform: "Netflix",
  genre: "Historical / Romance",
  year: 2021,
  popularity: 87,
  seasons: 1,
  episodes: 20,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 50,
  title: "Queenmaker",
  platform: "Netflix",
  genre: "Political / Drama",
  year: 2023,
  popularity: 84,
  seasons: 1,
  episodes: 11,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 51,
  title: "The 8 Show",
  platform: "Netflix",
  genre: "Survival / Satire / Thriller",
  year: 2024,
  popularity: 86,
  seasons: 1,
  episodes: 8,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 52,
  title: "A Killer Paradox",
  platform: "Netflix",
  genre: "Crime / Psychological / Thriller",
  year: 2024,
  popularity: 89,
  seasons: 1,
  episodes: 8,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 53,
  title: "The Trunk",
  platform: "Netflix",
  genre: "Mystery / Romance",
  year: 2024,
  popularity: 83,
  seasons: 1,
  episodes: 8,
  runtime: "50 min",
  language: "English Dubbed"
},
{
  id: 54,
  title: "Daily Dose of Sunshine",
  platform: "Netflix",
  genre: "Medical / Mental Health / Slice of Life",
  year: 2023,
  popularity: 88,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 55,
  title: "The Whirlwind",
  platform: "Netflix",
  genre: "Political / Thriller",
  year: 2025,
  popularity: 85,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "English Dubbed"
},
{
  id: 56,
  title: "Hierarchy",
  platform: "Netflix",
  genre: "Teen / Mystery / Romance",
  year: 2024,
  popularity: 84,
  seasons: 1,
  episodes: 7,
  runtime: "50 min",
  language: "English Dubbed"
},
{
  id: 57,
  title: "Castaway Diva",
  platform: "Netflix",
  genre: "Music / Romance / Comedy",
  year: 2023,
  popularity: 82,
  seasons: 1,
  episodes: 12,
  runtime: "55 min",
  language: "English Dubbed"
},
{
  id: 58,
  title: "The Bequeathed",
  platform: "Netflix",
  genre: "Mystery / Thriller",
  year: 2024,
  popularity: 80,
  seasons: 1,
  episodes: 6,
  runtime: "50 min",
  language: "English Dubbed"
},
{
  id: 59,
  title: "Chicken Nugget",
  platform: "Netflix",
  genre: "Comedy / Sci-Fi / Absurdist",
  year: 2024,
  popularity: 79,
  seasons: 1,
  episodes: 10,
  runtime: "40 min",
  language: "English Dubbed"
},
{
  id: 60,
  title: "Good Boy",
  platform: "JTBC",
  genre: "Sports / Action / Drama",
  year: 2025,
  popularity: 84,
  seasons: 1,
  episodes: 12,
  runtime: "60 min",
  language: "Korean (Subs)"
},
];