const koreanWatchlist = [
  {
    id: 1,
    title: "Mouse",
    platform: "tvN / Viki",
    genre: "Psychological Thriller",
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "20h",
    popularity: 92,
    imdbRating: 8.7,
    hindiDubbed: false,
    description: "A rookie cop becomes entangled in a string of serial murders — but who’s hunting whom in this intense mind game?"
  },
  {
    id: 2,
    title: "Hellbound",
    platform: "Netflix",
    genre: "Supernatural Thriller",
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "5h",
    popularity: 89,
    imdbRating: 6.6,
    hindiDubbed: true,
    description: "Mysterious creatures sentence people to hell — triggering chaos and cults in this dark commentary on justice and faith."
  },
  {
    id: 3,
    title: "My Mister",
    platform: "Netflix",
    genre: "Slice of Life Drama",
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 94,
    imdbRating: 9.1,
    hindiDubbed: false,
    description: "A weary middle-aged man and a stoic young woman find strength and solace in each other’s quiet pain."
  },
  {
    id: 4,
    title: "Stranger (Secret Forest)",
    platform: "Netflix",
    genre: "Crime Mystery",
    year: 2017,
    seasons: 2,
    episodes: 32,
    runtime: "24h",
    popularity: 91,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A prosecutor who feels no emotion and a principled detective team up to uncover systemic corruption."
  },
  {
    id: 5,
    title: "Crash Landing on You",
    platform: "Netflix",
    genre: "Romantic Drama",
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "18h",
    popularity: 98,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A South Korean heiress crash-lands in North Korea and finds love, danger, and destiny on the other side of the DMZ."
  },
  {
    id: 6,
    title: "Kingdom",
    platform: "Netflix",
    genre: "Historical Zombie Thriller",
    year: 2019,
    seasons: 2,
    episodes: 13,
    runtime: "12h",
    popularity: 93,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In medieval Joseon, a mysterious plague unleashes the undead — and only a crown prince can stop it."
  },
  {
    id: 7,
    title: "Extraordinary Attorney Woo",
    platform: "Netflix",
    genre: "Legal Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 95,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "A brilliant young attorney on the autism spectrum tackles complex cases with logic, empathy, and whale facts."
  },
  {
    id: 8,
    title: "Hospital Playlist",
    platform: "tvN / Netflix",
    genre: "Medical Slice of Life",
    year: 2020,
    seasons: 2,
    episodes: 24,
    runtime: "28h",
    popularity: 96,
    imdbRating: 8.8,
    hindiDubbed: false,
    description: "Five doctors, lifelong friends, and their patients share joy, loss, and music in this warmhearted medical drama."
  },
  {
    id: 9,
    title: "Flower of Evil",
    platform: "tvN / Viki / Airtel Xstream",
    genre: "Crime Melodrama",
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 90,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A loving husband hides a twisted past — but when his detective wife starts investigating, can love survive suspicion?"
  },
  {
    id: 10,
    title: "Signal",
    platform: "tvN / Netflix",
    genre: "Crime Sci-Fi",
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 88,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A mysterious walkie-talkie connects two detectives across time to solve cold cases and stop future crimes."
  },
  {
    id: 11,
    title: "The Glory",
    platform: "Netflix",
    genre: "Revenge Drama",
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 97,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "A woman scarred by brutal school bullying crafts a decades-long revenge plot against her tormentors."
  },
  {
    id: 12,
    title: "D.P.",
    platform: "Netflix",
    genre: "Military / Social Drama",
    year: 2021,
    seasons: 2,
    episodes: 12,
    runtime: "10h",
    popularity: 89,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Two army privates in the Deserter Pursuit Unit chase runaway soldiers — and confront the trauma inside military ranks."
  },
  {
    id: 13,
    title: "My Name",
    platform: "Netflix",
    genre: "Action Noir",
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "7h",
    popularity: 86,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "After her father's death, a woman enters the underworld and the police force — to exact her bloody revenge."
  },
  {
    id: 14,
    title: "Beyond Evil",
    platform: "JTBC / Netflix",
    genre: "Psychological Crime",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 84,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Two detectives with dark pasts chase a serial killer — but what if the monster is one of them?"
  },
  {
    id: 15,
    title: "Through the Darkness",
    platform: "SBS / Viki",
    genre: "True Crime Psychological",
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "12h",
    popularity: 83,
    imdbRating: 8.1,
    hindiDubbed: false,
    description: "Based on real events, Korea’s first profiler enters the twisted minds of serial killers to stop them before they strike again."
  },
  {
    id: 16,
    title: "The Devil Judge",
    platform: "tvN / Viki",
    genre: "Legal Dystopia",
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "16h",
    popularity: 85,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In a dystopian Korea, a charismatic judge turns the courtroom into reality TV — delivering justice his own way amid dark secrets."
  },
  {
    id: 17,
    title: "Vincenzo",
    platform: "tvN / Netflix",
    genre: "Mafia Satire / Action",
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "24h",
    popularity: 98,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "A Korean-Italian mafia consigliere returns to Seoul for hidden gold — but ends up fighting corporate villains with fire and flair."
  },
  {
    id: 18,
    title: "Queenmaker",
    platform: "Netflix",
    genre: "Political Drama",
    year: 2023,
    seasons: 1,
    episodes: 11,
    runtime: "10h",
    popularity: 87,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "A shrewd fixer transforms a humble lawyer into a political force — setting the stage for justice, revenge, and ruthless strategy."
  },
  