<<<<<<< Updated upstream
<<<<<<< Updated upstream
window.koreanWatchlist= [
=======
window.koreanWatchlist = [
>>>>>>> Stashed changes
=======
window.koreanWatchlist = [
>>>>>>> Stashed changes
  {
    id: 1,
    title: "Mouse",
    platform: "tvN / Viki",
    genre: "Psychological Thriller",
    mustwatch: true,
    year: 2021,
    popularity: 9.8,
    imdbRating: 8.6,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    description: "In this gripping psychological thriller, a righteous rookie police officer, Jung Ba-reum, has his life turned upside down after a fateful encounter with a serial killer. As he and a hardened detective hunt for the elusive murderer, they uncover a shocking truth about the killer's origins and face a moral dilemma about what constitutes a monster. The series explores the question of whether a psychopath's nature is inherited or nurtured, with shocking twists and turns that keep you on the edge of your seat."
  },
  {
    id: 2,
    title: "Hellbound",
    platform: "Netflix",
    genre: "Supernatural Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "60-70 min",
    popularity: 8.9,
    imdbRating: 6.6,
    hindiDubbed: true,
    description: "Mysterious creatures appear out of nowhere to condemn people to hell, triggering a wave of fear and religious fanaticism. As a new cult rises to power, a television producer and a detective try to investigate the supernatural occurrences and the sinister organization behind them. The series is a dark and thought-provoking commentary on justice, faith, and what it means to be human in the face of the unknown."
  },
  {
    id: 3,
    title: "My Mister",
    platform: "Netflix",
    genre: "Slice of Life Drama",
    mustwatch: true,
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.4,
    imdbRating: 9.1,
    hindiDubbed: false,
    description: "Park Dong-hoon, a middle-aged engineer burdened by life, forms a deep and unexpected bond with Lee Ji-an, a young temp worker at his company who is struggling to pay off debt. They find solace in each other's quiet pain and help one another navigate the harsh realities of their lives. This critically acclaimed series is a poignant and deeply moving exploration of human connection, loneliness, and the healing power of empathy."
  },
  {
    id: 4,
    title: "Stranger (Secret Forest)",
    platform: "Netflix",
    genre: "Crime Mystery",
    mustwatch: true,
    year: 2017,
    seasons: 2,
    episodes: 32,
    runtime: "60-70 min",
    popularity: 9.1,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Hwang Si-mok, a prosecutor who had brain surgery that left him devoid of emotion, and Han Yeo-jin, a warm and principled police detective, team up to expose a web of corruption and serial murders. As they dig deeper, they realize that the criminals they are chasing are intertwined with their own professional and personal circles. The series is a taut and intelligent crime thriller with a stellar cast and a complex, engaging plot."
  },
  {
    id: 5,
    title: "Crash Landing on You",
    platform: "Netflix",
    genre: "Romantic Drama",
    mustwatch: true,
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.8,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A South Korean heiress, Yoon Se-ri, gets swept up in a paragliding accident and crash-lands in North Korea. There, she is discovered by Ri Jeong-hyeok, a charismatic North Korean army officer, who reluctantly agrees to help her get back home. As they navigate the dangerous and restrictive world of North Korea, they fall in love, facing immense obstacles and political tensions that threaten to tear them apart."
  },
  {
    id: 6,
    title: "Kingdom",
    platform: "Netflix",
    genre: "Historical Zombie Thriller",
    mustwatch: true,
    year: 2019,
    seasons: 2,
    episodes: 13,
    runtime: "40-50 min",
    popularity: 9.3,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Set in Korea's Joseon Dynasty, a mysterious plague turns the dead into flesh-eating monsters. As the king falls ill, the Crown Prince Lee Chang is framed as a traitor and is forced to flee the palace. He embarks on a journey to uncover the truth behind the plague and save his people from the undead horde. The series is a thrilling combination of political intrigue, historical drama, and heart-pounding zombie action."
  },
  {
    id: 7,
    title: "Extraordinary Attorney Woo",
    platform: "Netflix",
    genre: "Legal Drama",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.5,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Woo Young-woo, a brilliant young attorney on the autism spectrum, joins a top law firm. Despite her photographic memory and high IQ, she struggles with social interactions. However, she uses her unique perspective to solve complex legal cases in a way that no one else can. The series is a heartwarming and insightful look into the challenges and triumphs of a person with autism in a neurotypical world."
  },
  {
    id: 8,
    title: "Hospital Playlist",
    platform: "tvN / Netflix",
    genre: "Medical Slice of Life",
    mustwatch: true,
    year: 2020,
    seasons: 2,
    episodes: 24,
    runtime: "60-80 min",
    popularity: 9.6,
    imdbRating: 8.8,
    hindiDubbed: false,
    description: "The series follows the lives of five doctors who have been best friends since medical school. They navigate the daily challenges of their professional lives, balancing surgeries and patient care with their personal relationships, families, and their weekly band practice. The show is known for its realistic and emotional portrayal of life inside a hospital, celebrating the bonds of friendship and the small, meaningful moments of everyday life."
  },
  {
    id: 9,
    title: "Flower of Evil",
    platform: "tvN / Viki / Airtel Xstream",
    genre: "Crime Melodrama",
    mustwatch: true,
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "Cha Ji-won, a strong and successful police detective, is married to Baek Hee-sung, a seemingly perfect husband and father. However, Hee-sung is secretly living a lie, having hidden a dark and twisted past. When Ji-won is assigned to a new murder case, the clues begin to point to her husband's past, forcing her to question everything she thought she knew about him. The series is a suspenseful blend of romance, family drama, and psychological thriller."
  },
  {
    id: 10,
    title: "Signal",
    platform: "tvN / Netflix",
    genre: "Crime Sci-Fi",
    mustwatch: true,
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.8,
    imdbRating: 8.9,
    hindiDubbed: true,
    description: "A criminal profiler from 2015 discovers a mysterious walkie-talkie that allows him to communicate with a detective from 1989. The two detectives, separated by time, use their unique connection to solve cold cases that have haunted the police force for years, and in the process, they also uncover a shocking truth about a past tragedy. This series is a masterclass in storytelling, combining a compelling procedural plot with a poignant time-travel element."
  },
  {
    id: 11,
    title: "The Glory",
    platform: "Netflix",
    genre: "Revenge Drama",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "50-60 min",
    popularity: 9.7,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Moon Dong-eun, a woman who was brutally bullied in high school, devotes her life to meticulously planning revenge against her tormentors. She carefully orchestrates a plan to take down each of her former bullies, becoming the teacher of one of their children in the process. The series is a dark and satisfying revenge thriller that explores the lasting trauma of bullying and the determination of a woman seeking justice."
  },
  {
    id: 12,
    title: "D.P.",
    platform: "Netflix",
    genre: "Military / Social Drama",
    mustwatch: true,
    year: 2021,
    seasons: 2,
    episodes: 12,
    runtime: "50-60 min",
    popularity: 8.9,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "An Jun-ho, a quiet but observant soldier, is assigned to the Deserter Pursuit (D.P.) unit, a team tasked with hunting down soldiers who have gone AWOL. Along with his partner, Han Ho-yeol, he chases down various deserters and in the process, confronts the harsh realities and emotional toll of life in the military. The series is a powerful and critically acclaimed look at the hidden side of military life and the reasons behind desertion."
  },
  {
    id: 13,
    title: "My Name",
    platform: "Netflix",
    genre: "Action Noir",
    mustwatch: true,
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "45-50 min",
    popularity: 8.6,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "After her father is murdered, Yoon Ji-woo, a young woman, joins a notorious crime syndicate to learn who killed him. Under the guidance of the gang's boss, she becomes a formidable fighter and goes undercover as a police officer to get closer to the truth. The series is a gritty and intense action noir, showcasing a female lead's journey of revenge and her struggle to uncover the secrets surrounding her father's death."
  },
  {
    id: 14,
    title: "Beyond Evil",
    platform: "JTBC / Netflix",
    genre: "Psychological Crime",
    mustwatch: true,
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.4,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Two police detectives, the seasoned Lee Dong-sik and the ambitious Han Joo-won, are forced to work together to solve a new murder case that eerily resembles a 20-year-old cold case. As they hunt for the killer, they begin to question the identities of everyone around them, including their own, as they dig deeper into the dark secrets of their small town. The series is a multi-layered psychological thriller that keeps you guessing until the very end."
  },
  {
    id: 15,
    title: "Through the Darkness",
    platform: "SBS / Viki",
    genre: "True Crime Psychological",
    mustwatch: false,
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.3,
    imdbRating: 8.1,
    hindiDubbed: false,
    description: "Based on the true story of South Korea's first criminal profiler, the series follows Song Ha-young, a quiet and meticulous profiler who studies the minds of serial killers to understand their motives. In a time when profiling was not a recognized practice, he and his team work tirelessly to prevent future crimes and bring justice to victims. This series is a compelling and authentic portrayal of the early days of criminal profiling in South Korea."
  },
  {
    id: 16,
    title: "The Devil Judge",
    platform: "tvN / Viki",
    genre: "Legal Dystopia",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.5,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In a dystopian South Korea where the rich and powerful run rampant, Kang Yo-han, a mysterious and charismatic judge, turns his courtroom into a live reality show. He delivers justice in a brutal and theatrical manner, making him a hero to the public but an enemy to the corrupt elite. The series is a thrilling legal drama that raises questions about justice, morality, and the fine line between a hero and a villain."
  },
  {
    id: 17,
    title: "Vincenzo",
    platform: "tvN / Netflix",
    genre: "Mafia Satire / Action",
    mustwatch: true,
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "70-80 min",
    popularity: 9.8,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Vincenzo Cassano, a consigliere to the Italian Mafia, returns to South Korea after a conflict within his organization. He intends to retrieve a fortune of gold hidden beneath an old building, but he finds himself caught in a battle against the corrupt conglomerate that has illegally taken over the property. With the help of a quirky lawyer, he uses his mafia tactics to take down his powerful enemies in this stylish and darkly comedic action series."
  },
  {
    id: 18,
    title: "Queenmaker",
    platform: "Netflix",
    genre: "Political Drama",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 11,
    runtime: "50-60 min",
    popularity: 8.7,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Hwang Do-hee, a brilliant public relations specialist, is an expert at shaping public opinion. After a personal tragedy, she leaves her powerful corporate job to become the campaign manager for Oh Kyung-sook, a feisty human rights lawyer and labor activist. Together, they take on the ruthless world of politics, seeking to expose corruption and get Kyung-sook elected as the mayor of Seoul."
  },
  {
    id: 19,
    title: "Revenant",
    platform: "SBS / Disney+",
    genre: "Occult Thriller",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.2,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A young woman, Gu San-yeong, finds herself possessed by a malevolent spirit after inheriting an old keepsake from her deceased father. She teams up with Yeom Hae-sang, a folklorist who can see ghosts, to uncover the secrets of the evil spirit and her father's past. The series is a spine-chilling occult thriller that delves into Korean folklore and superstition, with a compelling mystery at its core."
  },
  {
    id: 20,
    title: "Big Mouth",
    platform: "MBC / Disney+",
    genre: "Legal Mystery Thriller",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Park Chang-ho, a bumbling and unsuccessful lawyer nicknamed 'Big Mouth,' is framed as a notorious con artist known as 'Big Mouse.' Imprisoned and facing the death penalty, he must navigate the dangerous world of prison, all while trying to clear his name and expose the powerful figures who set him up. The series is a fast-paced thriller with a gripping plot and many unexpected twists."
  },
  {
    id: 21,
    title: "One Ordinary Day",
    platform: "Coupang Play / Viu",
    genre: "Crime Courtroom Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "50-60 min",
    popularity: 8.1,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Kim Hyun-soo, a normal college student, is accused of murder after a one-night stand goes wrong. With all evidence pointing against him, he is forced to rely on Shin Joong-han, a third-rate lawyer who barely passed the bar exam. This series is an intense courtroom drama that highlights the flaws in the criminal justice system and the terrifying reality of being wrongfully accused."
  },
  {
    id: 22,
    title: "The Good Bad Mother",
    platform: "JTBC / Netflix",
    genre: "Healing / Family Drama",
    mustwatch: true,
    year: 2023,
    seasons: 1,
    episodes: 14,
    runtime: "60-70 min",
    popularity: 8.9,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "Young-soon, a single mother, raises her son Kang-ho with strict discipline so he can become a successful prosecutor and not have to endure the hardships she faced. After a tragic accident, the adult Kang-ho loses his memory and reverts to the mind of a seven-year-old, giving Young-soon a second chance to raise him with love and compassion. This heartfelt and emotional series explores the complexities of a mother-son relationship."
  },
  {
    id: 23,
    title: "My Liberation Notes",
    platform: "JTBC / Netflix",
    genre: "Existential Slice of Life",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.5,
    imdbRating: 8.4,
    hindiDubbed: false,
    description: "The series follows the three Yeom siblings and a mysterious outsider named Mr. Gu, all of whom feel unfulfilled and trapped in their lives. They are trying to find purpose and escape the monotony of their existence in a small rural town. The show is a quiet, contemplative, and deeply relatable drama that explores themes of loneliness, depression, and the human search for freedom and happiness."
  },
  {
    id: 24,
    title: "Juvenile Justice",
    platform: "Netflix",
    genre: "Courtroom Drama",
    mustwatch: false,
    year: 2022,
    seasons: 1,
    episodes: 10,
    runtime: "50-60 min",
    popularity: 8.4,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Shim Eun-seok, a judge who despises juvenile offenders, is appointed to a juvenile court. She is known for her cold and unfeeling demeanor, but she is determined to hold young criminals accountable for their actions and to ensure the legal system does not fail society. The series is a gripping and powerful look at the juvenile justice system and the complex issues surrounding youth crime."
  },
  {
    id: 25,
    title: "Queen of Tears",
    platform: "tvN / Netflix",
    genre: "Romantic Comedy, Melodrama",
    mustwatch: true,
    year: 2024,
    popularity: 9.2,
    imdbRating: 8.3,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    description: "This popular series follows the turbulent marriage of Hong Hae-in, a wealthy chaebol heiress, and Baek Hyun-woo, a humble lawyer from a rural town. Despite their love, the pressures of their different worlds and a shocking terminal illness threaten to tear them apart. The show is a beautiful blend of romance, humor, and melodrama, with strong performances from the lead actors as they navigate a deeply emotional and complex story about love, family, and survival."
  },
  {
    id: 26,
    title: "Watcher",
    platform: "OCN / Viki",
    genre: "Psychological Crime / Corruption",
    mustwatch: false,
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 7.9,
    imdbRating: 8.0,
    hindiDubbed: false,
    description: "After a tragic incident in their pasts, three individuals—a police officer, a prosecutor, and a detective—form an anti-corruption team to expose the truth behind their past and uncover a vast web of corruption within the police force. They are constantly forced to question who they can trust, as they confront the darkness that lies within the system and themselves."
  },
  {
    id: 27,
    title: "Live",
    platform: "tvN / Netflix",
    genre: "Police / Slice of Life",
    mustwatch: false,
    year: 2018,
    seasons: 1,
    episodes: 18,
    runtime: "60-70 min",
    popularity: 8.3,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "The series follows the daily lives of rookie police officers who are assigned to a precinct, dealing with both mundane and dangerous situations. They struggle with the challenges of their job, from bureaucratic hurdles to emotional trauma, while trying to maintain their integrity and personal lives. This show offers a realistic and raw look at the sacrifices and humanity of the people who serve on the front lines."
  },
  {
    id: 28,
    title: "Mr. Sunshine",
    platform: "tvN / Netflix",
    genre: "Historical Epic / Romance",
    mustwatch: true,
    year: 2018,
    seasons: 1,
    episodes: 24,
    runtime: "70-80 min",
    popularity: 9.4,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "Set in the late 19th and early 20th century, the series tells the story of Eugene Choi, a Korean-born American Marine Corps officer who returns to his homeland during a period of great political turmoil. He falls in love with Go Ae-shin, a noblewoman who is secretly a member of the Righteous Army fighting for Korea's independence. This epic historical drama is a beautifully shot and emotional tale of love, sacrifice, and patriotism."
  },
  {
    id: 29,
    title: "Arthdal Chronicles",
    platform: "tvN / Netflix",
    genre: "Mythical Historical Fantasy",
    mustwatch: false,
    year: 2019,
    seasons: 2,
    episodes: 30,
    runtime: "60-70 min",
    popularity: 8.8,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "In the mythical land of Arth, various tribes and powerful leaders clash for control and power. The story centers on a hero, Eun-seom, who is destined to bring change to the world of Arth. As he faces prophecies and challenges, he fights to save his people and uncover the truth of his origins. The series is a sprawling fantasy epic with complex world-building and breathtaking visuals."
  },
  {
    id: 30,
    title: "Goblin (Guardian: The Lonely and Great God)",
    platform: "tvN / MX Player / Airtel Xstream",
    genre: "Fantasy Romance",
    mustwatch: true,
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.7,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Kim Shin, an immortal goblin, is cursed to live forever until he finds his destined bride, the only one who can pull the sword from his chest and bring him peace. His life changes when he meets Ji Eun-tak, a high school student who can see ghosts and claims to be his bride. The series is a beloved classic that combines romance, comedy, and fantasy, with a touching story about fate, love, and sacrifice."
  },
  {
    id: 31,
    title: "Alchemy of Souls",
    platform: "tvN / Netflix",
    genre: "Fantasy / Historical Romance",
    mustwatch: true,
    year: 2022,
    seasons: 2,
    episodes: 30,
    runtime: "60-70 min",
    popularity: 9.1,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "In a fictional kingdom, powerful mages can perform 'alchemy of souls,' a forbidden spell that allows souls to swap bodies. The story follows a powerful soul-shifter, Nak-su, who becomes trapped in the body of a weak servant girl named Mu-deok. She is then taken in by a nobleman, Jang Uk, and becomes his secret master, training him in magic and helping him become a powerful mage. The series is a visually stunning fantasy romance with a captivating plot and unforgettable characters."
  },
  {
    id: 32,
    title: "Mr. Queen",
    platform: "tvN / Netflix",
    genre: "Historical Comedy / Body Swap",
    mustwatch: true,
    year: 2020,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 9.3,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Jang Bong-hwan, a modern-day chef, is transported back in time to the Joseon Dynasty and finds himself trapped in the body of Queen Kim So-yong. He must navigate the treacherous world of palace politics and royal intrigue while trying to maintain his true identity and a sense of normalcy. The series is a hilarious and witty historical comedy that also delves into deeper themes of power, gender roles, and self-discovery."
  },
  {
    id: 33,
    title: "The Red Sleeve",
    platform: "MBC / Viki",
    genre: "Historical Romance",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 17,
    runtime: "60-70 min",
    popularity: 8.6,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Based on a true story, the series depicts the tragic love story between King Jeongjo and a court lady, Sung Deok-im. Deok-im values her freedom and independence, repeatedly rejecting the king's request for her to become his royal concubine, which would make her a political figure. The series is a beautifully told tale of a forbidden love that highlights the sacrifices and struggles of women in the Joseon palace."
  },
  {
    id: 34,
    title: "Moon Lovers: Scarlet Heart Ryeo",
    platform: "SBS / Viki",
    genre: "Historical Fantasy / Tragedy",
    mustwatch: true,
    year: 2016,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 9.5,
    imdbRating: 8.7,
    hindiDubbed: true,
    description: "A 21st-century woman, Go Ha-jin, is transported back in time to the Goryeo Dynasty during a total solar eclipse. She wakes up in the body of a young noblewoman and finds herself entangled in the political rivalries and romantic lives of the royal princes. She falls in love with the cruel and enigmatic 4th prince, Wang So, and is caught in a deadly battle for the throne. The series is a heart-wrenching and unforgettable historical drama."
  },
  {
    id: 35,
    title: "Rookie Historian Goo Hae-ryung",
    platform: "MBC / Netflix",
    genre: "Historical / Feminist Romance",
    mustwatch: false,
    year: 2019,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 8.2,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Goo Hae-ryung is an educated and independent woman in a time when women were not allowed to be historians. She joins the royal court as a historian, determined to document history truthfully and fight for gender equality. She meets Prince Yi Rim, a lonely and secretly rebellious writer, and they find common ground in their fight against societal norms. This is a lighthearted and charming historical romance with a refreshing feminist message."
  },
  {
    id: 36,
    title: "Joseon Attorney",
    platform: "MBC / Amazon miniTV / WeTV",
    genre: "Historical Legal Drama",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.0,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Kang Han-su is a cunning and brilliant lawyer in the Joseon Dynasty who uses the law to take revenge on those who wronged him and his family. He meets Princess Yeon-joo, who is secretly working as a servant to gather evidence against the corrupted officials. The series is a thrilling legal drama with a strong sense of justice and a touching romance at its core."
  },
  {
    id: 37,
    title: "Queen for Seven Days",
    platform: "KBS2 / Netflix",
    genre: "Historical Melodrama",
    mustwatch: false,
    year: 2017,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 8.1,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "This is the tragic love story of Queen Dan-gyeong, who was dethroned just seven days after her ascension. She falls in love with Prince Lee Yeok, who later becomes King Jungjong, and their relationship is caught in the midst of a bloody power struggle between the king and his tyrannical half-brother. The series is a heartbreaking melodrama that explores the pain of love and sacrifice in the face of political adversity."
  },
  {
    id: 38,
    title: "Under the Queen’s Umbrella",
    platform: "tvN / Netflix",
    genre: "Historical / Political Family Drama",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.8,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Queen Im Hwa-ryeong, a spirited and unorthodox queen, goes to great lengths to educate her five troublemaker sons so that one of them can succeed to the throne and she can protect them from the ruthless political machinations of the royal court. The series is a compelling historical drama that delves into the politics of the Joseon dynasty and the fierce love of a mother who will stop at nothing to protect her children."
  },
  {
    id: 39,
    title: "The Crowned Clown",
    platform: "tvN / Netflix",
    genre: "Historical Thriller",
    mustwatch: false,
    year: 2019,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.4,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "In a period of political unrest and power struggles, King Lee Heon, a paranoid and tyrannical ruler, hires a clown who looks exactly like him to be his doppelgänger and protect him from assassination. The clown, Ha-sun, soon finds himself in the middle of a deadly power play, and he must choose between his own survival and fighting for the people he has come to love. The series is a gripping and suspenseful historical drama."
  },
  {
    id: 40,
    title: "100 Days My Prince",
    platform: "tvN / Netflix",
    genre: "Historical Romance / Comedy",
    mustwatch: false,
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.7,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Crown Prince Lee Yul is a perfectionist who suffers from temporary amnesia after a failed assassination attempt. He wakes up with no memory of his past and is taken in by a commoner family, where he is forced to live as a farmer's son and marry a woman named Hong-shim. The series is a charming and funny historical romance that follows the prince's journey to reclaim his memories and his heart."
  },
  {
    id: 41,
    title: "Love in the Moonlight",
    platform: "KBS2 / Viki",
    genre: "Historical Romance / Youth",
    mustwatch: false,
    year: 2016,
    seasons: 1,
    episodes: 18,
    runtime: "60-70 min",
    popularity: 8.5,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Hong Ra-on, a young woman who makes a living as a relationship counselor, disguises herself as a eunuch to enter the royal palace. There, she meets Crown Prince Hyomyeong, and their initial animosity soon turns into a forbidden romance. The series is a heartwarming and charming historical romance that explores the challenges of love, gender identity, and royal duty."
  },
  {
    id: 42,
    title: "The King’s Affection",
    platform: "KBS2 / Netflix",
    genre: "Historical Romance / Gender Swap",
    mustwatch: true,
    year: 2021,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "After her twin brother is murdered, a princess named Dam-i is forced to take his place as the Crown Prince, hiding her true identity from everyone around her. As she navigates the dangerous world of the royal court, she struggles with her secret and her growing affection for her childhood love, who is now her royal tutor. The series is an emotional and suspenseful historical romance that explores themes of identity, fate, and forbidden love."
  },
  {
    id: 43,
    title: "Sweet Home",
    platform: "Netflix",
    genre: "Apocalyptic Horror / Monster",
    mustwatch: true,
    year: 2020,
    seasons: 3,
    episodes: 30,
    runtime: "40-50 min",
    popularity: 9.5,
    imdbRating: 7.3,
    hindiDubbed: true,
    description: "Cha Hyun-soo, a reclusive high school student, moves into a new apartment complex after his family dies in an accident. Soon, a mysterious apocalypse breaks out, and humans begin to turn into terrifying monsters that reflect their innermost desires. Hyun-soo and the other residents must band together to survive against the monstrous creatures and the growing paranoia within the building. The series is a visually stunning and suspenseful monster thriller."
  },
  {
    id: 44,
    title: "The Uncanny Counter",
    platform: "OCN / Netflix",
    genre: "Supernatural Action",
    mustwatch: true,
    year: 2020,
    seasons: 2,
    episodes: 28,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "A group of demon hunters, known as the 'Counters,' masquerade as employees of a noodle restaurant. They are tasked with capturing and banishing evil spirits that have escaped from the afterlife and are now preying on humans. The team gains a new member, a high school student named So Mun, who has a disability but possesses an extraordinary power. The series is a fun and fast-paced supernatural action-comedy with a lot of heart."
  },
  {
    id: 45,
    title: "Happiness",
    platform: "tvN / Netflix",
    genre: "Apocalyptic Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.8,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "In a world where a new virus called 'Mad Person Disease' turns people into bloodthirsty monsters, a high-rise apartment building is locked down and its residents are forced to survive. Yoon Sae-bom, a special operations police officer, and Jung Yi-hyun, a detective, are among the residents who must navigate the growing paranoia and fear within the building, as they fight for their lives against the infected and each other."
  },
  {
    id: 46,
    title: "All of Us Are Dead",
    platform: "Netflix",
    genre: "Zombie Survival / Teen Horror",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 9.6,
    imdbRating: 7.5,
    hindiDubbed: true,
    description: "A zombie virus outbreak begins at a high school and quickly spreads throughout the city. A group of students is trapped inside the school, and they must use their wits and courage to survive against the horde of undead. The series is a tense and action-packed zombie thriller that explores themes of friendship, survival, and the dark side of human nature."
  },
  {
    id: 47,
    title: "Duty After School",
    platform: "TVING / Viki",
    genre: "Sci-Fi Military Thriller",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 10,
    runtime: "45-50 min",
    popularity: 8.4,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "When mysterious alien spheres descend upon Earth, high school seniors are forced to enroll in the military and fight alongside their teachers to defend humanity. The students, who were just focused on their college entrance exams, must now face a brutal reality and a deadly war. The series is a gripping sci-fi thriller that showcases the students' struggles to survive and protect each other."
  },
  {
    id: 48,
    title: "Dark Hole",
    platform: "OCN / Viki / DramaLine",
    genre: "Horror / Mystery Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 7.8,
    imdbRating: 7.0,
    hindiDubbed: true,
    description: "A mysterious sinkhole in a small town emits a black smoke that turns people into bloodthirsty mutants. Lee Hwa-sun, a detective, and Yoo Tae-han, a former police officer, must team up to survive the chaos and uncover the secrets behind the outbreak. The series is a suspenseful horror thriller with a mysterious and dark atmosphere."
  },
  {
    id: 49,
    title: "Island",
    platform: "TVING / Amazon Prime Video",
    genre: "Fantasy / Demon Hunter",
    mustwatch: false,
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "40-50 min",
    popularity: 8.5,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "On Jeju Island, a beautiful and ancient place, a supernatural evil is about to awaken. A team of unlikely heroes—a demon slayer, a priest, and a woman who holds the key to the island's fate—must unite to stop the powerful demons from destroying the world. The series is a fantasy-action series with stunning visuals and an intriguing story rooted in Korean folklore."
  },
  {
    id: 50,
    title: "Bulgasal: Immortal Souls",
    platform: "tvN / Netflix",
    genre: "Fantasy / Revenge Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.3,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Dan Hwal, a man cursed with immortality, has been living for 600 years as a 'Bulgasal,' a mythical creature that feeds on human blood. He is haunted by the past and is determined to find the woman who was responsible for his curse, who is now reincarnated as a human. The series is a visually rich and emotional fantasy thriller that explores themes of revenge, fate, and redemption."
  },
  {
    id: 51,
    title: "Sisyphus: The Myth",
    platform: "JTBC / Netflix",
    genre: "Sci-Fi / Time Travel Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.0,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "Han Tae-sul, a genius engineer, discovers a shocking truth about his brother's death and a secret time-traveling conspiracy. He is saved by Kang Seo-hae, a warrior from the future who has traveled back in time to protect him and prevent a nuclear apocalypse. The series is a mind-bending sci-fi thriller with a complex plot and a mix of action and romance."
  },
  {
    id: 52,
    title: "SF8",
    platform: "MBC / PlayFlix / Tata Play Binge",
    genre: "Sci-Fi Anthology",
    mustwatch: false,
    year: 2020,
    seasons: 1,
    episodes: 8,
    runtime: "50-60 min",
    popularity: 7.5,
    imdbRating: 7.2,
    hindiDubbed: true,
    description: "SF8 is a South Korean sci-fi anthology series that features eight standalone episodes, each with a different cast and director. The series explores various futuristic and dystopian themes, such as artificial intelligence, virtual reality, robots, and human cloning. It is often compared to 'Black Mirror' and offers a thought-provoking look at the future of technology and its impact on humanity."
  },
  {
    id: 53,
    title: "Alice",
    platform: "SBS / DramaLine / BiliBili",
    genre: "Sci-Fi / Time Travel Mystery",
    mustwatch: false,
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 7.9,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "Park Jin-gyeom, a detective who is apathetic due to a rare birth defect, discovers a time-traveling agency called 'Alice.' He meets a woman named Yoon Tae-yi, a brilliant physicist who looks exactly like his deceased mother. As they work together to uncover the secrets of Alice and his mother's death, they become entangled in a time-bending mystery that could change the course of history."
  },
  {
    id: 54,
    title: "Memories of the Alhambra",
    platform: "tvN / Netflix",
    genre: "AR Sci-Fi / Romance Thriller",
    mustwatch: true,
    year: 2018,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.1,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Yoo Jin-woo, a CEO of an investment firm, travels to Granada, Spain to find the creator of a groundbreaking augmented reality game. He stays at a hostel run by Jung Hee-joo, the game's creator's sister. As he gets more immersed in the game, the line between the virtual world and reality begins to blur, and he is forced to confront a dangerous conspiracy that threatens to consume him."
  },
  {
    id: 55,
    title: "The Silent Sea",
    platform: "Netflix",
    genre: "Sci-Fi / Space Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "40-50 min",
    popularity: 8.6,
    imdbRating: 6.9,
    hindiDubbed: true,
    description: "In a futuristic world suffering from a global water shortage, a team of elite astronauts is sent on a mission to an abandoned research base on the moon. They are tasked with retrieving a mysterious sample, but they soon discover that the base holds a deadly secret and that they are not alone. The series is a tense and atmospheric space thriller that will keep you on the edge of your seat."
  },
  {
    id: 56,
    title: "Dr. Brain",
    platform: "Apple TV+ / Tata Play Binge",
    genre: "Sci-Fi / Psychological Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "45-50 min",
    popularity: 7.7,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "Koh Se-won, a brilliant neuroscientist with a detached personality, is obsessed with brain-sync technology. After his family is killed in a mysterious accident, he uses his technology to access the brains of the deceased and piece together their memories to solve the tragedy. The series is a dark and complex psychological thriller that explores the nature of memory, trauma, and human connection."
  },
  {
    id: 57,
    title: "Twenty-Five Twenty-One",
    platform: "tvN / Netflix",
    genre: "Romance / Coming-of-Age",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.7,
    imdbRating: 8.6,
    hindiDubbed: true,
    description: "Set against the backdrop of the 1998 Asian financial crisis, the series follows the romantic and professional journeys of a high school fencer, Na Hee-do, and a young man, Baek Yi-jin, who is trying to rebuild his life after his family's bankruptcy. Their paths cross as they navigate their dreams, friendships, and first love. The series is a nostalgic and beautiful coming-of-age story that will make you laugh and cry."
  },
  {
    id: 58,
    title: "Our Beloved Summer",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Slice of Life",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Choi Ung, a free-spirited illustrator, and Kook Yeon-soo, a pragmatic public relations expert, were high school sweethearts who broke up with a promise to never see each other again. Ten years later, a documentary they filmed in high school goes viral, and they are forced to reunite for a new one. The series is a charming and realistic romantic comedy that explores the complexities of a long-lost love and the process of finding yourself."
  },
  {
    id: 59,
    title: "Business Proposal",
    platform: "SBS / Netflix",
    genre: "Romantic Comedy / Workplace",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 9.5,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Shin Ha-ri, a food researcher, goes on a blind date disguised as her best friend to scare off a potential suitor. However, the suitor turns out to be her company's CEO, Kang Tae-moo, who is a workaholic and a man of few words. The two enter into a fake dating contract, leading to a series of hilarious and chaotic events. The series is a lighthearted and fun romantic comedy that will make you smile from beginning to end."
  },
  {
    id: 60,
    title: "True Beauty",
    platform: "tvN / Viki / Crunchyroll",
    genre: "Romantic Comedy / High School",
    mustwatch: true,
    year: 2020,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.2,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Lim Ju-kyung, a high school student, is bullied for her appearance. She masters the art of makeup to transform herself and start a new life at a new school. She soon meets Lee Su-ho, a handsome and popular student who has his own hidden past, and Han Seo-jun, a bad boy with a heart of gold. The series is a heartwarming and relatable high school romance that explores themes of self-love, friendship, and inner beauty."
  },
  {
    id: 61,
    title: "Nevertheless",
    platform: "JTBC / Netflix",
    genre: "Romance / Youth Drama",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 10,
    runtime: "50-60 min",
    popularity: 8.8,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "Yoo Na-bi, a heartbroken art student, no longer believes in love. She meets Park Jae-eon, a charming and flirtatious sculptor who doesn't believe in serious relationships. Despite their differences, they enter into a complicated and confusing 'friends with benefits' relationship. The series is a realistic and moody romance that delves into the complexities of modern dating and the struggles of young love."
  },
  {
    id: 62,
    title: "Love Alarm",
    platform: "Netflix",
    genre: "Romance / Sci-Fi",
    mustwatch: false,
    year: 2019,
    seasons: 2,
    episodes: 14,
    runtime: "40-50 min",
    popularity: 8.9,
    imdbRating: 6.8,
    hindiDubbed: true,
    description: "In a world where a mobile app called 'Love Alarm' notifies people if someone within a 10-meter radius has a crush on them, a high school girl named Kim Jo-jo finds herself caught in a love triangle between two best friends, Hwang Sun-oh and Lee Hye-yeong. The series is a futuristic romance that explores the complexities of technology, love, and human relationships in a world where feelings can be quantified."
  },
  {
    id: 63,
    title: "Crash Course in Romance",
    platform: "tvN / Netflix",
    genre: "Romantic Comedy / Family Drama",
    mustwatch: true,
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.1,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Nam Haeng-seon, a former handball player who now runs a side dish shop, decides to enter the highly competitive world of private education to help her daughter. There, she clashes with Choi Chi-yeol, a star math tutor who is known for his cold demeanor but is secretly a kind and caring man. The series is a charming and emotional romantic comedy that also sheds light on the pressures of the South Korean education system."
  },
  {
    id: 64,
    title: "See You in My 19th Life",
    platform: "tvN / Netflix",
    genre: "Fantasy Romance",
    mustwatch: true,
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.7,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Ban Ji-eum has the ability to remember all of her past lives. In her 18th life, she falls in love with a young boy named Moon Seo-ha. After her life is cut short, she is reincarnated as a young woman in her 19th life and is determined to find Seo-ha and reconnect with him. The series is a beautiful and magical romance that explores the concepts of reincarnation, fate, and eternal love."
  },
  {
    id: 65,
    title: "King the Land",
    platform: "JTBC / Netflix",
    genre: "Romantic Comedy / Chaebol Romance",
    mustwatch: true,
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.3,
    imdbRating: 7.4,
    hindiDubbed: true,
    description: "Gu Won, a wealthy chaebol heir, is a cold and arrogant man who hates fake smiles. He is sent to work at his family's hotel, where he meets Cheon Sa-rang, a cheerful and hardworking employee who is always smiling. The two initially clash, but they soon find themselves falling in love. The series is a classic romantic comedy with a lot of charm and a cute love story."
  },
  {
    id: 66,
    title: "My Demon",
    platform: "SBS / Netflix",
    genre: "Fantasy Romance / Supernatural",
    mustwatch: true,
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Do Do-hee, a cold and cynical heiress, enters into a contract marriage with Jung Gu-won, a powerful demon who has temporarily lost his powers. She is forced to protect him and help him get his powers back, and in the process, they fall in love. The series is a fun and stylish fantasy romance with a unique premise and a lot of sizzling chemistry between the leads."
  },
  {
    id: 67,
    title: "Castaway Diva",
    platform: "tvN / Netflix",
    genre: "Romance / Music / Slice of Life",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.5,
    imdbRating: 7.9,
    hindiDubbed: true,
    description: "Seo Mok-ha, a young and talented singer, is stranded on a deserted island after a boating accident. She is rescued 15 years later and returns to a completely changed world, where she is determined to pursue her dream of becoming a famous singer. With the help of two brothers, she navigates the challenges of her new life and confronts the past she left behind. The series is a heartfelt and inspiring musical drama."
  },
  {
    id: 68,
    title: "Doona!",
    platform: "Netflix",
    genre: "Romance / Idol Drama",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 9,
    runtime: "40-50 min",
    popularity: 8.8,
    imdbRating: 7.2,
    hindiDubbed: true,
    description: "Lee Won-jun, a kindhearted college student, moves into a sharehouse and discovers that his roommate is Lee Doona, a former K-pop idol who suddenly retired from the spotlight. The two of them develop a complicated relationship as they navigate their different worlds and personal struggles. The series is a romantic and emotional drama that explores the pressures of fame and the search for a normal life."
  },
  {
    id: 69,
    title: "Daily Dose of Sunshine",
    platform: "Netflix",
    genre: "Medical / Healing Drama",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.6,
    imdbRating: 8.3,
    hindiDubbed: true,
    description: "Jung Da-eun, a kind and compassionate nurse, is transferred to the neuropsychiatry department of a hospital. She struggles with the challenges of her new job but works tirelessly to bring hope and comfort to her patients who are suffering from various mental health issues. The series is a moving and insightful drama that sheds light on the importance of mental health and the struggles of those who work in the field."
  },
  {
    id: 70,
    title: "Behind Your Touch",
    platform: "JTBC / Netflix",
    genre: "Supernatural / Crime Comedy",
    mustwatch: false,
    year: 2023,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.4,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "Bong Ye-bun, a quirky veterinarian, gains the ability to see a person's or animal's past by touching their rear end. She teams up with Moon Jang-yeol, a hot-headed detective who has been demoted to a small town, to solve petty crimes. Their unique partnership takes a dark turn when they get entangled in a serious serial killer case that tests their powers and their trust in each other."
  },
  {
    id: 71,
    title: "Reborn Rich",
    platform: "JTBC / Disney+ / Viki",
    genre: "Fantasy Revenge / Corporate Drama",
    mustwatch: true,
    year: 2022,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.5,
    imdbRating: 8.1,
    hindiDubbed: true,
    description: "Yoon Hyun-woo, a loyal and hardworking employee of a powerful chaebol family, is betrayed and murdered. He is then reincarnated as the family's youngest son, Jin Do-jun, and uses his knowledge of the future to plot his revenge and take over the company. The series is a gripping corporate revenge thriller that explores themes of power, family, and the dark side of wealth."
  },
  {
    id: 72,
    title: "The Veil",
    platform: "MBC / Viki / BiliBili",
    genre: "Spy Thriller / Action",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    popularity: 8.4,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Han Ji-hyuk, a top National Intelligence Service (NIS) agent, returns after a year-long disappearance with no memory of what happened to him or why he went missing. He is determined to find the traitor within the NIS who betrayed him, but he soon discovers that the truth is far more complex and dangerous than he could have ever imagined. The series is an intense and suspenseful spy thriller with a lot of action and a compelling mystery at its core."
  },
  {
    id: 73,
    title: "Taxi Driver",
    platform: "SBS / Netflix / Amazon miniTV",
    genre: "Action / Vigilante Justice",
    mustwatch: true,
    year: 2021,
    seasons: 2,
    episodes: 32,
    runtime: "60-70 min",
    popularity: 9.2,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Kim Do-gi, a former special forces officer, works for a mysterious organization called 'Rainbow Taxi.' The company offers a unique service: they help victims who have been failed by the legal system get revenge on their tormentors. With his team of skilled professionals, Do-gi takes on various cases, from school bullying to corporate corruption, and delivers justice in his own unique way. The series is a thrilling and satisfying vigilante justice drama."
  },
  {
    id: 74,
    title: "Boys Over Flowers",
    platform: "Netflix",
    genre: "Romantic Comedy",
    mustwatch: false,
    year: 2009,
    seasons: 1,
    episodes: 25,
    runtime: "60-70 min",
    popularity: 8.7,
    imdbRating: 7.8,
    hindiDubbed: true,
    description: "Geum Jan-di, a cheerful and hardworking girl from a poor family, gets a scholarship to a prestigious high school for the rich. There, she clashes with the school's most popular and powerful group, the F4, led by the arrogant Gu Jun-pyo. Despite their initial animosity, Jan-di and Jun-pyo fall in love, leading to a classic romance filled with drama, friendships, and a lot of humor."
  },
  {
    id: 75,
    title: "Healer",
    platform: "KBS2 / Netflix",
    genre: "Romantic Thriller / Action",
    mustwatch: true,
    year: 2014,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 9.0,
    imdbRating: 8.5,
    hindiDubbed: true,
    description: "Seo Jung-hoo, a talented night courier known as 'Healer,' takes on a job to protect a young online reporter, Chae Young-shin. As he gets closer to her, he begins to unravel a decades-old conspiracy that links them both to a past tragedy. The series is a perfect blend of romance, action, and mystery, with a charming cast and a compelling plot that keeps you engaged from beginning to end."
  },
  {
    id: 76,
    title: "Pinocchio",
    platform: "SBS / Viki",
    genre: "Romantic Legal Drama",
    mustwatch: false,
    year: 2014,
    seasons: 1,
    episodes: 20,
    runtime: "60-70 min",
    popularity: 8.5,
    imdbRating: 8.0,
    hindiDubbed: true,
    description: "Choi In-ha has 'Pinocchio syndrome,' a condition that makes her hiccup uncontrollably whenever she tells a lie. She becomes a reporter, determined to fight for the truth, and teams up with a fellow reporter who has a mysterious past. Together, they work to expose the corruption and lies within the media industry and uncover the truth behind a past tragedy that ruined their families. The series is a thoughtful and emotional look at the power of the media and the importance of truth."
  },
  {
    id: 77,
    title: "Strong Woman Do Bong Soon",
    platform: "JTBC / Netflix",
    genre: "Romantic Comedy / Superhero",
    mustwatch: true,
    year: 2017,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 9.3,
    imdbRating: 8.2,
    hindiDubbed: true,
    description: "Do Bong-soon is a young woman born with superhuman strength, a secret she must keep hidden from the world. She is hired as a bodyguard by Ahn Min-hyuk, the eccentric CEO of a gaming company who is receiving death threats. The two of them, along with a detective, work to catch the mysterious culprit while falling in love. The series is a charming and funny romantic comedy with a unique superhero twist."
  },
  {
    id: 78,
    title: "Weightlifting Fairy Kim Bok-joo",
    platform: "MBC / Viki",
    genre: "Romantic Comedy / Sports",
    mustwatch: true,
    year: 2016,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.9,
    imdbRating: 8.4,
    hindiDubbed: true,
    description: "Kim Bok-joo, a talented female weightlifter, is trying to achieve her dreams while navigating the complexities of young love. She develops an unlikely friendship with a popular swimmer, Jung Joon-hyung, and their relationship blossoms into a heartwarming romance. The series is a lighthearted and relatable coming-of-age story that celebrates the power of friendship, dreams, and self-acceptance."
  },
  {
    id: 79,
    title: "You're Beautiful",
    platform: "SBS / Viki",
    genre: "Romantic Comedy / Idol Drama",
    mustwatch: false,
    year: 2009,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    popularity: 8.2,
    imdbRating: 7.7,
    hindiDubbed: true,
    description: "Go Mi-nyeo, a kind and innocent nun-in-training, is forced to impersonate her twin brother, Go Mi-nam, and join a popular boy band to save his career. She must navigate the world of K-pop, dealing with her bandmates' personalities and a growing romance with the band's leader. The series is a fun and heartwarming romantic comedy that showcases the struggles and triumphs of being a K-pop idol."
  },
  {
    id: 80,
    title: "The Silent Sea",
    platform: "Netflix",
    genre: "Sci-Fi / Space Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 8,
    runtime: "40-50 min",
    popularity: 8.6,
    imdbRating: 6.9,
    hindiDubbed: true,
    description: "In a futuristic world suffering from a global water shortage, a team of elite astronauts is sent on a mission to an abandoned research base on the moon. They are tasked with retrieving a mysterious sample, but they soon discover that the base holds a deadly secret and that they are not alone. The series is a tense and atmospheric space thriller that will keep you on the edge of your seat."
  },
  {
    id: 81,
    title: "Dr. Brain",
    platform: "Apple TV+ / Tata Play Binge",
    genre: "Sci-Fi / Psychological Thriller",
    mustwatch: false,
    year: 2021,
    seasons: 1,
    episodes: 6,
    runtime: "45-50 min",
    popularity: 7.7,
    imdbRating: 7.1,
    hindiDubbed: true,
    description: "Koh Se-won, a brilliant neuroscientist with a detached personality, is obsessed with brain-sync technology. After his family is killed in a mysterious accident, he uses his technology to access the brains of the deceased and piece together their memories to solve the tragedy. The series is a dark and complex psychological thriller that explores the nature of memory, trauma, and human connection."
  },
  {
    id: 82,
    title: "Lovely Runner",
    platform: "tvN / Viki",
    genre: "Time-travel, Romantic Comedy",
    mustwatch: true,
    year: 2024,
    popularity: 9.5,
    imdbRating: 8.9,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    description: "Im Sol, a devoted fan, is devastated by the sudden death of her favorite K-pop idol, Ryu Sun-jae. By a twist of fate, she is magically transported back to their high school days, 15 years in the past. Determined to prevent his tragic end, she tries to change his future, but her actions create a series of unexpected and humorous consequences. The series is a heartwarming and fun time-travel romance with a lot of heart, praised for its well-developed story and engaging characters."
  },
  {
    id: 83,
    title: "Marry My Husband",
    platform: "tvN / Amazon Prime Video",
    genre: "Revenge, Time-travel",
    mustwatch: true,
    year: 2024,
    popularity: 9.4,
    imdbRating: 8.4,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    description: "Kang Ji-won, a woman suffering from a terminal illness, is murdered by her unfaithful husband and her best friend after she catches them having an affair. She is miraculously sent back 10 years in the past with the knowledge of her future. Armed with this second chance, she devises a meticulous plan to get her revenge by making her best friend marry her husband instead, ensuring they suffer the same miserable fate she did."
  },
  {
    id: 84,
    title: "The Atypical Family",
    platform: "JTBC / Netflix",
    genre: "Fantasy, Melodrama",
    mustwatch: false,
    year: 2024,
    popularity: 8.8,
    imdbRating: 7.7,
    seasons: 1,
    episodes: 12,
    runtime: "60-70 min",
    description: "The Bok family has inherited unique superpowers, but modern-day challenges like depression, bulimia, and social media addiction are causing them to lose their abilities. Their lives are changed when a mysterious woman, Do Da-hae, with a secret of her own, enters their home. The series explores the intricate dynamics of a family struggling with both their extraordinary gifts and very human flaws, with a mysterious and melancholic quality that makes it a unique and compelling watch."
  },
  {
    id: 85,
    title: "A Killer Paradox",
    platform: "Netflix",
    genre: "Thriller, Dark Comedy",
    mustwatch: false,
    year: 2024,
    popularity: 8.5,
    imdbRating: 7.2,
    seasons: 1,
    episodes: 8,
    runtime: "45-50 min",
    description: "A college student accidentally kills a man and discovers that his victim was a serial killer. He soon realizes he has a supernatural ability to identify 'bad people' who deserve to die. This leads him on a dark path as he becomes a vigilante, but a persistent detective is hot on his trail. The show is a fast-paced and darkly humorous thriller that raises moral questions about justice and who has the right to decide a person's fate."
  },
  {
    id: 86,
    title: "Captivating the King",
    platform: "tvN / Netflix",
    genre: "Historical, Political",
    mustwatch: false,
    year: 2024,
    popularity: 8.4,
    imdbRating: 7.8,
    seasons: 1,
    episodes: 16,
    runtime: "60-70 min",
    description: "Set in the Joseon dynasty, this historical drama tells the story of a lonely and powerful king who is constantly entangled in political intrigue. He meets a mysterious female Go player who is secretly seeking revenge against him. Their connection grows into a complex relationship of love, betrayal, and loyalty amidst the political turmoil of the palace."
  },
  {
    id: 87,
    title: "Death's Game",
    platform: "TVING / Amazon Prime Video",
    genre: "Fantasy, Thriller",
    mustwatch: true,
    year: 2023,
    popularity: 9.6,
    imdbRating: 8.5,
    seasons: 1,
    episodes: 8,
    runtime: "60-70 min",
    description: "Choi Yee-jae, a man who has failed at everything in life, decides to take his own life. As a punishment for his recklessness, Death forces him to experience death 12 more times through different people. If he can survive in any of these new bodies, he will be allowed to live. This intense and emotional series is a profound exploration of life, death, and second chances."
  },
  {
    id: 88,
    title: "Sweet Home Season 2",
    platform: "Netflix",
    genre: "Apocalyptic Horror / Monster",
    mustwatch: false,
    year: 2023,
    popularity: 8.5,
    imdbRating: 6.6,
    seasons: 2,
    episodes: 8,
    runtime: "40-50 min",
    description: "The survivors of Green Home, including Hyun-soo, are forced to leave their shelter and face a new, even more dangerous world. As they try to find a safe haven, they encounter new kinds of monsters and learn more about the true nature of the virus. The series continues the story of survival in a world where humanity is on the brink of extinction."
  },
  {
    id: 89,
    title: "Gyeongseong Creature",
    platform: "Netflix",
    genre: "Historical Thriller / Sci-Fi",
    mustwatch: false,
    year: 2023,
    popularity: 8.7,
    imdbRating: 7.3,
    seasons: 1,
    episodes: 10,
    runtime: "60-70 min",
    description: "Set in 1945 Gyeongseong, a wealthy pawnshop owner and a talented sleuth team up to investigate a series of mysterious disappearances. They soon discover a dark secret hidden beneath a hospital, where a terrifying monster is being created through a series of human experiments. The series is a thrilling combination of historical drama and monster horror."
  }
];
