window.movies = [
  {
    id: 1,
    title: "The Godfather",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1972,
    director: "Francis Ford Coppola",
    mainCast: "Marlon Brando, Al Pacino, James Caan, Robert Duvall",
    genre: "Crime, Drama",
    synopsis: "Set in the 1940s, The Godfather follows the powerful Italian-American crime family of Don Vito Corleone. When the aging patriarch is nearly assassinated, his reluctant son Michael steps into the world of organized crime. The film explores themes of power, family, loyalty, and betrayal, ultimately charting Michael’s transformation from war hero to ruthless mafia boss.",
    awards: "Academy Award for Best Picture, Best Actor (Marlon Brando), Best Adapted Screenplay. Nominated for multiple Oscars.",
    rating: { imdb: 9.2, rottenTomatoes: 97 },
    countryOfOrigin: "USA",
    runtime: "2 hr 55 min",
    sequelPrequelAvailable: true,
    tags: ["mafia", "crime", "classic", "family", "power", "betrayal"]
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1994,
    director: "Frank Darabont",
    mainCast: "Tim Robbins, Morgan Freeman, Bob Gunton",
    genre: "Drama",
    synopsis: "Wrongly convicted of murder, banker Andy Dufresne is sentenced to life in Shawshank prison. Over the decades, he forms a deep friendship with fellow inmate Red and quietly plans an escape that no one could imagine. The film is an inspiring story about hope, perseverance, and the resilience of the human spirit.",
    awards: "Nominated for 7 Academy Awards including Best Picture and Best Actor (Morgan Freeman).",
    rating: { imdb: 9.3, rottenTomatoes: 98 },
    countryOfOrigin: "USA",
    runtime: "2 hr 22 min",
    sequelPrequelAvailable: false,
    tags: ["prison", "friendship", "hope", "escape", "classic"]
  },
  {
    id: 3,
    title: "The Dark Knight",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2008,
    director: "Christopher Nolan",
    mainCast: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    genre: "Action, Crime, Drama",
    synopsis: "Batman faces his greatest psychological and physical test when the Joker unleashes chaos in Gotham City. As the line between hero and vigilante blurs, the film explores morality, justice, and the price of order. Heath Ledger’s iconic performance as the Joker redefined the comic book villain archetype forever.",
    awards: "Academy Awards for Best Supporting Actor (Heath Ledger) and Best Sound Editing. Multiple nominations.",
    rating: { imdb: 9.0, rottenTomatoes: 94 },
    countryOfOrigin: "USA",
    runtime: "2 hr 32 min",
    sequelPrequelAvailable: true,
    tags: ["batman", "joker", "gotham", "crime", "dark", "superhero"]
  },
  {
    id: 4,
    title: "Inception",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2010,
    director: "Christopher Nolan",
    mainCast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    genre: "Sci-Fi, Thriller",
    synopsis: "Dom Cobb, a thief who specializes in stealing secrets from deep within the subconscious, is offered a chance to regain his old life if he can achieve the impossible: inception. Cobb and his team dive into multiple dream layers, blurring the lines between reality and illusion in this visually stunning and mind-bending story.",
    awards: "Academy Awards for Best Cinematography, Best Visual Effects, Best Sound Mixing, Best Sound Editing.",
    rating: { imdb: 8.8, rottenTomatoes: 87 },
    countryOfOrigin: "USA",
    runtime: "2 hr 28 min",
    sequelPrequelAvailable: false,
    tags: ["dreams", "heist", "mind-bending", "sci-fi", "psychological"]
  },
  {
    id: 5,
    title: "Parasite",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2019,
    director: "Bong Joon-ho",
    mainCast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
    genre: "Thriller, Drama",
    synopsis: "Parasite tells the story of the Kim family, who live in poverty in a semi-basement apartment in Seoul. They cleverly infiltrate the wealthy Park household by posing as skilled workers. However, their deception spirals into chaos when secrets from the Parks’ home come to light, leading to shocking and tragic consequences.",
    awards: "Academy Award for Best Picture, Best Director, Best International Feature, Best Original Screenplay.",
    rating: { imdb: 8.6, rottenTomatoes: 99 },
    countryOfOrigin: "South Korea",
    runtime: "2 hr 12 min",
    sequelPrequelAvailable: false,
    tags: ["class divide", "satire", "thriller", "social commentary", "Korean cinema"]
  },
  {
    id: 6,
    title: "Schindler’s List",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1993,
    director: "Steven Spielberg",
    mainCast: "Liam Neeson, Ben Kingsley, Ralph Fiennes",
    genre: "Drama, History, War",
    synopsis: "Based on true events, the film follows Oskar Schindler, a German businessman who saves the lives of more than a thousand Polish Jews during the Holocaust by employing them in his factories. It is a haunting exploration of humanity, morality, and redemption in the darkest chapter of history.",
    awards: "Academy Awards for Best Picture, Best Director, Best Adapted Screenplay, and four others.",
    rating: { imdb: 9.0, rottenTomatoes: 98 },
    countryOfOrigin: "USA",
    runtime: "3 hr 15 min",
    sequelPrequelAvailable: false,
    tags: ["holocaust", "ww2", "redemption", "true story", "historical"]
  },
  {
    id: 7,
    title: "Fight Club",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1999,
    director: "David Fincher",
    mainCast: "Edward Norton, Brad Pitt, Helena Bonham Carter",
    genre: "Drama, Thriller",
    synopsis: "An insomniac office worker and a mysterious soap salesman form an underground fight club that evolves into something much more. As identity and sanity blur, the film delivers a raw critique of consumerism, masculinity, and society’s hollow values.",
    awards: "Nominated for Academy Award for Best Sound Editing. Later became a cult classic.",
    rating: { imdb: 8.8, rottenTomatoes: 79 },
    countryOfOrigin: "USA",
    runtime: "2 hr 19 min",
    sequelPrequelAvailable: false,
    tags: ["psychological", "cult classic", "consumerism", "masculinity", "thriller"]
  },
  {
    id: 8,
    title: "Forrest Gump",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1994,
    director: "Robert Zemeckis",
    mainCast: "Tom Hanks, Robin Wright, Gary Sinise",
    genre: "Drama, Romance",
    synopsis: "Forrest Gump, a man with a low IQ but pure heart, inadvertently influences major historical events in 20th-century America. His journey through life is one of love, loss, perseverance, and destiny, narrated with warmth and innocence.",
    awards: "Academy Awards for Best Picture, Best Director, Best Actor (Tom Hanks), and three more.",
    rating: { imdb: 8.8, rottenTomatoes: 71 },
    countryOfOrigin: "USA",
    runtime: "2 hr 22 min",
    sequelPrequelAvailable: false,
    tags: ["drama", "romance", "history", "life journey", "classic"]
  },
  {
    id: 9,
    title: "Pulp Fiction",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1994,
    director: "Quentin Tarantino",
    mainCast: "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    genre: "Crime, Drama",
    synopsis: "Tarantino’s iconic nonlinear narrative weaves together the lives of mobsters, boxers, and criminals in Los Angeles. With dark humor, memorable dialogues, and shocking violence, Pulp Fiction remains a landmark in modern cinema storytelling.",
    awards: "Academy Award for Best Original Screenplay. Palme d'Or at Cannes Film Festival.",
    rating: { imdb: 8.9, rottenTomatoes: 92 },
    countryOfOrigin: "USA",
    runtime: "2 hr 34 min",
    sequelPrequelAvailable: false,
    tags: ["tarantino", "crime", "dark humor", "nonlinear", "cult classic"]
  },
  {
    id: 10,
    title: "Interstellar",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2014,
    director: "Christopher Nolan",
    mainCast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    genre: "Sci-Fi, Drama, Adventure",
    synopsis: "In a dystopian future where Earth is becoming uninhabitable, a group of astronauts travels through a wormhole in search of a new home for humanity. The film explores time dilation, black holes, and the endurance of love across dimensions.",
    awards: "Academy Award for Best Visual Effects. Multiple nominations for score, sound, and production design.",
    rating: { imdb: 8.7, rottenTomatoes: 73 },
    countryOfOrigin: "USA",
    runtime: "2 hr 49 min",
    sequelPrequelAvailable: false,
    tags: ["space", "black holes", "love", "sci-fi", "nolan", "time"]
  },
  {
    id: 11,
    title: "Gladiator",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2000,
    director: "Ridley Scott",
    mainCast: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
    genre: "Action, Drama, History",
    synopsis: "After being betrayed and having his family murdered, Roman general Maximus is forced into slavery. He rises as a gladiator in the Colosseum, fighting for honor and vengeance against the corrupt emperor Commodus. A tale of loyalty, revenge, and redemption set in the Roman Empire.",
    awards: "Academy Awards for Best Picture, Best Actor (Russell Crowe), and three others.",
    rating: { imdb: 8.5, rottenTomatoes: 79 },
    countryOfOrigin: "USA",
    runtime: "2 hr 35 min",
    sequelPrequelAvailable: false,
    tags: ["rome", "gladiator", "revenge", "honor", "epic"]
  },
  {
    id: 12,
    0title: "Saving Private Ryan",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1998,
    director: "Steven Spielberg",
    mainCast: "Tom Hanks, Matt Damon, Tom Sizemore",
    genre: "War, Drama, Action",
    synopsis: "During World War II, Captain Miller leads a group of U.S. soldiers behind enemy lines to retrieve Private James Ryan, whose brothers have all been killed in combat. The film is known for its realistic portrayal of the Normandy landings and the moral questions of war.",
    awards: "Academy Awards for Best Director, Best Cinematography, Best Editing, and two others.",
    rating: { imdb: 8.6, rottenTomatoes: 94 },
    countryOfOrigin: "USA",
    runtime: "2 hr 49 min",
    sequelPrequelAvailable: false,
    tags: ["ww2", "sacrifice", "war", "brotherhood", "history"]
  },
  {
    id: 13,
    title: "Braveheart",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1995,
    director: "Mel Gibson",
    mainCast: "Mel Gibson, Sophie Marceau, Patrick McGoohan",
    genre: "War, Biography, Drama",
    synopsis: "Scottish warrior William Wallace leads his countrymen in a rebellion against English oppression in the 13th century. Driven by love and vengeance, Wallace’s journey is one of freedom, betrayal, and sacrifice.",
    awards: "Academy Awards for Best Picture, Best Director, and three others.",
    rating: { imdb: 8.3, rottenTomatoes: 76 },
    countryOfOrigin: "USA",
    runtime: "2 hr 58 min",
    sequelPrequelAvailable: false,
    tags: ["scotland", "freedom", "epic", "war", "revolution"]
  },
  {
    id: 14,
    title: "Titanic",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1997,
    director: "James Cameron",
    mainCast: "Leonardo DiCaprio, Kate Winslet, Billy Zane",
    genre: "Romance, Drama, History",
    synopsis: "A young aristocrat falls in love with a poor artist aboard the ill-fated R.M.S. Titanic. Their forbidden romance unfolds against the backdrop of one of the greatest maritime disasters in history.",
    awards: "11 Academy Awards including Best Picture, Best Director, Best Original Song.",
    rating: { imdb: 7.9, rottenTomatoes: 88 },
    countryOfOrigin: "USA",
    runtime: "3 hr 14 min",
    sequelPrequelAvailable: false,
    tags: ["romance", "ship", "disaster", "history", "love story"]
  },
  {
    id: 15,
    title: "Avatar",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2009,
    director: "James Cameron",
    mainCast: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
    genre: "Sci-Fi, Adventure, Fantasy",
    synopsis: "Set in the lush alien world of Pandora, a paraplegic marine becomes part of the Na’vi people through an avatar body. As he grows attached to their culture, he must choose between human greed and protecting the planet.",
    awards: "Academy Awards for Best Cinematography, Best Visual Effects, Best Art Direction.",
    rating: { imdb: 7.9, rottenTomatoes: 82 },
    countryOfOrigin: "USA",
    runtime: "2 hr 42 min",
    sequelPrequelAvailable: true,
    tags: ["pandora", "alien", "sci-fi", "environment", "epic"]
  },
  {
    id: 16,
    title: "Oldboy",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2003,
    director: "Park Chan-wook",
    mainCast: "Choi Min-sik, Yoo Ji-tae, Kang Hye-jung",
    genre: "Thriller, Mystery, Action",
    synopsis: "A man is inexplicably imprisoned for 15 years, then suddenly released. He embarks on a quest for vengeance, only to uncover a shocking secret that redefines his past and future. A gripping tale of revenge and twisted justice.",
    awards: "Grand Prix at Cannes Film Festival 2004.",
    rating: { imdb: 8.4, rottenTomatoes: 82 },
    countryOfOrigin: "South Korea",
    runtime: "2 hr",
    sequelPrequelAvailable: false,
    tags: ["revenge", "thriller", "korean cinema", "dark", "mystery"]
  },
  {
    id: 17,
    title: "Memories of Murder",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2003,
    director: "Bong Joon-ho",
    mainCast: "Song Kang-ho, Kim Sang-kyung, Roe-ha Kim",
    genre: "Crime, Drama, Thriller",
    synopsis: "Based on Korea’s first serial murders, the film follows two detectives trying to solve a string of brutal killings in a rural town. Their frustration grows as the case remains unsolved, reflecting a haunting reality.",
    awards: "Multiple Korean Film Awards; critical acclaim worldwide.",
    rating: { imdb: 8.1, rottenTomatoes: 95 },
    countryOfOrigin: "South Korea",
    runtime: "2 hr 11 min",
    sequelPrequelAvailable: false,
    tags: ["serial killer", "detectives", "true crime", "unsolved", "thriller"]
  },
  {
    id: 18,
    title: "Train to Busan",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2016,
    director: "Yeon Sang-ho",
    mainCast: "Gong Yoo, Ma Dong-seok, Jung Yu-mi",
    genre: "Horror, Action, Thriller",
    synopsis: "Passengers on a train from Seoul to Busan fight for survival as a zombie outbreak consumes South Korea. The gripping story blends high-octane action with emotional family drama.",
    awards: "Best Director at Korean Film Awards. Multiple nominations internationally.",
    rating: { imdb: 7.6, rottenTomatoes: 94 },
    countryOfOrigin: "South Korea",
    runtime: "1 hr 58 min",
    sequelPrequelAvailable: true,
    tags: ["zombie", "survival", "thriller", "family", "apocalypse"]
  },
  {
    id: 19,
    title: "A Separation",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2011,
    director: "Asghar Farhadi",
    mainCast: "Peyman Moaadi, Leila Hatami, Sareh Bayat",
    genre: "Drama, Family",
    synopsis: "An Iranian couple struggles with a decision to separate. When the husband hires a caretaker for his father, a series of moral and legal conflicts emerge. A deeply layered story about family, justice, and class.",
    awards: "Academy Award for Best Foreign Language Film.",
    rating: { imdb: 8.3, rottenTomatoes: 99 },
    countryOfOrigin: "Iran",
    runtime: "2 hr 3 min",
    sequelPrequelAvailable: false,
    tags: ["family", "drama", "iranian cinema", "morality", "conflict"]
  },
  {
    id: 20,
    title: "Pan’s Labyrinth",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2006,
    director: "Guillermo del Toro",
    mainCast: "Ivana Baquero, Sergi López, Maribel Verdú",
    genre: "Fantasy, Drama, War",
    synopsis: "In fascist Spain 1944, young Ofelia discovers a mysterious labyrinth and meets a faun who sets her on a dangerous path of magical trials. Blending harsh wartime reality with dark fantasy, the film is both enchanting and tragic.",
    awards: "Academy Awards for Best Cinematography, Best Art Direction, Best Makeup.",
    rating: { imdb: 8.2, rottenTomatoes: 95 },
    countryOfOrigin: "Spain, Mexico",
    runtime: "1 hr 59 min",
    sequelPrequelAvailable: false,
    tags: ["fantasy", "war", "fairy tale", "dark", "labyrinth"]
  },
  window.movies.push(
  {
    id: 21,
    title: "Amélie",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2001,
    director: "Jean-Pierre Jeunet",
    mainCast: "Audrey Tautou, Mathieu Kassovitz, Rufus",
    genre: "Romance, Comedy, Drama",
    synopsis: "Amélie is a shy waitress in Paris who decides to secretly improve the lives of people around her through small acts of kindness. While helping others find happiness, she discovers love and meaning in her own life. A whimsical and visually stunning French classic.",
    awards: "5 Academy Award nominations including Best Foreign Language Film.",
    rating: { imdb: 8.3, rottenTomatoes: 89 },
    countryOfOrigin: "France",
    runtime: "2 hr 2 min",
    sequelPrequelAvailable: false,
    tags: ["paris", "romance", "whimsical", "comedy-drama", "french cinema"]
  },
  {
    id: 22,
    title: "The Intouchables",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2011,
    director: "Olivier Nakache, Éric Toledano",
    mainCast: "François Cluzet, Omar Sy, Anne Le Ny",
    genre: "Comedy, Drama, Biography",
    synopsis: "A wealthy quadriplegic man hires a young man from the projects to be his caregiver. Despite their differences, an unlikely friendship blossoms, proving the healing power of humor, trust, and human connection.",
    awards: "Nominated for Golden Globe for Best Foreign Language Film. Won multiple César Awards.",
    rating: { imdb: 8.5, rottenTomatoes: 75 },
    countryOfOrigin: "France",
    runtime: "1 hr 52 min",
    sequelPrequelAvailable: false,
    tags: ["friendship", "inspirational", "true story", "france", "feel-good"]
  },
  {
    id: 23,
    title: "City of God",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2002,
    director: "Fernando Meirelles, Kátia Lund",
    mainCast: "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen",
    genre: "Crime, Drama",
    synopsis: "Based on real events, the film chronicles the rise of organized crime in the favelas of Rio de Janeiro during the 1960s and 1970s. It follows the lives of two boys: one who becomes a photographer, the other a drug lord. A raw and unflinching look at violence and poverty.",
    awards: "4 Academy Award nominations including Best Director and Best Adapted Screenplay.",
    rating: { imdb: 8.6, rottenTomatoes: 91 },
    countryOfOrigin: "Brazil",
    runtime: "2 hr 10 min",
    sequelPrequelAvailable: false,
    tags: ["rio", "crime", "gangs", "poverty", "brazilian cinema"]
  },
  {
    id: 24,
    title: "Life Is Beautiful",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1997,
    director: "Roberto Benigni",
    mainCast: "Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini",
    genre: "Drama, Comedy, War",
    synopsis: "A charming man wins the heart of the woman he loves and starts a family. When they are deported to a Nazi concentration camp, he uses humor and imagination to shield his young son from the horrors of war. A deeply moving story of love, hope, and sacrifice.",
    awards: "Academy Awards for Best Actor, Best Foreign Language Film, Best Original Score.",
    rating: { imdb: 8.6, rottenTomatoes: 81 },
    countryOfOrigin: "Italy",
    runtime: "1 hr 56 min",
    sequelPrequelAvailable: false,
    tags: ["ww2", "holocaust", "father-son", "italian cinema", "hope"]
  },
  {
    id: 25,
    title: "Cinema Paradiso",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 1988,
    director: "Giuseppe Tornatore",
    mainCast: "Philippe Noiret, Enzo Cannavale, Antonella Attili",
    genre: "Drama, Romance",
    synopsis: "A filmmaker recalls his childhood in a Sicilian village and the friendship he shared with the local cinema’s projectionist. A nostalgic love letter to movies and the power of cinema to shape lives.",
    awards: "Academy Award for Best Foreign Language Film.",
    rating: { imdb: 8.5, rottenTomatoes: 90 },
    countryOfOrigin: "Italy",
    runtime: "2 hr 4 min",
    sequelPrequelAvailable: false,
    tags: ["cinema", "nostalgia", "childhood", "italy", "friendship"]
  },
  {
    id: 26,
    title: "Rashomon",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 1950,
    director: "Akira Kurosawa",
    mainCast: "Toshirô Mifune, Machiko Kyô, Masayuki Mori",
    genre: "Drama, Mystery",
    synopsis: "A crime is described in contradictory ways by four witnesses, exposing the elusiveness of truth and human perception. Kurosawa’s masterpiece introduced the world to Japanese cinema with its innovative storytelling.",
    awards: "Golden Lion at Venice Film Festival. Honorary Academy Award.",
    rating: { imdb: 8.2, rottenTomatoes: 98 },
    countryOfOrigin: "Japan",
    runtime: "1 hr 28 min",
    sequelPrequelAvailable: false,
    tags: ["truth", "perception", "crime", "japanese cinema", "classic"]
  },
  {
    id: 27,
    title: "Seven Samurai",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1954,
    director: "Akira Kurosawa",
    mainCast: "Toshirô Mifune, Takashi Shimura, Keiko Tsushima",
    genre: "Action, Drama, Adventure",
    synopsis: "When a poor village is threatened by bandits, they hire seven ronin (masterless samurai) to protect them. An epic story of honor, sacrifice, and heroism that influenced countless films worldwide.",
    awards: "Nominated for 2 Academy Awards. Won Silver Lion at Venice Film Festival.",
    rating: { imdb: 8.6, rottenTomatoes: 100 },
    countryOfOrigin: "Japan",
    runtime: "3 hr 27 min",
    sequelPrequelAvailable: false,
    tags: ["samurai", "honor", "japan", "epic", "classic"]
  },
  {
    id: 28,
    title: "Spirited Away",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2001,
    director: "Hayao Miyazaki",
    mainCast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
    genre: "Animation, Fantasy, Adventure",
    synopsis: "A 10-year-old girl stumbles into a magical world where humans are turned into animals and spirits rule. She must work in a bathhouse for spirits while searching for a way to free her parents and return home.",
    awards: "Academy Award for Best Animated Feature. Golden Bear at Berlin Film Festival.",
    rating: { imdb: 8.6, rottenTomatoes: 97 },
    countryOfOrigin: "Japan",
    runtime: "2 hr 5 min",
    sequelPrequelAvailable: false,
    tags: ["anime", "fantasy", "spirits", "ghibli", "japanese animation"]
  },
  {
    id: 29,
    title: "Your Name",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2016,
    director: "Makoto Shinkai",
    mainCast: "Ryunosuke Kamiki, Mone Kamishiraishi",
    genre: "Animation, Romance, Fantasy",
    synopsis: "Two teenagers mysteriously begin swapping bodies despite living in different parts of Japan. As they grow closer, they race against time to change fate and prevent disaster. A breathtaking anime romance.",
    awards: "Japan Academy Prize for Best Screenplay. Multiple international awards.",
    rating: { imdb: 8.4, rottenTomatoes: 98 },
    countryOfOrigin: "Japan",
    runtime: "1 hr 46 min",
    sequelPrequelAvailable: false,
    tags: ["anime", "romance", "fantasy", "body-swap", "japan"]
  },
  {
    id: 30,
    title: "Sholay",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 1975,
    director: "Ramesh Sippy",
    mainCast: "Dharmendra, Amitabh Bachchan, Hema Malini, Amjad Khan",
    genre: "Action, Adventure, Drama",
    synopsis: "Two criminals, Jai and Veeru, are hired by a retired police officer to capture the ruthless bandit Gabbar Singh. Filled with action, memorable dialogues, and legendary characters, Sholay is considered India’s greatest blockbuster.",
    awards: "Filmfare Award for Best Editing. Multiple nominations.",
    rating: { imdb: 8.2, rottenTomatoes: 92 },
    countryOfOrigin: "India",
    runtime: "3 hr 18 min",
    sequelPrequelAvailable: false,
    tags: ["bollywood", "action", "india", "classic", "gabbar singh"]
  },
  {
    id: 31,
    title: "Lagaan",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2001,
    director: "Ashutosh Gowariker",
    mainCast: "Aamir Khan, Gracy Singh, Rachel Shelley",
    genre: "Sports, Drama, Musical",
    synopsis: "In colonial India, villagers burdened with high taxes challenge the British officers to a game of cricket. If they win, their taxes will be waived. A patriotic, musical, and inspirational drama about courage and unity.",
    awards: "Academy Award nomination for Best Foreign Language Film.",
    rating: { imdb: 8.1, rottenTomatoes: 95 },
    countryOfOrigin: "India",
    runtime: "3 hr 44 min",
    sequelPrequelAvailable: false,
    tags: ["india", "cricket", "patriotism", "bollywood", "colonial era"]
  },
  {
    id: 32,
    title: "3 Idiots",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2009,
    director: "Rajkumar Hirani",
    mainCast: "Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor",
    genre: "Comedy, Drama",
    synopsis: "Three college friends navigate the pressures of India’s rigid education system while chasing their dreams. Rancho, their unconventional friend, inspires them to think differently about success, love, and life.",
    awards: "Filmfare Awards for Best Film, Best Director, Best Actor (Aamir Khan).",
    rating: { imdb: 8.4, rottenTomatoes: 100 },
    countryOfOrigin: "India",
    runtime: "2 hr 51 min",
    sequelPrequelAvailable: true,
    tags: ["bollywood", "college", "friendship", "education", "inspirational"]
  },
  {
    id: 33,
    title: "Taare Zameen Par",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2007,
    director: "Aamir Khan",
    mainCast: "Darsheel Safary, Aamir Khan, Tisca Chopra",
    genre: "Drama, Family",
    synopsis: "Ishaan, a dyslexic child struggling at school, finds hope and guidance when a new art teacher recognizes his creative potential. A heartfelt story about education, compassion, and parenting.",
    awards: "Filmfare Awards for Best Film, Best Director. India’s official entry for Oscars.",
    rating: { imdb: 8.3, rottenTomatoes: 92 },
    countryOfOrigin: "India",
    runtime: "2 hr 45 min",
    sequelPrequelAvailable: false,
    tags: ["bollywood", "childhood", "education", "disability", "emotional"]
  },
  {
    id: 34,
    title: "Dangal",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2016,
    director: "Nitesh Tiwari",
    mainCast: "Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra",
    genre: "Sports, Drama, Biography",
    synopsis: "Based on the real-life story of wrestler Mahavir Singh Phogat, who trains his daughters to become world-class wrestlers despite societal pressure. A powerful story about determination and breaking barriers.",
    awards: "Filmfare Awards for Best Film, Best Actor. Multiple international recognitions.",
    rating: { imdb: 8.3, rottenTomatoes: 88 },
    countryOfOrigin: "India",
    runtime: "2 hr 41 min",
    sequelPrequelAvailable: false,
    tags: ["wrestling", "india", "sports", "bollywood", "inspirational"]
  },
  {
    id: 35,
    title: "Gully Boy",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2019,
    director: "Zoya Akhtar",
    mainCast: "Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi",
    genre: "Drama, Music",
    synopsis: "Inspired by the lives of Mumbai street rappers, the film follows Murad, a young man who rises from the slums to become a hip-hop sensation. It’s a gritty and inspiring story of chasing dreams.",
    awards: "Filmfare Awards sweep with 13 wins including Best Film, Best Actor.",
    rating: { imdb: 7.9, rottenTomatoes: 95 },
    countryOfOrigin: "India",
    runtime: "2 hr 33 min",
    sequelPrequelAvailable: false,
    tags: ["hip hop", "rap", "mumbai", "dreams", "bollywood"]
  },
  {
    id: 36,
    title: "RRR",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2022,
    director: "S. S. Rajamouli",
    mainCast: "N. T. Rama Rao Jr., Ram Charan, Alia Bhatt, Ajay Devgn",
    genre: "Action, Drama, History",
    synopsis: "A fictional story set in the 1920s, imagining the lives of two legendary revolutionaries before they began their fight for independence. Packed with action, drama, and larger-than-life sequences.",
    awards: "Academy Award for Best Original Song (Naatu Naatu). Golden Globe winner.",
    rating: { imdb: 7.9, rottenTomatoes: 95 },
    countryOfOrigin: "India",
    runtime: "3 hr 7 min",
    sequelPrequelAvailable: false,
    tags: ["india", "freedom fighters", "epic", "bollywood", "patriotism"]
  },
  {
    id: 37,
    title: "Baahubali: The Beginning",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2015,
    director: "S. S. Rajamouli",
    mainCast: "Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah",
    genre: "Action, Fantasy, Drama",
    synopsis: "Raised in a small village, Shivudu discovers his royal heritage and embarks on a journey to reclaim his kingdom. Known for its groundbreaking VFX and epic storytelling.",
    awards: "National Film Award for Best Feature Film. Multiple Filmfare Awards.",
    rating: { imdb: 8.0, rottenTomatoes: 87 },
    countryOfOrigin: "India",
    runtime: "2 hr 39 min",
    sequelPrequelAvailable: true,
    tags: ["epic", "fantasy", "india", "mythical", "battle"]
  },
  {
    id: 38,
    title: "Baahubali: The Conclusion",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2017,
    director: "S. S. Rajamouli",
    mainCast: "Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah",
    genre: "Action, Fantasy, Drama",
    synopsis: "The epic conclusion reveals why Kattappa killed Baahubali and how Mahendra Baahubali avenges his father’s death. A grand cinematic experience filled with battles, drama, and emotion.",
    awards: "National Film Award for Best Special Effects. Multiple Filmfare Awards.",
    rating: { imdb: 8.2, rottenTomatoes: 86 },
    countryOfOrigin: "India",
    runtime: "2 hr 47 min",
    sequelPrequelAvailable: true,
    tags: ["epic", "battle", "india", "fantasy", "revenge"]
  },
  {
    id: 39,
    title: "The Grand Budapest Hotel",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2014,
    director: "Wes Anderson",
    mainCast: "Ralph Fiennes, Tony Revolori, Saoirse Ronan",
    genre: "Comedy, Drama",
    synopsis: "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero, the lobby boy who becomes his most trusted friend. Together, they are swept up in the theft of a priceless painting and the battle for a family fortune.",
    awards: "Won 4 Academy Awards including Best Costume Design and Best Production Design.",
    rating: { imdb: 8.1, rottenTomatoes: 92 },
    countryOfOrigin: "USA, Germany",
    runtime: "1 hr 39 min",
    sequelPrequelAvailable: false,
    tags: ["comedy", "friendship", "hotel", "europe", "style"]
  },
  {
    id: 40,
    title: "12 Angry Men",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 1957,
    director: "Sidney Lumet",
    mainCast: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    genre: "Drama, Crime",
    synopsis: "A jury of 12 men must decide the fate of a teenager accused of murdering his father. What begins as an open-and-shut case turns into an intense examination of prejudice, justice, and moral responsibility.",
    awards: "Nominated for 3 Academy Awards including Best Picture.",
    rating: { imdb: 9.0, rottenTomatoes: 100 },
    countryOfOrigin: "USA",
    runtime: "1 hr 36 min",
    sequelPrequelAvailable: false,
    tags: ["courtroom", "justice", "debate", "drama", "classic"]
  },
  {
    id: 41,
    title: "Amélie",
    isMustWatch: true,
    isHindiDubbed: false,
    yearOfRelease: 2001,
    director: "Jean-Pierre Jeunet",
    mainCast: "Audrey Tautou, Mathieu Kassovitz, Rufus",
    genre: "Romance, Comedy, Drama",
    synopsis: "Amélie, a shy Parisian waitress, decides to change the lives of those around her for the better while struggling with her own isolation. A whimsical tale of love, kindness, and destiny.",
    awards: "Won 4 César Awards, nominated for 5 Academy Awards.",
    rating: { imdb: 8.3, rottenTomatoes: 89 },
    countryOfOrigin: "France",
    runtime: "2 hr 2 min",
    sequelPrequelAvailable: false,
    tags: ["paris", "romance", "kindness", "drama", "french cinema"]
  },
  {
    id: 42,
    title: "The Lion King",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1994,
    director: "Roger Allers, Rob Minkoff",
    mainCast: "Matthew Broderick, Jeremy Irons, James Earl Jones",
    genre: "Animation, Adventure, Drama",
    synopsis: "Simba, a lion cub prince, flees his kingdom after the murder of his father, Mufasa. Guided by love, friendship, and destiny, he must return to reclaim his throne from his treacherous uncle Scar.",
    awards: "2 Academy Awards for Best Original Score and Best Original Song.",
    rating: { imdb: 8.5, rottenTomatoes: 93 },
    countryOfOrigin: "USA",
    runtime: "1 hr 28 min",
    sequelPrequelAvailable: true,
    tags: ["disney", "animation", "lion", "family", "africa"]
  },
  {
    id: 43,
    title: "Spirited Away",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2001,
    director: "Hayao Miyazaki",
    mainCast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
    genre: "Animation, Fantasy, Adventure",
    synopsis: "A young girl named Chihiro wanders into a mysterious world ruled by spirits, witches, and creatures. She must summon her courage to free her parents and return to the human world.",
    awards: "Academy Award for Best Animated Feature, Golden Bear at Berlinale.",
    rating: { imdb: 8.6, rottenTomatoes: 97 },
    countryOfOrigin: "Japan",
    runtime: "2 hr 5 min",
    sequelPrequelAvailable: false,
    tags: ["anime", "fantasy", "spirits", "adventure", "studio ghibli"]
  },
  {
    id: 44,
    title: "Coco",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2017,
    director: "Lee Unkrich, Adrian Molina",
    mainCast: "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
    genre: "Animation, Family, Fantasy",
    synopsis: "Miguel, a young boy with a passion for music, finds himself in the Land of the Dead. With the help of his ancestors, he must uncover his family's past and follow his dream of becoming a musician.",
    awards: "2 Academy Awards: Best Animated Feature and Best Original Song.",
    rating: { imdb: 8.4, rottenTomatoes: 97 },
    countryOfOrigin: "USA",
    runtime: "1 hr 45 min",
    sequelPrequelAvailable: false,
    tags: ["pixar", "family", "music", "afterlife", "mexico"]
  },
  {
    id: 45,
    title: "WALL·E",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2008,
    director: "Andrew Stanton",
    mainCast: "Ben Burtt, Elissa Knight, Jeff Garlin",
    genre: "Animation, Adventure, Sci-Fi",
    synopsis: "In a distant future where Earth is abandoned, a small waste-collecting robot named WALL·E discovers love and hope as he embarks on a space journey that may decide the fate of humanity.",
    awards: "Academy Award for Best Animated Feature.",
    rating: { imdb: 8.4, rottenTomatoes: 95 },
    countryOfOrigin: "USA",
    runtime: "1 hr 38 min",
    sequelPrequelAvailable: false,
    tags: ["pixar", "robot", "environment", "future", "sci-fi"]
  },
  {
    id: 46,
    title: "Inside Out",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2015,
    director: "Pete Docter, Ronnie del Carmen",
    mainCast: "Amy Poehler, Phyllis Smith, Richard Kind",
    genre: "Animation, Comedy, Family",
    synopsis: "Inside the mind of a young girl named Riley, five emotions—Joy, Sadness, Anger, Fear, and Disgust—struggle to guide her through a life-changing move. A heartfelt exploration of emotions and childhood.",
    awards: "Academy Award for Best Animated Feature.",
    rating: { imdb: 8.1, rottenTomatoes: 98 },
    countryOfOrigin: "USA",
    runtime: "1 hr 35 min",
    sequelPrequelAvailable: true,
    tags: ["pixar", "emotions", "family", "mind", "animated"]
  },
  {
    id: 47,
    title: "The Incredibles",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2004,
    director: "Brad Bird",
    mainCast: "Craig T. Nelson, Holly Hunter, Samuel L. Jackson",
    genre: "Animation, Action, Adventure",
    synopsis: "A family of undercover superheroes tries to live a quiet suburban life but are forced into action to save the world from a new villain. Packed with action, humor, and family values.",
    awards: "Academy Award for Best Animated Feature and Best Sound Editing.",
    rating: { imdb: 8.0, rottenTomatoes: 97 },
    countryOfOrigin: "USA",
    runtime: "1 hr 55 min",
    sequelPrequelAvailable: true,
    tags: ["pixar", "superhero", "family", "action", "adventure"]
  },
  {
    id: 48,
    title: "Up",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2009,
    director: "Pete Docter, Bob Peterson",
    mainCast: "Edward Asner, Jordan Nagai, Christopher Plummer",
    genre: "Animation, Adventure, Comedy",
    synopsis: "A 78-year-old balloon salesman fulfills his lifelong dream of a great adventure by tying thousands of balloons to his house and flying to South America, accidentally bringing along a young stowaway.",
    awards: "2 Academy Awards including Best Animated Feature and Best Original Score.",
    rating: { imdb: 8.3, rottenTomatoes: 98 },
    countryOfOrigin: "USA",
    runtime: "1 hr 36 min",
    sequelPrequelAvailable: false,
    tags: ["pixar", "adventure", "balloons", "friendship", "animated"]
  },
  {
    id: 49,
    title: "Finding Nemo",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 2003,
    director: "Andrew Stanton, Lee Unkrich",
    mainCast: "Albert Brooks, Ellen DeGeneres, Alexander Gould",
    genre: "Animation, Adventure, Comedy",
    synopsis: "After his son Nemo is captured, a timid clownfish named Marlin sets out on a daring journey across the ocean to rescue him, joined by the forgetful but lovable Dory.",
    awards: "Academy Award for Best Animated Feature.",
    rating: { imdb: 8.2, rottenTomatoes: 99 },
    countryOfOrigin: "USA",
    runtime: "1 hr 40 min",
    sequelPrequelAvailable: true,
    tags: ["pixar", "ocean", "fish", "family", "adventure"]
  },
  {
    id: 50,
    title: "Toy Story",
    isMustWatch: true,
    isHindiDubbed: true,
    yearOfRelease: 1995,
    director: "John Lasseter",
    mainCast: "Tom Hanks, Tim Allen, Don Rickles",
    genre: "Animation, Adventure, Comedy",
    synopsis: "Woody, a pull-string cowboy doll, feels threatened when Buzz Lightyear, a flashy new space ranger toy, joins the toy collection. Their rivalry turns into a heartwarming friendship as they embark on an unexpected adventure.",
    awards: "Special Academy Award for groundbreaking animation; nominated for 3 Oscars.",
    rating: { imdb: 8.3, rottenTomatoes: 100 },
    countryOfOrigin: "USA",
    runtime: "1 hr 21 min",
    sequelPrequelAvailable: true,
    tags: ["pixar", "toys", "friendship", "family", "animated"]
  },
];
