const recommendedEnglishSeries = [
  { title: "Breaking Bad", hindiDubbed: true },
  { title: "Better Call Saul", hindiDubbed: true },
  { title: "Stranger Things", hindiDubbed: true },
  { title: "The Boys", hindiDubbed: true },
  { title: "The Last of Us", hindiDubbed: true },
  { title: "The Night Agent", hindiDubbed: true },
  { title: "Mr. & Mrs. Smith", hindiDubbed: true },
  { title: "The Queen’s Gambit", hindiDubbed: true },
  { title: "Lucifer", hindiDubbed: true },
  { title: "Ozark", hindiDubbed: true },
  { title: "Game of Thrones", hindiDubbed: true },
  { title: "Reacher", hindiDubbed: true },
  { title: "The Lincoln Lawyer", hindiDubbed: true },
  { title: "The Gentlemen", hindiDubbed: true },
  { title: "Loki", hindiDubbed: true },
  { title: "Moon Knight", hindiDubbed: true },
  { title: "The Watcher", hindiDubbed: true },
  { title: "Wednesday", hindiDubbed: true },
  { title: "The Umbrella Academy", hindiDubbed: true },
  { title: "Severance", hindiDubbed: false },
  { title: "Money Heist", hindiDubbed: true },
  { title: "Berlin", hindiDubbed: true },
  { title: "Elite", hindiDubbed: true },
  { title: "Sky Rojo", hindiDubbed: true },
  { title: "Who Killed Sara?", hindiDubbed: true },
  { title: "Toy Boy", hindiDubbed: true },
  { title: "Valeria", hindiDubbed: true },
  { title: "Cable Girls", hindiDubbed: true },
  { title: "Dark", hindiDubbed: true },
  { title: "1899", hindiDubbed: true },
  { title: "Biohackers", hindiDubbed: false },
  { title: "Lupin", hindiDubbed: true },
  { title: "Marianne", hindiDubbed: true },
  { title: "Alice in Borderland", hindiDubbed: true },
  { title: "First Love", hindiDubbed: true },
  { title: "Erased", hindiDubbed: true },
  { title: "The Journalist", hindiDubbed: true },
  { title: "Narcos", hindiDubbed: true },
  { title: "Narcos: Mexico", hindiDubbed: true },
  { title: "Fauda", hindiDubbed: true },
  { title: "The Rain", hindiDubbed: true },
  { title: "Lost", hindiDubbed: true },
  { title: "Prison Break", hindiDubbed: true },
  { title: "Sherlock", hindiDubbed: true },
  { title: "Dexter", hindiDubbed: true },
  { title: "House M.D.", hindiDubbed: true },
  { title: "24", hindiDubbed: true },
  { title: "Hannibal", hindiDubbed: true },
  { title: "True Detective", hindiDubbed: true },
  { title: "The Sopranos", hindiDubbed: false },
  { title: "The Wire", hindiDubbed: false },
  { title: "Jack Ryan", hindiDubbed: true },
  { title: "Bodyguard", hindiDubbed: true },
  { title: "Designated Survivor", hindiDubbed: true },
  { title: "The Blacklist", hindiDubbed: true },
  { title: "Quantico", hindiDubbed: true },
  { title: "Alias", hindiDubbed: true },
  { title: "Person of Interest", hindiDubbed: true },
  { title: "Homeland", hindiDubbed: true },
  { title: "The Terminal List", hindiDubbed: true },
  { title: "Citadel", hindiDubbed: true },
  { title: "The Peripheral", hindiDubbed: true },
  { title: "The Recruit", hindiDubbed: true },
  { title: "Manifest", hindiDubbed: true },
  { title: "Travelers", hindiDubbed: true },
  { title: "Fringe", hindiDubbed: true },
  { title: "Black Mirror", hindiDubbed: true },
  { title: "The 100", hindiDubbed: true },
  { title: "Westworld", hindiDubbed: true },
  { title: "Sense8", hindiDubbed: true },
  { title: "The OA", hindiDubbed: true },
  { title: "The Leftovers", hindiDubbed: false },
  { title: "Utopia", hindiDubbed: true },
  { title: "3%", hindiDubbed: true },
  { title: "The Haunting of Hill House", hindiDubbed: true },
  { title: "The Haunting of Bly Manor", hindiDubbed: true },
  { title: "Midnight Mass", hindiDubbed: true },
  { title: "Locke & Key", hindiDubbed: true },
  { title: "Supernatural", hindiDubbed: true },
  { title: "The Witcher", hindiDubbed: true },
  { title: "Shadow and Bone", hindiDubbed: true },
  { title: "Sweet Tooth", hindiDubbed: true },
  { title: "Chilling Adventures of Sabrina", hindiDubbed: true },
  { title: "How to Get Away with Murder", hindiDubbed: true },
  { title: "Suits", hindiDubbed: true },
  { title: "Scandal", hindiDubbed: true },
  { title: "You", hindiDubbed: true },
  { title: "Dead to Me", hindiDubbed: true },
  { title: "Inventing Anna", hindiDubbed: true },
  { title: "Behind Her Eyes", hindiDubbed: true },
  { title: "The Undoing", hindiDubbed: true },
  { title: "Big Little Lies", hindiDubbed: true },
  { title: "The Good Wife", hindiDubbed: true },
  { title: "The Good Fight", hindiDubbed: true },
  { title: "This Is Us", hindiDubbed: true },
  { title: "The Morning Show", hindiDubbed: false },
  { title: "Little Fires Everywhere", hindiDubbed: true },
  { title: "Atypical", hindiDubbed: true },
  { title: "Sex Education", hindiDubbed: true },
  { title: "After Life", hindiDubbed: true },
  { title: "Fleabag", hindiDubbed: true },
  { title: "The End of the F***ing World", hindiDubbed: true },
  { title: "I Am Not Okay With This", hindiDubbed: true },
  { title: "Russian Doll", hindiDubbed: true },
  { title: "The Society", hindiDubbed: true },
  { title: "The Fall", hindiDubbed: true },
  { title: "Marcella", hindiDubbed: true },
  { title: "Mindhunter", hindiDubbed: true },
  { title: "Archive 81", hindiDubbed: true },
  { title: "Outer Banks", hindiDubbed: true },
  { title: "The Night Of", hindiDubbed: true }
];
const recommendedHindiSeries = [
  // 🔫 Crime / Thriller / Action
  { title: "Scam 1992", platform: "SonyLIV" },
  { title: "Mirzapur", platform: "Prime Video" },
  { title: "Paatal Lok", platform: "Prime Video" },
  { title: "Sacred Games", platform: "Netflix" },
  { title: "Rudra: The Edge of Darkness", platform: "Hotstar" },
  { title: "Dahaad", platform: "Prime Video" },
  { title: "Asur", platform: "JioCinema" },
  { title: "Criminal Justice", platform: "Hotstar" },
  { title: "The Night Manager", platform: "Hotstar" },
  { title: "Delhi Crime", platform: "Netflix" },
  { title: "Breathe: Into the Shadows", platform: "Prime Video" },
  { title: "Hostages", platform: "Hotstar" },
  { title: "Arya", platform: "Hotstar" },
  { title: "Mumbai Diaries", platform: "Prime Video" },
  { title: "Taj: Divided by Blood", platform: "Zee5" },
  { title: "Farzi", platform: "Prime Video" },
  { title: "Yeh Kaali Kaali Ankhein", platform: "Netflix" },
  { title: "Kohrra", platform: "Netflix" },
  { title: "CAT", platform: "Netflix" },

  // 🎭 Drama / Biographical
  { title: "Rocket Boys", platform: "SonyLIV" },
  { title: "The Family Man", platform: "Prime Video" },
  { title: "November Story", platform: "Hotstar" },
  { title: "Trial by Fire", platform: "Netflix" },
  { title: "Gyaarah Gyaarah", platform: "Zee5" },
  { title: "Tribhuwan Mishra: CA Topper", platform: "JioCinema" },
  { title: "Taaza Khabar", platform: "Hotstar" },
  { title: "Brinda", platform: "SonyLIV" },
  { title: "Dhootha", platform: "Prime Video" },
  { title: "Scoop", platform: "Netflix" },

  // ❤️ Romance / Youth / Feel-Good
  { title: "College Romance", platform: "SonyLIV / TVF" },
  { title: "Mismatched", platform: "Netflix" },
  { title: "Flames", platform: "Prime Video / TVF" },
  { title: "Bandish Bandits", platform: "Prime Video" },
  { title: "Little Things", platform: "Netflix" },
  { title: "Feels Like Ishq", platform: "Netflix" },

  // 🧠 Dark Comedy / Satire / Experimental
  { title: "Killer Soup", platform: "Netflix" },
  { title: "TVF Pitchers", platform: "Zee5" },
  { title: "TVF Aspirants", platform: "Prime Video" },
  { title: "TVF Gullak", platform: "SonyLIV" },
  { title: "Dhindora", platform: "YouTube" },
  { title: "Saas Bahu Aur Flamingo", platform: "Hotstar" },
  { title: "Panchayat", platform: "Prime Video" },

  // 🕵️‍♂️ Mystery / Sci-Fi / Experimental
  { title: "Typewriter", platform: "Netflix" },
  { title: "Betaal", platform: "Netflix" },
  { title: "Leila", platform: "Netflix" },
  { title: "The Forgotten Army", platform: "Prime Video" },
  { title: "Pill", platform: "JioCinema" },
  { title: "Class", platform: "Netflix" },
  { title: "Inside Edge", platform: "Prime Video" },
  { title: "Avrodh", platform: "SonyLIV" },
  { title: "Jamtara", platform: "Netflix" },

  // 🎯 Bonus Mini-Series / Anthologies
  { title: "Made in Heaven", platform: "Prime Video" },
  { title: "Ray", platform: "Netflix" },
  { title: "Kaala", platform: "Hotstar" },
  { title: "Crushed", platform: "Amazon miniTV" },
  { title: "Bang Baaja Baaraat", platform: "YouTube" },
  { title: "UNDEKHI", platform: "SonyLIV" },
  { title: "Illegal", platform: "Voot" }
];