const recommendedEnglishSeries = [
  { title: "Breaking Bad", hindiDubbed: true },
  { title: "Better Call Saul", hindiDubbed: true },
  { title: "Stranger Things", hindiDubbed: true },
  { title: "The Boys", hindiDubbed: true },
  { title: "The Last of Us", hindiDubbed: true },
  { title: "The Night Agent", hindiDubbed: true },
  { title: "Mr. & Mrs. Smith", hindiDubbed: true },
  { title: "The Queen’s Gambit", hindiDubbed: true },
  { title: "Lucifer", hindiDubbed: true },
  { title: "Ozark", hindiDubbed: true },
  { title: "Game of Thrones", hindiDubbed: true },
  { title: "Reacher", hindiDubbed: true },
  { title: "The Lincoln Lawyer", hindiDubbed: true },
  { title: "The Gentlemen", hindiDubbed: true },
  { title: "Loki", hindiDubbed: true },
  { title: "Moon Knight", hindiDubbed: true },
  { title: "The Watcher", hindiDubbed: true },
  { title: "Wednesday", hindiDubbed: true },
  { title: "The Umbrella Academy", hindiDubbed: true },
  { title: "Severance", hindiDubbed: false },
  { title: "Money Heist", hindiDubbed: true },
  { title: "Berlin", hindiDubbed: true },
  { title: "Elite", hindiDubbed: true },
  { title: "Sky Rojo", hindiDubbed: true },
  { title: "Who Killed Sara?", hindiDubbed: true },
  { title: "Toy Boy", hindiDubbed: true },
  { title: "Valeria", hindiDubbed: true },
  { title: "Cable Girls", hindiDubbed: true },
  { title: "Dark", hindiDubbed: true },
  { title: "1899", hindiDubbed: true },
  { title: "Biohackers", hindiDubbed: false },
  { title: "Lupin", hindiDubbed: true },
  { title: "Marianne", hindiDubbed: true },
  { title: "Alice in Borderland", hindiDubbed: true },
  { title: "First Love", hindiDubbed: true },
  { title: "Erased", hindiDubbed: true },
  { title: "The Journalist", hindiDubbed: true },
  { title: "Narcos", hindiDubbed: true },
  { title: "Narcos: Mexico", hindiDubbed: true },
  { title: "Fauda", hindiDubbed: true },
  { title: "The Rain", hindiDubbed: true },
  { title: "Lost", hindiDubbed: true },
  { title: "Prison Break", hindiDubbed: true },
  { title: "Sherlock", hindiDubbed: true },
  { title: "Dexter", hindiDubbed: true },
  { title: "House M.D.", hindiDubbed: true },
  { title: "24", hindiDubbed: true },
  { title: "Hannibal", hindiDubbed: true },
  { title: "True Detective", hindiDubbed: true },
  { title: "The Sopranos", hindiDubbed: false },
  { title: "The Wire", hindiDubbed: false },
  { title: "Jack Ryan", hindiDubbed: true },
  { title: "Bodyguard", hindiDubbed: true },
  { title: "Designated Survivor", hindiDubbed: true },
  { title: "The Blacklist", hindiDubbed: true },
  { title: "Quantico", hindiDubbed: true },
  { title: "Alias", hindiDubbed: true },
  { title: "Person of Interest", hindiDubbed: true },
  { title: "Homeland", hindiDubbed: true },
  { title: "The Terminal List", hindiDubbed: true },
  { title: "Citadel", hindiDubbed: true },
  { title: "The Peripheral", hindiDubbed: true },
  { title: "The Recruit", hindiDubbed: true },
  { title: "Manifest", hindiDubbed: true },
  { title: "Travelers", hindiDubbed: true },
  { title: "Fringe", hindiDubbed: true },
  { title: "Black Mirror", hindiDubbed: true },
  { title: "The 100", hindiDubbed: true },
  { title: "Westworld", hindiDubbed: true },
  { title: "Sense8", hindiDubbed: true },
  { title: "The OA", hindiDubbed: true },
  { title: "The Leftovers", hindiDubbed: false },
  { title: "Utopia", hindiDubbed: true },
  { title: "3%", hindiDubbed: true },
  { title: "The Haunting of Hill House", hindiDubbed: true },
  { title: "The Haunting of Bly Manor", hindiDubbed: true },
  { title: "Midnight Mass", hindiDubbed: true },
  { title: "Locke & Key", hindiDubbed: true },
  { title: "Supernatural", hindiDubbed: true },
  { title: "The Witcher", hindiDubbed: true },
  { title: "Shadow and Bone", hindiDubbed: true },
  { title: "Sweet Tooth", hindiDubbed: true },
  { title: "Chilling Adventures of Sabrina", hindiDubbed: true },
  { title: "How to Get Away with Murder", hindiDubbed: true },
  { title: "Suits", hindiDubbed: true },
  { title: "Scandal", hindiDubbed: true },
  { title: "You", hindiDubbed: true },
  { title: "Dead to Me", hindiDubbed: true },
  { title: "Inventing Anna", hindiDubbed: true },
  { title: "Behind Her Eyes", hindiDubbed: true },
  { title: "The Undoing", hindiDubbed: true },
  { title: "Big Little Lies", hindiDubbed: true },
  { title: "The Good Wife", hindiDubbed: true },
  { title: "The Good Fight", hindiDubbed: true },
  { title: "This Is Us", hindiDubbed: true },
  { title: "The Morning Show", hindiDubbed: false },
  { title: "Little Fires Everywhere", hindiDubbed: true },
  { title: "Atypical", hindiDubbed: true },
  { title: "Sex Education", hindiDubbed: true },
  { title: "After Life", hindiDubbed: true },
  { title: "Fleabag", hindiDubbed: true },
  { title: "The End of the F***ing World", hindiDubbed: true },
  { title: "I Am Not Okay With This", hindiDubbed: true },
  { title: "Russian Doll", hindiDubbed: true },
  { title: "The Society", hindiDubbed: true },
  { title: "The Fall", hindiDubbed: true },
  { title: "Marcella", hindiDubbed: true },
  { title: "Mindhunter", hindiDubbed: true },
  { title: "Archive 81", hindiDubbed: true },
  { title: "Outer Banks", hindiDubbed: true },
  { title: "The Night Of", hindiDubbed: true }
];
const recommendedHindiSeries = [
  {
    title: "Scam 1992",
    platform: "SonyLIV",
    genre: "Crime",
    year: 2020,
    popularity: 95,
    seasons: 1,
    episodes: 10,
    runtime: "50–60 min"
  },
  {
    title: "Mirzapur",
    platform: "Prime Video",
    genre: "Thriller",
    year: 2018,
    popularity: 97,
    seasons: 2,
    episodes: 19,
    runtime: "45–60 min"
  },
  {
    title: "Paatal Lok",
    platform: "Prime Video",
    genre: "Crime",
    year: 2020,
    popularity: 92,
    seasons: 1,
    episodes: 9,
    runtime: "45–55 min"
  },
  {
    title: "Sacred Games",
    platform: "Netflix",
    genre: "Thriller",
    year: 2018,
    popularity: 94,
    seasons: 2,
    episodes: 16,
    runtime: "45–60 min"
  },
  {
    title: "Rudra: The Edge of Darkness",
    platform: "Hotstar",
    genre: "Thriller",
    year: 2022,
    popularity: 84,
    seasons: 1,
    episodes: 6,
    runtime: "45–55 min"
  },
  {
    title: "Dahaad",
    platform: "Prime Video",
    genre: "Crime",
    year: 2023,
    popularity: 88,
    seasons: 1,
    episodes: 8,
    runtime: "50–60 min"
  },
  {
    title: "Asur",
    platform: "JioCinema",
    genre: "Mystery",
    year: 2020,
    popularity: 91,
    seasons: 2,
    episodes: 16,
    runtime: "40–50 min"
  },
  {
    title: "Criminal Justice",
    platform: "Hotstar",
    genre: "Crime",
    year: 2019,
    popularity: 89,
    seasons: 3,
    episodes: 22,
    runtime: "40–50 min"
  },
  {
    title: "The Night Manager",
    platform: "Hotstar",
    genre: "Thriller",
    year: 2023,
    popularity: 86,
    seasons: 1,
    episodes: 7,
    runtime: "45–55 min"
  },
  {
    title: "Delhi Crime",
    platform: "Netflix",
    genre: "Crime",
    year: 2019,
    popularity: 94,
    seasons: 2,
    episodes: 11,
    runtime: "45–60 min"
  },
  {
    title: "Breathe: Into the Shadows",
    platform: "Prime Video",
    genre: "Thriller",
    year: 2020,
    popularity: 85,
    seasons: 2,
    episodes: 20,
    runtime: "45–55 min"
  },
  {
    title: "Hostages",
    platform: "Hotstar",
    genre: "Thriller",
    year: 2019,
    popularity: 82,
    seasons: 2,
    episodes: 22,
    runtime: "40–50 min"
  },
  {
    title: "Arya",
    platform: "Hotstar",
    genre: "Crime",
    year: 2020,
    popularity: 87,
    seasons: 3,
    episodes: 24,
    runtime: "45–55 min"
  },
  {
    title: "Mumbai Diaries",
    platform: "Prime Video",
    genre: "Drama",
    year: 2021,
    popularity: 84,
    seasons: 2,
    episodes: 16,
    runtime: "40–50 min"
  },
  {
    title: "Taj: Divided by Blood",
    platform: "Zee5",
    genre: "Historical Drama",
    year: 2023,
    popularity: 83,
    seasons: 2,
    episodes: 20,
    runtime: "40–50 min"
  },
  {
    title: "Farzi",
    platform: "Prime Video",
    genre: "Thriller",
    year: 2023,
    popularity: 93,
    seasons: 1,
    episodes: 8,
    runtime: "50–60 min"
  },
  {
    title: "Yeh Kaali Kaali Ankhein",
    platform: "Netflix",
    genre: "Thriller",
    year: 2022,
    popularity: 88,
    seasons: 1,
    episodes: 8,
    runtime: "35–45 min"
  },
  {
    title: "Rocket Boys",
    platform: "SonyLIV",
    genre: "Biographical",
    year: 2022,
    popularity: 90,
    seasons: 2,
    episodes: 16,
    runtime: "45–55 min"
  },
  {
    title: "The Family Man",
    platform: "Prime Video",
    genre: "Drama",
    year: 2019,
    popularity: 95,
    seasons: 2,
    episodes: 19,
    runtime: "40–55 min"
  },
  {
    title: "November Story",
    platform: "Hotstar",
    genre: "Crime Drama",
    year: 2021,
    popularity: 80,
    seasons: 1,
    episodes: 7,
    runtime: "40–50 min"
  },
  {
    title: "Trial by Fire",
    platform: "Netflix",
    genre: "Biographical",
    year: 2023,
    popularity: 84,
    seasons: 1,
    episodes: 7,
    runtime: "45–55 min"
  },
  {
    title: "Gyaarah Gyaarah",
    platform: "Zee5",
    genre: "Mystery Drama",
    year: 2024,
    popularity: 78,
    seasons: 1,
    episodes: 9,
    runtime: "40–50 min"
  },
  {
    title: "Tribhuwan Mishra: CA Topper",
    platform: "JioCinema",
    genre: "Comedy Drama",
    year: 2024,
    popularity: 76,
    seasons: 1,
    episodes: 8,
    runtime: "30–40 min"
  },
  {
    title: "Taaza Khabar",
    platform: "Hotstar",
    genre: "Fantasy Drama",
    year: 2023,
    popularity: 85,
    seasons: 1,
    episodes: 6,
    runtime: "30–40 min"
  },
  {
    title: "Brinda",
    platform: "SonyLIV",
    genre: "Crime Drama",
    year: 2024,
    popularity: 75,
    seasons: 1,
    episodes: 8,
    runtime: "40–50 min"
  },
  {
    title: "Dhootha",
    platform: "Prime Video",
    genre: "Supernatural Thriller",
    year: 2023,
    popularity: 82,
    seasons: 1,
    episodes: 8,
    runtime: "45–55 min"
  },
  {
    title: "College Romance",
    platform: "SonyLIV / TVF",
    genre: "Romance / Comedy",
    year: 2018,
    popularity: 86,
    seasons: 4,
    episodes: 20,
    runtime: "25–30 min"
  },
  {
    title: "Mismatched",
    platform: "Netflix",
    genre: "Romance / Youth",
    year: 2020,
    popularity: 83,
    seasons: 2,
    episodes: 12,
    runtime: "30–35 min"
  },
  {
    title: "Flames",
    platform: "Prime Video / TVF",
    genre: "Romance / Youth",
    year: 2018,
    popularity: 84,
    seasons: 3,
    episodes: 15,
    runtime: "25–30 min"
  },
  {
    title: "Bandish Bandits",
    platform: "Prime Video",
    genre: "Romance / Musical",
    year: 2020,
    popularity: 85,
    seasons: 1,
    episodes: 10,
    runtime: "35–45 min"
  },
  {
    title: "Little Things",
    platform: "Netflix",
    genre: "Romance / Slice of Life",
    year: 2016,
    popularity: 88,
    seasons: 4,
    episodes: 29,
    runtime: "20–30 min"
  },
  {
    title: "Feels Like Ishq",
    platform: "Netflix",
    genre: "Romance / Anthology",
    year: 2021,
    popularity: 78,
    seasons: 1,
    episodes: 6,
    runtime: "25–30 min"
  },
recommendedHindiSeries.push(
  {
    title: "Killer Soup",
    platform: "Netflix",
    genre: "Dark Comedy",
    year: 2024,
    popularity: 87,
    seasons: 1,
    episodes: 8,
    runtime: "50–55 min"
  },
  {
    title: "TVF Pitchers",
    platform: "Zee5",
    genre: "Drama / Satire",
    year: 2015,
    popularity: 92,
    seasons: 2,
    episodes: 10,
    runtime: "30–45 min"
  },
  {
    title: "TVF Aspirants",
    platform: "Prime Video",
    genre: "Drama / Satire",
    year: 2021,
    popularity: 91,
    seasons: 2,
    episodes: 10,
    runtime: "35–45 min"
  },
  {
    title: "TVF Gullak",
    platform: "SonyLIV",
    genre: "Family / Satire",
    year: 2019,
    popularity: 90,
    seasons: 4,
    episodes: 20,
    runtime: "25–30 min"
  },
  {
    title: "Dhindora",
    platform: "YouTube",
    genre: "Comedy / Experimental",
    year: 2021,
    popularity: 85,
    seasons: 1,
    episodes: 8,
    runtime: "15–25 min"
  },
  {
    title: "Saas Bahu Aur Flamingo",
    platform: "Hotstar",
    genre: "Action / Satire",
    year: 2023,
    popularity: 85,
    seasons: 1,
    episodes: 8,
    runtime: "45–55 min"
  }
);
];